### ISSUE TITLE
bug - Unit description is repeated 3 times

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#101]
In current implementation of PR #91, on a case details the description for the unit is repeated 3 times
![image](https://user-images.githubusercontent.com/31331637/35689414-6423a74a-07ae-11e8-9eb9-b0f9e5027ad4.png)

In the BZFE the description for that unit is correct

![image](https://user-images.githubusercontent.com/31331637/35689449-84543ea8-07ae-11e8-93db-cd7197d4e428.png)

**Comment by franck-boullier** [comment]
@nbiton issue seems to be a simple typo in the code line 121 of  'imports/ui/case/case-details.jsx'

+          <div className='gray lh-dbl'>
+            {unitItem.description}{unitItem.description}{unitItem.description}
+          </div>

**Comment by nbiton** [comment]
That's a bit embarrasing... I used it for testing multiline text and forgot to remove it

**Comment by nbiton** [comment]
@franck-boullier I fixed that line on commit 4588c7e. Should be ok now.

**Comment by franck-boullier** [comment]
fixed in latest version of PR #91
