### ISSUE TITLE
bug - HTML code in a comment or description is not interpreted correctly

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#103]
Case description and case comments, as well as unit and role description can include html styling and line breaks.

In the current version of PR#91 the html styling is not interpreted for case comment
comment in the MEFE
<img width="238" alt="comment_no_line_breaks" src="https://user-images.githubusercontent.com/31331637/35701970-b765b352-07d2-11e8-9719-bfe1f94e8621.png">

Same comment in the BZFE
<img width="545" alt="case_description_has_line_breaks_in_bzfe" src="https://user-images.githubusercontent.com/31331637/35701985-c243b8aa-07d2-11e8-8f67-38fe883cf244.png">

See also a unit description in the MEFE
<img width="240" alt="html_not_interpreted_in_unit_description" src="https://user-images.githubusercontent.com/31331637/35702003-d18cf25e-07d2-11e8-87e5-b90ae3a8171d.png">

**Comment by kaihendry** [comment]
Meteor should treat text as markdown? https://docs.meteor.com/packages/markdown.html

That way HTML should be let through. Some **sanitization** needs to be happen (and ideally defined) though at some point.

**Comment by franck-boullier** [comment]
Closing this: this will not be a problem since all the information about a unit shall come from the MEFE: the source of truth for information about a unit see issue #283 for more details on how the solution was implemented
