### ISSUE TITLE
Measure viral coefficient

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#116]
Based on the data in:

* db.pendingInvitations
* db.users

Hopefully we can create a metric to show how users are sharing / inviting other users to use the system to manage their property.

On advice, I've been told to read up on [Adam Nash's material](https://adamnash.blog/2012/03/28/product-leaders-user-acquisition-series/) and account for "cycle time". Not sure what that means, probably the delay of uptake.

Do we count the user as on boarded from the [invitation stage](https://github.com/unee-t/frontend/issues/114) or when they complete sign up?

**Comment by kaihendry** [comment]
We need to answer the question:

* "In the last X days, how many non-users have been invited?" - will this include re-invitations?

Perhaps this new sign up *conversion metric* can be measured in another way, though also:

* "In the last X days, how many non-users have completed sign up via an invite?" - there could be a delay from when the invite was sent, and when it was acted upon. Does it matter?

**Comment by kaihendry** [comment]
# In the last X days, how many non-users have been invited?

Look at User table. Query by createdAt, i.e. the time when they were first invited to join a  case
Filter by invitedToCases.done true (i.e. they have been processed on the Bugzilla end)
This doesn't account for conversions. Only gives an indication on how invites were sent in the query period.

# In the last X days, how many non-users have completed sign up via an invite?

Looking at the user table in Mongo @nbiton, I don't think I can tell exactly when a new sign up converted.

<img src="https://s.natalian.org/2018-03-08/1520507672_2548x1398.png">

resume.loginTokens.when's date seems to get updated the user logs in with the magic link. I noticed accessedCount increments, but ideally each access had a timestamp so I would know when the user logged in.

**Comment by kaihendry** [comment]
Note we are re-jigging this to be on a per house/product bases since you cannot invite a user to another case if he/she has already been invited to that property already. So it makes most sense to track invites per property instead of per case.

**Comment by franck-boullier** [comment]
I agree and I'm OK with that!
