### ISSUE TITLE
Invitation - Need to know if user is the first in this role

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#118]
in the current version of the master, the API for pending invitation does not differentiate 
1- user is the first 'real' user in that role for that unit
from
2- user is an additional user in this role for this unit and we already have a 'real' user for that role for that unit.

We need to have that information to know what to do in the BZ database when we process the invitation.

**Comment by nbiton** [comment]
Is this still relevant?

**Comment by franck-boullier** [comment]
No this is not relevant anymore: I found a way to handle that in the SQL script that we run when we process the invitation in the BZ database.
