### ISSUE TITLE
When posting a comment - comment disappears after a while

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#123]
In PR#122 when a user post a new comment the comment is created and disappears after a few seconds.

The comment is visible again if we refresh the browser window

**Comment by franck-boullier** [comment]
This seems to be fixed in PR #122 now

**Comment by nbiton** [comment]
No change was really made. I'm suspecting it might be an API timeout issue on BZ.

**Comment by franck-boullier** [comment]
Maybe adding the logs slowed down the MEFE somehow giving BZ time to send the response when the MEFE was expecting it?
Is there a way to make the timeout a little longer to avoid this type of issue to reappear?

**Comment by nbiton** [comment]
The logs I added are trivial, and should have no significant impact on the timing. I'm not aware of a setting that can affect the timeout length, but I'm suspecting that it might be the case since we've experienced other issues with it before, and the sporadic nature of this issue.

**Comment by franck-boullier** [comment]
OK, let's not get to stuck on this then so we can get the pilot out ASAP

**Comment by franck-boullier** [comment]
Error reappears in the latest tests done on PR #122.
Reopening that for future reference.
Let's not get this delay the MVP and treat that as a bug we'll fix at a later stage...
