### ISSUE TITLE
Users in the list of invitees are listed twice after invitation is processed

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#124]
In the latest version of the PR, after the invitation is processed, the users in the list of invitee are duplicated.
![image](https://user-images.githubusercontent.com/31331637/36184300-d4852cac-116d-11e8-8334-90f30f9fbe65.png)

**Comment by nbiton** [comment]
Which issue can I test this on?

**Comment by franck-boullier** [comment]
Case 61906

**Comment by franck-boullier** [comment]
fixed in latest version of PR #122
