### ISSUE TITLE
Invitation email is not received

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#129]
# How to replicate the Issue:
In the latest version of the Master - in the DEV environment
Go to case 58260
- Invite a new user (user must not exist in the BZFE already - see issue #128 ) PASSED
- Process the invitation (I used Postman) PASSED
- Check that the user is in CC of the case in the dashboard PASSED
- Go to the mailbox of the invitee. 
# Expected result
- Email with Magic link is visible in the invitee mailbox.
# Actual result
- No email received in the invitee mailbox
# Diagnosis steps:
- Wait for the email to travel the internet - Waited 15mn +
- As the invitor, check if Invitee is visible in the MEFE as invited PASSED
- Check that the email engine works PASSED (the BZFE sends an email each time the case is updated)
- Check Spambox PASSED - nothing there.

**Comment by kaihendry** [comment]
This is on https://dev.case.unee-t.com/ ? Could you please paste you Postman request here?
 
We need a cheaper mail check from Meteor.

**Comment by franck-boullier** [comment]
@kaihendry 
'This is on https://dev.case.unee-t.com/ ?' yes
'Could you please paste you Postman request here?' 
https://dev.case.unee-t.com/api/pending-invitations/done?accessToken=[access token for dev]
I got no error messge from that request

**Comment by kaihendry** [comment]
![mail_url](https://user-images.githubusercontent.com/765871/36371875-5f98cce8-159e-11e8-8cdb-f75f1368209e.png)

Can see from meteor logs MAIL_URL is not set https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=meteor;stream=08c573967fa5fc081d75b37bc915c43fb338cb348a0bb542b989f12cd26ec330

**Comment by franck-boullier** [comment]
AhAh!
@kaihendry: Good catch! Now we need to understand how to configure the MAIL_URL I guess...

**Comment by kaihendry** [comment]
@franck-boullier can you try again now please? I don't know the token.

**Comment by franck-boullier** [comment]
I'll re-create an invitation to do the end to end process, give me 5mn...

**Comment by franck-boullier** [comment]
@kaihendry 
Bravo! That was it: I have received the email invitation as expected

We probably need to document how to configure the MAIL_URL in each environment so we don't have the same issue in the future

**Comment by kaihendry** [comment]
I created https://github.com/unee-t/frontend/pull/130 which was the missing piece.

**Comment by franck-boullier** [comment]
@nbiton feel free to close this issue once you've reviewed and merged PR #130 :-)
