### ISSUE TITLE
Do we need to create an API key when we create a new BZ user?

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#14]
One authentication method to access the BZ installation is to user the user credentials for the rest API (login/password).

A more robust way to do this is to use the API key for the user. The benefit is that we won't pass the login/password anymore: these could be used to access the BZFE directly.

In order to do this we need to create the API for each user in the BZFE and make sure the MEFE has this API too.

This issue it to discuss when and how we could do that

**Comment by kaihendry** [comment]
Isn't this related or the same as https://github.com/unee-t/bugzilla-customisation/issues/9 ?

e.g. "the API key problem for each user" problem

**Comment by nbiton** [comment]
The other issue is about the admin API key as an environment variable. This is about individual users' API key. I don't think it's really related.

**Comment by franck-boullier** [comment]
@naor is correct: these are 2 different issues and this one is indeed about the indvidual API key for the BZFE users that we need to create.

**Comment by franck-boullier** [comment]
Answer is yes.
Ssee issue #178
