### ISSUE TITLE
chore - we need to get the GA tracking code in the MEFE

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#140]
I'd like to be able to monitor the traffic and usage with Google Analytics.

In order to do that we need to inject the GA tracking code in the MEFE

My guess is that we can probably do that with an environment variable and place this somewhere here
https://github.com/unee-t/frontend/blob/44e8104cd39c1605e57ef649067b29a7b1ddf84a/client/main.html

@nbiton and @kaihendry any comment/idea/suggestions?

**Comment by franck-boullier** [comment]
@kaihendry how could we get the Google Analytic Tracking code in an environment variable so that it's properly setup when we do a deployment?

**Comment by kaihendry** [comment]
The Google Analytucs (GA) tracking id looks like "UA-XXXXXX-X" and that can be saved under an env variable like **GA_TRACKING_ID**

**Comment by franck-boullier** [comment]
sounds good to me.
I've created the following parameters for the prod and the dev environment already:
- GA_TRACKING_ID_MEFE for the Meteor Front End (case)
- GA_TRACKING_ID_BZFE for the Bugzilla Front End (dashboard)

I have included the full GA script there (not only the GA tracking code) to make it easier to inject.

We now need to make sure that they are included when we do a deployment.

@kaihendry can you look into that?

**Comment by kaihendry** [comment]
https://s.natalian.org/2018-03-06/gsuite.mp4 <-- we are missing the actual code.

Can we establish a G-suite for the unee-t.com? I think this will make it easier to administer things like:

* email
* analytics
* browser profiles
* internal only stuff
* google meetings

**Comment by franck-boullier** [comment]
@kaihendry "https://s.natalian.org/2018-03-06/gsuite.mp4 <-- we are missing the actual code"
I used a dummy code in the DEV environment and used the actual one in the LIVE parameter variables
![image](https://user-images.githubusercontent.com/31331637/37021708-7483abd2-215b-11e8-854a-eeb4be0117c2.png)

That code is LIVE

**Comment by franck-boullier** [comment]
@kaihendry not sure I understand what you mean by "Can we establish a G-suite for the unee-t.com?" I don't know how it would help in the context of GA tracking. Can you help me better understand why we should have a G-Suite setup?
