### ISSUE TITLE
feature - Interface to create a new unit

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#145]
As part of the pilot and demo I'd like to do @MTEC I expect/hope that a lot of users will ask to try Unee-T out and will ask to create one or more unit.

The interface to create a unit exists today in Invision
![image](https://user-images.githubusercontent.com/31331637/36964877-eb794a2c-2092-11e8-8913-271ff199271a.png)

It would be good to have this interface available in the MEFE and the information entered int this form saved in a Mongo collection that would be accessible via an API initially (similar to what we have for invitation).

This way:
- The prospective users will be able to experience the 'unit creation' interface in the MEFE (with a temporary message that would tell them that this still need to be approved for Pilot before the unit is visible in their list of units.)
- The units would be available in the MEFE already.
- It would be very easy to create them in the BZFE using the SQL script that already exist (no missing information - process similar to the inviation creation process).

The alternative is to create a form in the Unee-T website which would capture all the information that will be in that future screen so that pilot user can enter these until the front end is ready.
Issue with that workaround is that we will have to re-create these units in the MEFE at a later stage and link these unit to the corresponding BZ product_id (which might be a PITA)...

@nbiton can you update this and give me an idea if this is feasible so that I knows if I need to create the alternative form in the Unee-T website or not.

This should be done AFTER issue #136, #99, #70 and #108: these 5 issues are show stoppers for the pilot but ideally before #109, #60 and #20

**Comment by franck-boullier** [comment]
Lable removed as we have a workaround

**Comment by kaihendry** [comment]
Is this the same as https://github.com/unee-t/frontend/issues/7 ?

**Comment by kaihendry** [comment]
IIUC a whole bunch of SQL scripts needs to be run to setup a unit? Could you please reference said scripts and their arguments? Furthermore any assertions/tests that can be implemented so that we know that the Unit is created correctly.

**Comment by franck-boullier** [comment]
The Flow for the Unit creation can be seen in the [Realtim Board](https://realtimeboard.com/app/board/o9J_k0ckGU4=/).

**Comment by franck-boullier** [comment]
@kai, answering your above questions to close the loop:
Most of the answer to the API related issue can be found in the [invite repository](https://github.com/unee-t/invite).

"IIUC a whole bunch of SQL scripts needs to be run to setup a unit? "
No, we just need 1 SQL script
"Could you please reference said scripts and their arguments?"
See the [invite repository](https://github.com/unee-t/invite).

"tests that can be implemented so that we know that the Unit is created correctly."
See the [invite repository](https://github.com/unee-t/invite).

**Comment by franck-boullier** [comment]
See also the [screens in invision](https://projects.invisionapp.com/d/main#/console/12250377/299136062/preview).

**Comment by franck-boullier** [comment]
This works in the current version of Unee-T
