### ISSUE TITLE
Invitation still visible as 'pending' after they have been processed

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#147]
In the API accessible view for the pending invitation, processed invitation are still visible.

Expected result:
The pending invitation are not visible in the list of pending invitation after they are processed

I think it used to work, not sure why not anymore...

![image](https://user-images.githubusercontent.com/31331637/37042656-db3f8812-2199-11e8-9997-a99992d3772e.png)

**Comment by nbiton** [comment]
I'm guessing there might be an issue which causes the 'PUT /api/pending-invitations/done' to not mark these invitations as "done".
Did the http request go through fine with no errors? (You can try it again with the same ids, there should be no harm in that)

**Comment by franck-boullier** [comment]
I just did the PUT again:
- No error while doing the PUT
- Invitation are still in the list of pending invites

**Comment by franck-boullier** [comment]
![image](https://user-images.githubusercontent.com/31331637/37066258-94d5204e-21df-11e8-98a7-d5d24226e0d6.png)

**Comment by kaihendry** [comment]
Is there no accompanying debug info in https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=meteor;

**Comment by franck-boullier** [comment]
@kaihendry "Is there no accompanying debug info in https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=meteor;"
nothing there

**Comment by franck-boullier** [comment]
Error was that I used the incorrect URL (duh!)
It works when I use
https://case.unee-t.com/api/pending-invitations/done?accessToken=[token]
