### ISSUE TITLE
Username/Password for unee-t-staging ?

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#152]
Could this please be put in EC2 parameter store:

* CLOUDINARY_STAGING_USER
* CLOUDINARY_STAGING_PASS

Just want to get a better idea of how the media is stored. My aim is get the images prefixed or at least with some sort of metadata tagged.

**Comment by kaihendry** [comment]
Or we could have in every AWS account:

* CLOUDINARY_USER
* CLOUDINARY_PASS

**Comment by franck-boullier** [comment]
I'm just seeing  this
Will work on that in a few hours

**Comment by franck-boullier** [comment]
"Or we could have in every AWS account:
    CLOUDINARY_USER
    CLOUDINARY_PASS
---
I prefer this approach actually...

**Comment by franck-boullier** [comment]
Done for the DEMO environment.

**Comment by franck-boullier** [comment]
Done for the DEV environment

**Comment by franck-boullier** [comment]
Done for the LIVE environment
