### ISSUE TITLE
Minor: Risk of user being locked out if the password supplied to bugzilla is repeatedly wrong

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#160]
![locked-out](https://user-images.githubusercontent.com/765871/37322925-7e0e1a2e-26bb-11e8-9239-955f69f2d9d4.png)

I mistakenly did this via the the front end sign up form http://localhost:3000/signup

**Comment by nbiton** [comment]
This happened while you were using the "existing BZ user" sub-form, right?
That form is only a temporary solution for onboarding existing BZ users onto MEFE. This wouldn't happen in our "normal" use case

**Comment by franck-boullier** [comment]
this should not happen now that we are unsing the API key mechanism to authenticate the user
