### ISSUE TITLE
Simple search by case number

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#164]
Need to give the user the ability to enter a case number.
If user is allowed to see the case, then case is displayed.

This makes issue #60 less critical

**Comment by kaihendry** [comment]
Should there be a URL route for case number? e.g. For case 5, https://case.unee-t.com/5

**Comment by nbiton** [comment]
There is. It's /case/<number>

**Comment by franck-boullier** [comment]
fixed in PR #678
