### ISSUE TITLE
Confirmation button for new user first and last name is not accessible on smaller screens

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#166]
When we invite user, we send an email with a magic link (after invitation is processed).

The magic link sends the user to a dialogue that asks him/her to enter his/her first and last name.

On smaller screens the button to enter/validate is only partially visible. The modal window is not scrollable.
This make it difficult to understand what needs to be done.

We need to make sure that this screen works also on smaller screens

**Comment by kaihendry** [comment]
Screenshots or it didn't happen

**Comment by franck-boullier** [comment]
see also issue #254

**Comment by franck-boullier** [comment]
We need to understand the root cause of this to make sure that the next release in the prod environment does not have the same issue!

**Comment by nbiton** [comment]
Test on #255

**Comment by nbiton** [comment]
It's an exact clone of #254 , right?

**Comment by franck-boullier** [comment]
closing as this is a duplicate of issue #254
