### ISSUE TITLE
Meteor logging to Cloudwatch is poor

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#176]
Lines are broken. The whole JSON string should be logged as a line. Not like this:

<img src="https://s.natalian.org/2018-03-26/1522035681_2558x1406.png">

**Comment by kaihendry** [comment]
https://forums.meteor.com/t/stop-console-logs-getting-split-between-lines/42892

**Comment by kaihendry** [comment]
I think we have improved logging to JSON:
https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=meteor;filter=%257B%2520%2524.title%2520%253D%2520%2522error%2522%2520%257D;start=P1D

However we need perhaps better use of log levels. E.g.

`{
    "timestamp": "2019-03-25T03:14:47+0000",
    "title": "error",
    "file": "post-process-db-change-message.js",
    "line": "220",
    "method": "Set.forEach.userId",
    "message": "User with bz id 8018 has no verified email address, skipping notification"
}`

Should probably be a loglevel of **warn**, not error.

**Comment by franck-boullier** [comment]
Closing this as we have implemented a lot of improvements in the Meteor logs
