### ISSUE TITLE
BZ Token expires after a certain period if user has not logged in - Invitation won't work

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#178]
If we try to invite a user that has not logged in for a while, the token has expired.

Issue: the magic link expects the token in the MEFE to be valid.
Because the token is expired, the magic link does not work.

**Comment by franck-boullier** [comment]
Trying to reset the password in the MEFE does NOT seem to fix the issue.

**Comment by franck-boullier** [comment]
The error message:
![image](https://user-images.githubusercontent.com/31331637/37914479-e18cbcd4-3149-11e8-9202-6e687e106365.png)

**Comment by franck-boullier** [comment]
Temporary workaround is to
1- Reset the user password in the BZFE
2- Log in as the user in the BZFE
3- DO NOT logout
4- go in the BZ db in the table 'logincookies' and find the value of the cookie
5- go to the MongoDB in the 'user' collection and replace the value of the old 'token' with the value of the newly created cookie (found in step 4)
6- click on the magic link in the invitation

**Comment by franck-boullier** [comment]
Long term solution is to change the way we authenticate users in the BZFE: we need to use the BZ user API Key instead of the logincookie for the user.
This means that we need to change several things:

# Change the way we create user:
During the user creation process, in the MEFE, we need the MEFE to:
1- Create the BZ user as we create it today.
2- Generate a random (and unique) API key: varchar(40) and store it in the MEFE.
3- Use the same mechanism that we use to pass information from the MEFE to the BZFE to add the following information into the BZ DB table `user_api_keys`:
  - `user_id` - mediumint(9):  the BZ user id of the user
  - `api_key` - varchar(40) : the API Key that the MEFE has generated
  - `description` - varchar(255) : The description of the key. We use the default description "Allows MEFE access for this user"
@kaihendry can you create the routine to do this please?

# Change the way the MEFE authenticates users:
use the BZ user API key mechanism to authenticate users.
@nbiton, once Kai has created the routine we'll have to implement this in the MEFE.

# Disabling users:
Additional benefit is that we will also be able to easily disable user access to the BZ back end if needed:
We will just need to update the field `revoked` in the table `user_api_keys` to the value '1' for the record where the fields `user_id` and `api_key` are matching the MEFE user who we want to disable

**Comment by franck-boullier** [comment]
@nbiton the more I think about this one the more I feel that is is a HUGE issue: it silently prevents users to log in to Unee-T and from a user experience, it seems that the application is broken (endless load)

We need to make this a priority IMO...
Any idea for a quick fix until we have a final solution?

**Comment by nbiton** [comment]
The most reliable quick solution I can think of, is to try to do as we suggested yesterday - periodically resetting the time column in the login_cookies table of the BZ DB so the the tokens can't expire

**Comment by franck-boullier** [comment]
For context, background information and future reference: [how the token mechanism was implemented in BZ](https://bugzilla.mozilla.org/show_bug.cgi?id=893195).

**Comment by franck-boullier** [comment]
The documentation about the [Buzilla REST API](http://bugzilla.readthedocs.io/en/latest/api/index.html).

**Comment by kaihendry** [comment]
https://github.com/unee-t/bugzilla-customisation/issues/9 seems related to me.

**Comment by franck-boullier** [comment]
It clearly is yes
