### ISSUE TITLE
Some cases are not displayed - User has a role in A LOT of cases

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#179]
In the MEFE if a user has a role in a LOT of cases, some cases are not displayed in the Home page (list of cases).

This might be due to the fact that BZ has a limit of returning a max of 500 results per search by default.

We need to find a workaround/solution for that.

**Comment by nbiton** [comment]
I can see that the API limit is set to 10k in dev. This is also the number of results returned on manual test requests I made to the API.
It should be the same for the UI, but I not sure how to setup a user with that many related cases (I'm also skeptical the browser could keep up with the UI if it tries to render 10k cases)

**Comment by franck-boullier** [comment]
Solution is to make sure that once a case is closed, the user is not in CC or assigned to this case anymore. This works as this likely to happen to user who are in supervising roles and these organization should have a 'generic triage user' that we can use to park the case:
1- before the case is assigned (triage)
2- after the case is closed.

We need to document this so that users in these configuration have a good understanding of this feature

**Comment by franck-boullier** [comment]
not a bug
