### ISSUE TITLE
No date information

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#18]
Messages are displayed with time information but no information about the date of the comment

**Comment by franck-boullier** [comment]
This works as intended in PR 28

**Comment by franck-boullier** [comment]
@nbiton, this does NOT work as intended in PR 28: the year is missing in the date.

**Comment by nbiton** [comment]
I set it up to only show the year if it's more than 1 year ago

**Comment by franck-boullier** [comment]
There is a bug then: the comments have incorrect dates in the MEFE.
See comment date in the BZFE for case number 12345
![image](https://user-images.githubusercontent.com/31331637/33361320-89054a7e-d512-11e7-9a82-37a2f2fe1d3c.png)

**Comment by nbiton** [comment]
You're right, the year diff check was not working properly

**Comment by franck-boullier** [comment]
@nbiton, the latest version of the PR 28 uses a date format xx/yy/zz this is confusing as American will read this as mm/dd/yy and the rest of the world will read this as dd/mm/yy
Can we use a more universal format like 'monthname, dd yyyy'?

**Comment by nbiton** [comment]
Sure. I changed it

**Comment by franck-boullier** [comment]
Dates now work as intended in the PR 28
