### ISSUE TITLE
Update the design of the "More info" button

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#182]
![moreinfo-row-highlighted](https://user-images.githubusercontent.com/765871/38119739-8a8ec1a2-33f6-11e8-9459-7846d128413f.png)

It's not clear to me that **More Info** is a button, especially when previous two columns don't act as buttons? 

Perhaps selections should be disabled on this row. No need to copy and paste CONFIRMED & More info right?

Btw when More info is open I find the horizontal rules a bit jarring against the underline of a text input. I prefer the grey spacing.

**Comment by michkwt** [comment]
![m - case detail - case first create with role copy 2](https://user-images.githubusercontent.com/38183796/38480702-92d7c3da-3bf9-11e8-85cd-a7aa5886bc2d.png)

The **More Info** might be unclear as a button due to the fixed 3 columns. So we've removed the fixed columns and added color to More Info button so that it highlights the button and makes it stand out from the case information. It is also for consistency as CTA buttons are colored.

**Comment by franck-boullier** [comment]
this works in PR #222

**Comment by kaihendry** [comment]
Would have been nice to get an explanation how it was fixed or at least a screenshot for completeness.

**Comment by nbiton** [comment]
It looked just like the design :laughing:

**Comment by nbiton** [comment]
![screenshot from 2018-05-08 12-12-16](https://user-images.githubusercontent.com/2662819/39737674-1b58c468-52b9-11e8-844d-5ca777afb380.png)

**Comment by kaihendry** [comment]
Silly comments:
* Why not more like WhatsApp paradigm? I.e. click the top bar get more info
* Case 61982 info should be expressed in the URL, not inline imo
* Priority: P2 means absolutely **nothing** to me. At worse, noise.

**Comment by franck-boullier** [comment]
"Priority: P2 means absolutely nothing to me. At worse, noise." agreed, we have an issue somewhere to replace this with criticity instead and move priority in the more info part

**Comment by nbiton** [comment]
* "Case 61982 info should be expressed in the URL, not inline imo"
In app mode the URL wouldn't show up, which would make it very hard for the typical user to understand what the current case number is, if we remove it.
* "Priority: P2 means absolutely nothing to me. At worse, noise."
It used to be the status just before I made my changes. I adjusted it to fit the current designs

**Comment by kaihendry** [comment]
What's App mode? I thought our clients will always show a URL or have some share URL hyperlink at the very least.

/me prays we don't break the Web paradigm

**Comment by franck-boullier** [comment]
@nbiton 

> "Priority: P2 means absolutely nothing to me. At worse, noise."
> It used to be the status just before I made my changes. I adjusted it to fit the current designs

Can we use 'criticity' instead of 'Priority' there?

**Comment by nbiton** [comment]
"severity"?

**Comment by nbiton** [comment]
@kaihendry I guess something like this will be used
https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android

**Comment by franck-boullier** [comment]
As in current design:
![image](https://user-images.githubusercontent.com/31331637/39851624-817b91a2-544a-11e8-807a-22ec33a0a4f4.png)
'Priority' in the UI is the BZ field 'bug_severity' and NOT the BZ field 'priority': I know: confusing: we probably need to use consistent naming there...

**Comment by nbiton** [comment]
> 'Priority' in the UI is the BZ field 'bug_severity' and NOT the BZ field 'priority': I know: confusing: we probably need to use consistent naming there...

Actually, we currently map "bug_severity" to "Severity" (as seen on case creation) and "priority" to "Priority". This mapping applies to anywhere these fields are involved

**Comment by franck-boullier** [comment]
> Actually, we currently map "bug_severity" to "Severity" (as seen on case creation) and "priority" to "Priority". This mapping applies to anywhere these fields are involved

So this mean that Invision mockup uses the incorrect wording there: it should be either:
- Severity: High (preferred)
or
- Priority: P1 (confusing)
It cannot be Priority: High
