### ISSUE TITLE
Status could be more intuitive

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#183]
We have:
* CONFIRMED
* STAND BY
* RESOLVED
* IN_PROGRESS

Could that have descriptions as to what they mean and perhaps "Friendly names"?

**Comment by franck-boullier** [comment]
@kaihendry any recommendation for an alternative to these statuses?

**Comment by kaihendry** [comment]
Something similar to Github's?

* https://octicons.github.com/icon/issue-opened/
* https://octicons.github.com/icon/issue-reopened/
* https://octicons.github.com/icon/issue-closed/

**Comment by franck-boullier** [comment]
Status are currently OK with Pilot users.
Closing this
