### ISSUE TITLE
We need to enable notification when a case is updated

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#185]
On the MEFE, when a case is updated, we need to signal the MEFE user about this.
We should have a notification mechanism enabled to make sure user do not have to check Unee-T on a random/regular basis but only if/when a case they are part of is updated.

**Comment by kaihendry** [comment]
Unlike #186 the idea here is to use [App push notifications](https://developers.google.com/web/fundamentals/push-notifications/) or perhaps even SMS?

**Comment by franck-boullier** [comment]
Idea is clearly to use App push notifications, yes.

SMS should be a different GH issue IMO as this will have different implications similar to what we have to do for email (namely an unsubscribe mechanism and a way to make sure that these will not be flagged as spam too)

**Comment by kaihendry** [comment]
So we need:

- [ ] Trigger for when a case is updated, implemented as a lambda2sns trigger on the longdescs table in the schema
- [ ] The frontend to subscribe to the relevant endpoint and notify the user somehow https://github.com/unee-t/frontend/issues/244

**Comment by franck-boullier** [comment]
>  Trigger for when a case is updated, 

This exists already

> implemented as a lambda2sns trigger 

We understand how to do that and @kaihendry and I need to have that 1/2 conversation so I have the detailed step by step instruction in our context.

> on the longdescs table in the schema

@kaihendry  Nope! This needs to happen on the table 'ut_notification_messages_cases' and NOT the table 'longdescs '

**Comment by franck-boullier** [comment]
This has been implemented in the June 25th release
