### ISSUE TITLE
Email notification until invitation is accepted

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#186]
If a user has no access to Unee-T (he/she has not accepted the invitation yet) the user will not be notified of any changes in the case.

The MEFE needs to send an email notification to the invited user each time a case is updated.
The email notification should always include a magic link to the case.

Once the invitation is accepted, we can stop sending email notification: the user should be able to log into Unee-T and see the case there

**Comment by franck-boullier** [comment]
Text of the email can be generic: like 
"case [case title] has been updated, please click on [insert the magic link] to see the latest information about this case."

**Comment by kaihendry** [comment]
Wonder how Bugzilla handles this? Surely there must be some opt in or at least an opt out ?

**Comment by franck-boullier** [comment]
For MEFE user's only (most users) the standard BZ email notification when a case is updated is disabled: that way they never receive confusing updates from the BZFE

**Comment by franck-boullier** [comment]
in other words: in BZ there IS an opt out functionality and it is activated for all the users that have no business in the BZFE

**Comment by kaihendry** [comment]
What if the case is updated several times? 3 images are added, 2 text. Would that be 5 emails?

**Comment by franck-boullier** [comment]
"What if the case is updated several times? 3 images are added, 2 text. Would that be 5 emails?"
Yes
Until the user accept the invitation this is the only simple and easy way to send him the magic link at relevant times

After the user accepts the invitation the MEFE notification should be able to take over what emails are doing...
There might be some fringes scenario where the user disable notification from mobile but we can handle/explain that using the 'chatbot' concept 

I really like that Chabot idea BTW: this is a great way to gradually expose users to Unee-T functionalities when it's relevant!

**Comment by nbiton** [comment]
I think that without a throttling mechanism, the feature could become unusable. Currently, case field will be updated too often, which can result in a ridiculous amout of emails each time

**Comment by franck-boullier** [comment]
"I think that without a throttling mechanism, the feature could become unusable. Currently, case field will be updated too often, which can result in a ridiculous amout of emails each time"
This makes total sense: we could limit email to 1 per day/user/unit for instance.

**Comment by kaihendry** [comment]
Shouldn't the email at least have an unsubscribe (to notifications) link?

Say if someone isn't willing to sign up for whatever reason?

**Comment by franck-boullier** [comment]
@kaihendry good point and yes it should

**Comment by franck-boullier** [comment]
so as a summary the specs are:
* email notification sent from the MEFE to the MEFE user
* when a change is made to a case
* max 1 email per day
* email notification should include an 'unsubscribe' option

**Comment by kaihendry** [comment]
@nbiton is there some sort of event stream for "a change" I can hook into to implement this?

Otherwise I'll study case messages.

**Comment by nbiton** [comment]
You can add a hook in the method in cases.js . There's no other way to be notified of the change

**Comment by kaihendry** [comment]
I couldn't figure this out last Friday afternoon.

**Comment by kaihendry** [comment]
I see this issue as the beginning of the non-trivial **ground work** for some sort of PubSub message bus, so that various notifications can be published. I.e.
* Send a notification to someone who's not on the system yet, that the case they were invited to participate in, has updated (this issue #186)
* [When a message in the case was seen](https://github.com/unee-t/frontend/issues/191)
* [When a case was updated](https://github.com/unee-t/frontend/issues/185)

I'm not confident with Meteor enough to implement it. I'm not sure for e.g. the right way to implement or leverage an [event bus in Meteor](https://forums.meteor.com/t/event-bus-for-a-meteor-application/33497). Do `Meteor.call('event')` broadcast across the entire application?? Since recall in our deployment we have two instances of Meteor runtime, connected by a shared Mongo.

**Comment by franck-boullier** [comment]
"I'm not sure for e.g. the right way to implement or leverage an event bus in Meteor"
I think it's not good to try to use Meteor to handle the notification.
The MEFE is only an interface which connects and interacts with the BZFE.

IMO we should get these events as close as possible to were the information is stored (the BZ db today)

**Comment by kaihendry** [comment]
After chatting with Franck over Slack, he seems keen to do this from the Bugzilla side instead. E.g. `Paws->service('SNS')->Publish(Message => $msg, TopicArn => '...');` So the Frontend wouldn't publish the events, but the [our backend](https://github.com/unee-t/bugzilla-customisation/issues/59) would.

It's probably best if Bugzilla does this since it's the "source of truth" here, please track this work over here: https://github.com/unee-t/bugzilla-customisation/issues/59

Tbh personally I would prefer to solve this particular issue (email notification) via a Lambda function with a SNS trigger, but I'll leave this open for @nbiton to make the call.

**Comment by franck-boullier** [comment]
Well TBH I would very much prefer that we go Serverless and use a lambda function to query the RDS database and check if certain tables are changed....

My understanding of the convo I had with @Kaihendry was that this was not possible...

That's why I'm ready to settle for the next best thing which is the BZ solution...

**Comment by franck-boullier** [comment]
Also it is probably best to record this conversation in issue #13 which is exactly about that whereas this issue is limited to email notification

**Comment by kaihendry** [comment]
Rolling up the lambda messages does seem to require a bit of work! https://stackoverflow.com/questions/49807958/aws-sns-message-digest/49811628#49811628

**Comment by kaihendry** [comment]
I guess so? Some sort of [staging area is needed by the sounds of things](https://stackoverflow.com/questions/49807958/aws-sns-message-digest/49811628#49811628). 

Btw the demo env is running Aurora already if you want to fiddle with it.

**Comment by franck-boullier** [comment]
"demo env is running Aurora already"
sweet!
how complex will it be to do a migration to Aurora in the DEV/Staging and see if this breaks anything?

**Comment by franck-boullier** [comment]
"Some sort of staging area is needed by the sounds of things."
Yep! 
Saw that and I have this in mind but the SQL side of things seems to work really nicely so far: I'm able to create the messages when an update is done and also add routing information too so this looks quite promising :grin:

**Comment by franck-boullier** [comment]
OK tested and this works as intended (so far).
We can have a table in the BZ DB (Aurora) which is updated each time something change in a case:
- Case is created
- Case is modified
- A new comment is added.

Table looks like this
![image](https://user-images.githubusercontent.com/31331637/38805110-401cfd3c-41a7-11e8-9563-bda5d02c3bb1.png)

@kaihendry I now need to have the Lambda function’s ARN to finish implementing the SQL steps described there https://aws.amazon.com/blogs/database/capturing-data-changes-in-amazon-aurora-using-aws-lambda/

Then we need to have a routing logic somewhere but I'm guessing we can implement and manage that outside of BZ

@nbiton any comments?

**Comment by franck-boullier** [comment]
Housekeping
This is too vague and covered in several smaller other issues, many have already been implemented.

As of today, with the invitation mechanism in place, the email notification to invited users and the capability to subscribe/unsubscribe to email notifications, we are covering most of the intended user cases.
