### ISSUE TITLE
'magic link' in the invitation is not working

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#187]
# The test:
* Create a case in an existing unit
* Invite a user in a role which has no assigned user yet
* process the invitation as per normal

# Expected result:
* Invited user received an email with the magic link to access the new case. PASSED
* Since the user has already been invited before and already has a MEFE account which has been activated, the expected behavior is that user is:
  * option 1: logged in automatically - FAILED
  * option 2: logged in after entering username and password - FAILED
  * option 3: logged in after password is reset - FAILED 

# Actual result:
When the invited user clicks (I actually copy/pasted the link into an incognito window from FF) on the magic link in the invitation email, the magic link is not working:
See the screenshot:
![image](https://user-images.githubusercontent.com/31331637/38135618-bd64d1a2-344b-11e8-9f03-1d785dfeafa8.png)

# More information about the issue:
If I log out from the MEFE and log in with the user credentials all works as intended and the case is visible as expected.
@nbiton, any idea what might go wrong?

**Comment by nbiton** [comment]
Were you already logged in with the same user that was invited or a different one?
If it was the same, I couldn't find a way to reproduce the issue yet. It worked as expected.
For a different user, it would currently throw an error. Do you prefer it would log out the existing user session and log in as the new user?
If it is the second case, I guess the issue is pretty minor.

**Comment by franck-boullier** [comment]
"Do you prefer it would log out the existing user session and log in as the new user?"
@nbiton I think this would be appropriate yes

**Comment by franck-boullier** [comment]
The issue seems to be more complex than initally understood and can be replicated easily in the DEV environment:
* log in as user 1
* create a case
* invite user 2 as assignee for a case (choose a role that has not been assigned yet)
* log out of the MEFE
* process invitation
* go to the invitee mailbox
* click on the magic link in the invitation email

Result: unable to access the case as the invitee.

* Close browser
* reopen browser and go to the MEFE
* login as the invited user

Result: the case is visible and accessible for the invitee

**Comment by nbiton** [comment]
I can't recreate the above scenario as described (functionality works as expected), but I can recreate it if I omit the "log out of the MEFE" step.
Whether or not you can still recreate it as described above, I do have a fix for the adjusted scenario. I'll push it as a PR.
