### ISSUE TITLE
Invitation eMail looks like spam and is difficult to understand

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#188]
We received feedback from invited users that the email we sent as part of the invitation process is confusing and difficult to understand.
One invited user even called the invitor to make sure that the email was not spam/clickbait.

We need to improve the design of the invitation email to avoid this.

@kaihendry where can I find the click through rate for the invitation email?

**Comment by franck-boullier** [comment]
The text of the email is 

---
      to: user.emails[0].address,
      from: process.env.FROM_EMAIL,
      replyTo: `${invitorUsername} <${invitorEmailAddress}>`,
      subject: `New Case: ${caseTitle}`,
      text: `Hi there,

${invitorUsername || invitorEmailAddress}, the ${roleStr} for the Unit ${unitName} (${unitDesc}) has invited you to collaborate on the case ${caseTitle} as the ${inviteeRole} for that unit.

Please click the link below to get more information about the case and reply to ${invitorUsername || 'him'}:
${url.resolve(process.env.ROOT_URL, `/invitation?code=${accessToken}`)}

Kind regards,
---

This can be changed in [this file](https://github.com/unee-t/frontend/blob/master/imports/util/email-invite.js#L21)

**Comment by kiatlim** [comment]
@franck-boullier we actually had something like this designed previously: 

![image](https://user-images.githubusercontent.com/641679/38353052-d8452990-38e7-11e8-8798-919da5633562.png)

Plus I tried to send an invite to michelle but she's not getting it, how often does the email gets sends out?

**Comment by kiatlim** [comment]
**Current email received:**
![image](https://user-images.githubusercontent.com/641679/38353294-9a605b58-38e8-11e8-82b3-41d7a006847d.png)

**Comment by franck-boullier** [comment]
@kiatlim "Plus I tried to send an invite to michelle but she's not getting it, how often does the email gets sends out"
confused as it seems from your previous message that she received it...

**Comment by franck-boullier** [comment]
invitation are not immediate but are typically processed within a few hours... :-)

**Comment by kiatlim** [comment]
haha i see, yeah she just got it after awhile.

**Comment by franck-boullier** [comment]
@kiatlim we probably need to tone down the disclaimer about Unee-T too (we do not have over 1 million user... yet) :-))

**Comment by franck-boullier** [comment]
@kaihendry, the design requires us to have an html version of the email I'm afraid, do you think you'll be able to spend some time on this tomorrow (if not possible I can probably have a go at it...)?

**Comment by kiatlim** [comment]
Absolutely, the what is Unee-T text @franck-boullier needs to provide a description :)  
Added a version to make it more credible with logo. But if we're just sending out in text mail then not possible.

![image](https://user-images.githubusercontent.com/641679/38354089-e94b5cfc-38ea-11e8-91cc-768e64c3f334.png)

**Email image:** ![Uploading unee-t_logo_email.png…]()

**Comment by franck-boullier** [comment]
@kiatlim I like that we add the logo there: much better IMO

I suggest that we replace the paragraph "What is Unee-T (...)" with the following tagline:
"Managing and sharing 'To Do's for your properties has never been easier"

As for the unit, we might need to have 2 information for the avoidance of doubt from the invitee:
1- The unit name (which was determined by the creator of the unit)
2- The unit Address (so that anyone else knows what we are talking about)

I like that we have a link 'Find out more at unee-t.com' please note that there should be no www in the url though.

We probably also need an option so that the user can switch from html version of the email to plain text (this seems to be common practice)

What about the usual message which says "If this link doesn't work copy and paste this link directly in your browser"  ?

**Comment by kaihendry** [comment]
Be good to have the full HTML template here. Otherwise I need to spend time copy writing instead of programming. For the record the template is here: https://github.com/unee-t/frontend/blob/master/imports/util/email-invite.js#L21

Click through rate could be determined by the conversions aka "/api/converted-invitations" divided by number of invites sent aka "api/invitations" as documented on Postman.

**Comment by kaihendry** [comment]
https://s.natalian.org/2018-04-06/send-invite.mp4 documents how I develop the invitation email btw.

**Comment by franck-boullier** [comment]
@kaihendry there seem to be a problem...

# The Test 
done after the PR #188 has been deployed in the DEV/Staging environment
Process a pending invitation
MEFE Invitation ref: YQHywsEyfdDGcBj8o

#Expected result:
New Invitation email (html version) is received in the mailbox of the invited user.

#Actual result:
After waiting for 30mn, the invitation email is still not in the inbox of the invited user.

**Comment by franck-boullier** [comment]
One more test done on MEFE invitation #hKLR2mJNytAGrpjrC
Same result: the email to the invitee has not been received.

**Comment by kaihendry** [comment]
Be a lot easier to see what went wrong if you could dig out the logs from https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=meteor

**Comment by franck-boullier** [comment]
@kaihendry not sure I understand your comment:

> Be a lot easier to see what went wrong if you could dig out the logs 
Do you need me to do anything?
Do you know how to fix this issue?

**Comment by franck-boullier** [comment]
@kaihendry forget my last comment, I just saw your PR and merged it... 😊

**Comment by franck-boullier** [comment]
Test done in the DEV on MEFE invitaion ref: 
* Invitation email is received: PASSED
* email is in html format: PASSED
* Make sure the invited user is logged off the MEFE PASSED
* Magic link is working and sending me to the case: FAILED
![image](https://user-images.githubusercontent.com/31331637/38531757-14fb17ea-3ca4-11e8-93cf-dea182b33313.png)

@nbiton I am wondering if the diagnosis we did for issue #187 is correct...

**Comment by kaihendry** [comment]
I haven't touched the magic link code, so shouldn't this be a separate issue and this one closed?

**Comment by franck-boullier** [comment]
@kaihendry good point!
