### ISSUE TITLE
Review and rate (simple/moderate/complex) all open issues - 'Bounty based fixing'

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#192]
We are implementing the 'Bounty' model to speed up bug fixing and compensate outside contributors easily.

This requires us to qualify each GH issue. 
For all the issues we want to highlight as eligible to 'bounty based fixing', we need to add one of the following Labels:
* Simple: this issue should be fixed within 0.5 day's worth of dev.
* Moderate: this issue should be fixed withing 1 day's worth of dev.
* Complex: this issue should be fixed withing 2 days' worth of dev.

If an issue is too complex (it can't be tackled in 2 days or less) then we need to break this issue down into smaller issues and label each sub-issue as either simple, moderate or complex.

These labels (simple, moderate or complex) will allow the freelancers we source via Upwork to know much they will get paid if they fix the issue.

We will considered an issue fixed once the code in the relevant PR created by the contributor/freelancer is merged into the Master (obviously after careful QA review and tests).

@nbiton and @sebdeckers can you please have a look at the existing open issues and label these so we can get this started :-)

**Comment by franck-boullier** [comment]
The Upwork job posts:
* [Simple](https://www.upwork.com/ab/applicants/982053204448870400/job-details)
* [Moderate](https://www.upwork.com/ab/applicants/982053687720771584/job-details)
* [Complex](https://www.upwork.com/ab/applicants/982054301943840768/job-details)

**Comment by kaihendry** [comment]
The above links don't work unless logged in, is that right? Be nicer if it was a public page.

**Comment by franck-boullier** [comment]
Housekeeping - Closing this as this is not needed anymore: Upwork jobs have lapsed
