### ISSUE TITLE
Unable to create an account on Locahost

### ISSUE THREAD

**Issue by mariorodriguespt** [unee-t/frontend#195]
I tried to created an account: Nothing changed in the Sign Up page and got this error log on the server:

```
I20180407-05:22:41.729(1)? creating user for mario@gmail.com
W20180407-05:22:41.738(1)? (STDERR) { [Error: failed [404] Cannot POST /rest/user ]
W20180407-05:22:41.739(1)? (STDERR)   response: 
W20180407-05:22:41.740(1)? (STDERR)    { statusCode: 404,
W20180407-05:22:41.741(1)? (STDERR)      content: 'Cannot POST /rest/user\n',
W20180407-05:22:41.745(1)? (STDERR)      headers: 
W20180407-05:22:41.746(1)? (STDERR)       { 'x-content-type-options': 'nosniff',
W20180407-05:22:41.747(1)? (STDERR)         'content-type': 'text/html; charset=utf-8',
W20180407-05:22:41.749(1)? (STDERR)         'content-length': '23',
W20180407-05:22:41.752(1)? (STDERR)         vary: 'Accept-Encoding',
W20180407-05:22:41.754(1)? (STDERR)         date: 'Sat, 07 Apr 2018 04:22:41 GMT',
W20180407-05:22:41.755(1)? (STDERR)         connection: 'close' },
W20180407-05:22:41.756(1)? (STDERR)      data: null } }
```

**Comment by kaihendry** [comment]
For the frontend to function need to run the Bugzilla backend: https://github.com/unee-t/bugzilla-customisation

If you run `npm run start`, you need to comment out the meteor and mongo service in https://github.com/unee-t/bugzilla-customisation/blob/master/docker-compose.yml

**Comment by franck-boullier** [comment]
Good practice is to have the issue creator close the issue if he's happy with the solution provided
@mariorodriguespt can you please close if all is in order

@kaihendry maybe we need to update the readme file on the repo to reflect this or make it more obvious

**Comment by mariorodriguespt** [comment]
I'll figure this out and will update the README.md

**Comment by kaihendry** [comment]
https://gist.github.com/kaihendry/5de385d271c6fafde9c9fd317e03ca0f is a guide to how I do it

**Comment by kaihendry** [comment]
Trying to do some bug housekeeping here. Please re-open if it's still an issue.
