### ISSUE TITLE
Can't view case details

### ISSUE THREAD

**Issue by ahmadmzak** [unee-t/frontend#196]
After adding some cases, nothing happens when I click on them. The loading animation keeps running and i get the following errors in the console:

`modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:12895 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:12895)
    at Object.dangerouslyReplaceNodeWithMarkup (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:13362)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:12715)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18333)
    at ReactCompositeComponentWrapper._updateRenderedComponent (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18323)
    at ReactCompositeComponentWrapper._performComponentUpdate (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273)
    at ReactCompositeComponentWrapper.updateComponent (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194)
    at ReactCompositeComponentWrapper.receiveComponent (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096)
    at Object.receiveComponent (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647)
    at ReactCompositeComponentWrapper._updateRenderedComponent (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303)
replaceChildWithTree @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:12895
dangerouslyReplaceNodeWithMarkup @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:13362
dangerouslyReplaceNodeWithMarkup @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:12715
_replaceNodeWithMarkup @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18333
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18323
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:17359
_reconcilerUpdateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16893
_updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16997
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16984
_updateDOMChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14361
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14179
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14141
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:17359
_reconcilerUpdateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16893
_updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16997
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16984
_updateDOMChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14361
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14179
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14141
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:17359
_reconcilerUpdateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16893
_updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16997
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16984
_updateDOMChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14361
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14179
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14141
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:17359
_reconcilerUpdateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16893
_updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16997
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16984
_updateDOMChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14361
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14179
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14141
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:17359
_reconcilerUpdateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16893
_updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16997
updateChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:16984
_updateDOMChildren @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14361
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14179
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:14141
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18096
receiveComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10647
_updateRenderedComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18303
_performComponentUpdate @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18273
updateComponent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18194
performUpdateIfNecessary @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18110
performUpdateIfNecessary @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10679
runBatchedUpdates @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10254
perform @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:11533
perform @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:11533
perform @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10193
flushBatchedUpdates @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10276
closeAll @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:11599
perform @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:11546
batchedUpdates @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:20539
batchedUpdates @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:10201
dispatchEvent @ modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:20701
meteor.js?hash=27829e936d09beae3149ecfbf3332c42ccb1596f:930 Exception from Tracker recompute function:
meteor.js?hash=27829e936d09beae3149ecfbf3332c42ccb1596f:930 TypeError: Cannot read property 'replace' of undefined
    at attachmentTextMatcher (matchers.js:4)
    at CaseMessages.renderSingleMessage (case-messages.jsx:175)
    at case-messages.jsx:157
    at Array.reduce (<anonymous>)
    at CaseMessages.renderMessages (case-messages.jsx:145)
    at CaseMessages.render (case-messages.jsx:107)
    at modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18345
    at measureLifeCyclePerf (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:17625)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18344)
    at ReactCompositeComponentWrapper._renderValidatedComponent (modules.js?hash=dd30bc8bf4a12d287befb441500aeffc0f5d49ef:18371)`

**Comment by kaihendry** [comment]
This is probably because bugzilla on localhost:8081 is not properly running for the meteor application to front? The frontend will endlessly retry if it can't find it, which is a bug in itself.

https://github.com/unee-t/frontend/issues/195#issuecomment-379431893

**Comment by franck-boullier** [comment]
@ahmadmzak 
1- have you installed the BZ backend: https://github.com/unee-t/bugzilla-customisation already?
2- Which user are you using to log in?
3- can you include an URL of the page that produces the error?

@kaihendry can this be an issue with the API key for the BZ admin user?

**Comment by ahmadmzak** [comment]
@franck-boullier 
1. Yes, I have that running
2. User is administrator@example.com, password is password
3. URL is localhost:3000/case/* where * is 1,2, or 3 (i have 3 cases)

**Comment by kaihendry** [comment]
https://gist.github.com/kaihendry/5de385d271c6fafde9c9fd317e03ca0f is a quick guide to what I do

**Comment by ahmadmzak** [comment]
@kaihendry I commented those lines and did make {down, clean, up} and now I'm getting a connection refused error for MySQL:

Can't connect to MySQL server on 'db' (111)

**Comment by kaihendry** [comment]
Closing, bug I believe is a local misconfiguration or bad state.
