### ISSUE TITLE
Confusing design for inviting users

### ISSUE THREAD

**Issue by michkwt** [unee-t/frontend#198]
<img width="404" alt="screen shot 2018-04-09 at 2 38 41 pm" src="https://user-images.githubusercontent.com/38183796/38484688-fd2ffb2a-3c09-11e8-8c9d-c436a3e6905e.png">
<img width="401" alt="screen shot 2018-04-09 at 2 38 21 pm" src="https://user-images.githubusercontent.com/38183796/38484690-fd7b33ec-3c09-11e8-86d0-186aeed6cd3d.png">

New Invite flow:
<img width="913" alt="screen shot 2018-04-09 at 2 51 16 pm" src="https://user-images.githubusercontent.com/38183796/38485005-f8309b42-3c0a-11e8-9634-4f9ccffbe78a.png">

**Comment by franck-boullier** [comment]
Thanks @michkwt I like the new flow!

**Comment by nbiton** [comment]
The issue with this new design is that it is unclear how the previously invited users should appear. If they appear the same with users who are about to be invited- three new issues will impact the user's experience:
1. The user will have to mentally keep track of which users would be added to the case before submitting.
2. The user will not be able to distinguish users about to be removed from the case from users who are not a part of the case.
3. It is unclear how "pending" users are to be shown, as they can't be removed from the case until the invitation is finalized.

In addition, removing the search could make the task of finding users in a unit that has many role holders more cumbersome.

**Comment by franck-boullier** [comment]
@nbiton "removing the search could make the task of finding users in a unit that has many role holders more cumbersome."
The number of scenario when the list of users in given role for a given unit is more than 5 users long are limited. There might be scenarios when we have several contractors and several occupants but these are fringes scenarios at this point. I understand the risk bt I think this is worth the tradeoff as the search box is adding confusion to the invitation interface (I for one always think that this box is there to 'search for a user who has not been invited to this unit yet' even after using it on a regular basis!)
better to remove it for know.
If and when we have long lists of users in roles for a unit, then we can always revisit that...

**Comment by franck-boullier** [comment]
@kiatlim and @michkwt 
Any comments/suggestions on @nbiton 's point?
---

1. The user will have to mentally keep track of which users would be added to the case before submitting.
2. The user will not be able to distinguish users about to be removed from the case from users who are not a part of the case.
3. It is unclear how "pending" users are to be shown, as they can't be removed from the case until the invitation is finalized.
---

**Comment by michkwt** [comment]
@nbiton  @franck-boullier comments with screenshots coming in shortly but the gist is:
1. The link to open the overlay for inviting user should strictly be used to invite users, not remove users as well. The remove users should ideally be a "x" on the right of their name and a confirmation "Are you sure you want to remove Marina from the case?" - @nbiton what do you think, possible?

Downside of this is removal of user from case is only done 1 by 1.  

2. The overlay for inviting users should only show users who are in the unit but not part of this case yet so they don't need to keep track of which users are already added to the case.

**Comment by michkwt** [comment]
<img width="564" alt="screen shot 2018-04-23 at 6 39 33 pm" src="https://user-images.githubusercontent.com/38183796/39121922-c087d720-4725-11e8-8253-75234b2cb330.png">

**Comment by franck-boullier** [comment]
thanks @michkwt that's clear for me!
@nbiton do you see any issue with this approach?

**Comment by nbiton** [comment]
No issues with this approach. Thanks, that's much clearer :)

**Comment by nbiton** [comment]
Resolved in #218
