### ISSUE TITLE
Invite new assignee flow

### ISSUE THREAD

**Issue by michkwt** [unee-t/frontend#199]
<img width="882" alt="screen shot 2018-04-09 at 4 15 23 pm" src="https://user-images.githubusercontent.com/38183796/38487326-5117f348-3c12-11e8-898e-4d820e8f7bbc.png">

**Comment by franck-boullier** [comment]
I suggest that we remove the search box altogether: there is no need for a search functionality since hte list should be relatively small in 99% of the cases.

**Comment by franck-boullier** [comment]
and we also probably need 2 buttons there:
1- Assign the case
2- Invite another person
(wording should probably be fine tuned though...)

**Comment by michkwt** [comment]
<img width="993" alt="screen shot 2018-04-09 at 5 55 11 pm" src="https://user-images.githubusercontent.com/38183796/38491722-4b679e64-3c1f-11e8-9e38-4d6741d6d792.png">

**Comment by kiatlim** [comment]
@franck-boullier ignore the 3rd image. so from the 2nd image, bottom link to invite new assignee will go to the 4th image. 

Pressing Assign case will go back to the case more-info screen to show the assignee changed.

**Comment by franck-boullier** [comment]
OK thanks for the clarification!

**Comment by nbiton** [comment]
@kiatlim @michkwt In the 2nd image, do we show who the previous assignee in some way?
Also, I understand from this the selection box drop down UI is to be removed entirely?

**Comment by nbiton** [comment]
The added details make sense, thanks

**Comment by nbiton** [comment]
Resolved in #218
