### ISSUE TITLE
meteor build fails on a css minify step

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#2]
I posted here about it https://forums.meteor.com/t/traverse-node-type-is-not-a-function/38842

I'm on shaky ground here. Perhaps a bug should be filed at meteor? Though we would need a reduced example as requested by https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor

**Comment by kaihendry** [comment]
After doing a bisect, http://tachyons.io/ seems to make the meteor build process choke!

```
~/lmb/unee-t-fe$ git bisect good
5e8ad5776ded4e0529e4710dce8b6f7e0ecd8517 is the first bad commit
commit 5e8ad5776ded4e0529e4710dce8b6f7e0ecd8517
Author: nbiton <naor.biton@gmail.com>
Date:   Fri Jul 21 17:12:20 2017 +0800

    chore: added tachyons css to the

:040000 040000 a3c2d6d20ed462d6689a48352ca9eef78a05c410 758a4f33bd67f43a0126a2343d53ae0e24e43b7e M     client
:040000 040000 40b5673a1b43a49c9bfc78bceaa484fab75649ca 369abc3e5369b68ddd90204d01c9b691819ed591 M     imports
:100644 100644 ca530adc5d7fecd90d38159939eca197d50d39c2 bd8d6ea0be34963ff65d348ae57854eb12b20fb8 M     package.json
```

**Comment by kaihendry** [comment]
This issue makes it a pain to deploy. Asking for a workaround: https://github.com/CyCoreSystems/docker-meteor/issues/53

**Comment by sebdeckers** [comment]
Does the proposed debug flag help?

**Comment by kaihendry** [comment]
It does, it's workaround, but I don't want to deploy debug builds ideally.
