### ISSUE TITLE
display name - not email address

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#20]
email addresses are too long.
Display public user name instead of email address

**Comment by nbiton** [comment]
Not sure if it's possible. The BZ API provides us only with the email address as the creator of each message. I can try to match it to existing MEFE users and pull their names which shouldn't create too much performance overhead, but the comments from BZFE-only users might have to remain as email addresses

**Comment by franck-boullier** [comment]
the BZFE records 2 information:
- login (a valid email address)
- Real Name (or 'full_name' in the API to create new users (https://bugzilla.readthedocs.io/en/5.0/api/core/v1/user.html#create-user)

We should use this Real Name/full_name as the default display for the user unless it's empty.

We can add a message on the user creation page to say that
'If the username field is empty, we will use your email address as your username. Creating a User Name is useful for people who prefer to keep their email address more private.'

**Comment by franck-boullier** [comment]
@Naor: "I can try to match it to existing MEFE users and pull their names".
I think that's probably the best way to do it indeed.
FYI, by default the BZFE displays the username/Real Name/full_name and not the email address next to comments and messages.

**Comment by nbiton** [comment]
http://bugzilla.readthedocs.io/en/latest/api/core/v1/comment.html#get-comments

The "creator" is the login name of the user in BZ. The login name seems to be just the email. Unless we try to match email address to MEFE user and replace it respectively, we can't really use the real name from BZ. The only way to do it for BZ is to make one additional API request for each one of the participants in the conversation, and that is likely to get really bad performance very fast.

**Comment by franck-boullier** [comment]
"Unless we try to match email address to MEFE user and replace it respectively"
This seems to be the right solution and since email addresses are also our likely unique identifier for the BZFE user we should be able to do that replacement the MEFE then.

**Comment by franck-boullier** [comment]
Add the 'Pilot' label based on user feedback: one of the stated reason for NOT using the invitation mechanism is "I don't want user 1 to see the email for user 2: this would be a problem as I want to make sure that user 1 (or user 2) does not 'short circuit' me and talks to user 2 (or user 1) directly".

**Comment by franck-boullier** [comment]
@nbiton user feedback tells me that this issue is what prevents most users to use the invitation mechanism: they do not want to have the email addresses of some of the people involved in the conversation exposed to the other people in the conversation.
Any idea how difficult this would be to correct this and use the MEFE username instead?

**Comment by nbiton** [comment]
It'll be easy to switch to the username just for display purposes, but much
more complex to prevent the email addresses from ever reachinf client side
code.

**Comment by franck-boullier** [comment]
"It'll be easy to switch to the username just for display purposes, but much more complex to prevent the email addresses from ever reachinf client side code."

Understood
Let's switch to the username just for display purposes for now as this would be a temp solution that is acceptable in the pilot/MVP phase

**Comment by kaihendry** [comment]
Anyone have a screen shot of where this is a problem, so I know exactly what to fix?

**Comment by nbiton** [comment]
@kaihendry There are two things that need to be done to show the user name instead of the email address. 
First, you have to publish the user objects (with sensitive data reduced) from the server code so it will be accessible on the client. This should be done almost exactly like on the 'byId' publication on cases.js, with the 'withUsers' utility function. This would be done on the comments publication in a similar way
Second, you need  to match each comment's 'creator' field to a user in client code. See how this is done for the owner, assignee and subscribers of a case in 'case.jsx' around line 206.

**Comment by kaihendry** [comment]
Ok, seems a fair bit harder than I expected. Will try though.
