### ISSUE TITLE
"Create New Case" hangs for certain demo users

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#202]
**Summary of issue**

Currently for the following 3 accounts, the UI randomly hangs after logging in on the loading page, and clicking on "Create New Case". Note that due to its semi random nature, you should try to repeat at least 3 times the process.

**Affected user : Updated 22nd May 2018**

Account Name  | Dev env | Demo env
-- | -- | --
Sabrina | ok | Hangs at create case
Marina | ok | Hangs at create case
Lawrance | ok | Hangs at create case
Celeste | Login hangs at redirect | ok
Regina | Login hangs at redirect | Login hangs at redirect
Marvin | Login hangs at redirect | ok
Anabella | Login hangs at redirect | ok

See animated gif for steps involved
![new-case-bug](https://user-images.githubusercontent.com/17175484/38597049-dbcc6d2c-3d87-11e8-8c78-f0bdc8059319.gif)

**Tested environment**

+ https://demo.case.unee-t.com/
+ https://dev.case.unee-t.com/

**Tested browser**

+ Chrome
+ Firefox
+ IE edge

**Tested resolution**

+ Laptop : 1440 x 900
+ Phone : 480 x 840 (Chrome)

**Test Script**

The specific ui test script is found at : `case/case-management/create-a-new-case-window (buggy-users)`

The steps are provided below for convinence

```.js
/////////////////////////////////////////////////////////////
//
//  test case : open "new case" window multiple
//  times across multiple accounts. 
//
//  This is doneDue to its random occurance nature
//
/////////////////////////////////////////////////////////////

// Include the default config, such as site settings
TEST.run("data-config");

// This function allows the iteration of user objects
// And performs a logout and login for each account
TEST.run("func/auth/forEachAccount");

// ForEachAccount requires the site to be loaded first
I.goTo( DATA.site );

// The specific 3 demo users to test
var BUG_USER = {
	"sabrina@example.com"  : "sabrina",
	"marina@example.com"   : "marina",
	"lawrence@example.com" : "lawrence"
};

// For each email password pair in the demo account list,
// login and execute the inner function
forEachAccount( BUG_USER, function(email, pass) {

	// For each account, lets repeat this 10 times
	for(var i=0; i<3; ++i) {

		// Lets reload the page
		I.goTo( DATA.site );

		// Click on "Create New Case"
		I.click("Create New Case");
		
		// Lets see the "New Case" UI
		I.see("New Case");
		I.see("Assign this case to");
		I.see("Add Case");
		
		// And try again
	}

});
```

**Comment by franck-boullier** [comment]
in which environment are you running these tests? (please include the URL that you use)

**Comment by franck-boullier** [comment]
@PicoCreator can you copy paste the Chrome or FF console output when the UI hangs?
This will help us better understand the issue

**Comment by kaihendry** [comment]
UI-licious are using the dev/staging env.

**Comment by franck-boullier** [comment]
I'm wondering if this might be related to issue #178 :thinking: 
@nbiton do you have any idea?

**Comment by kaihendry** [comment]
We should run the test above and carefully tail the logs...

**Comment by kaihendry** [comment]
Eugene aka @PicoCreator was saying over WhatsApp chat that the tests will run at 2AM, so it should make it easier for us to range the logs for debugging.

**Comment by PicoCreator** [comment]
@franck-boullier : sorry, missed the notification - currently testing against both dev and demo environment. Will indicate that in future bug reports.

**Comment by PicoCreator** [comment]
Doing an update on the accounts facing this issue, cause it has since changed

Account Name  | Dev env | Demo env
-- | -- | --
Sabrina | ok | Hangs at create case
Marina | ok | Hangs at create case
Lawrance | ok | Hangs at create case
Celeste | Login hangs at redirect | ok
Regina | Login hangs at redirect | Login hangs at redirect
Marvin | Login hangs at redirect | ok
Anabella | Login hangs at redirect | ok

**Comment by franck-boullier** [comment]
This should have been fixed when we refactored the user login engine and moved away from token to implement API Keys.

Please Reopen if needed
