### ISSUE TITLE
Speed up and simplify unit selection when creating a case

### ISSUE THREAD

**Issue by michkwt** [unee-t/frontend#204]
Desktop view:
![d1 0 - dashboard - marina unit with no case](https://user-images.githubusercontent.com/38183796/38604593-6b386f18-3da3-11e8-8b6a-3f6bf918c6ae.png)
![d1 0 - dashboard - marina with cases](https://user-images.githubusercontent.com/38183796/38604616-84a3a3aa-3da3-11e8-900a-e250d082bfc1.png)
[Pilot case - listing desktop](https://invis.io/KUEN7B954#/290546951_D1-0_-_Dashboard_-_Marina_Unit_With_No_Case)

Mobile View:
<img width="829" alt="screen shot 2018-04-11 at 6 00 19 pm" src="https://user-images.githubusercontent.com/38183796/38610521-be56c63a-3db3-11e8-9c57-bd9da6684dd2.png">
[Pilot - case landing mobile](https://invis.io/PGGSJRGAF6U#/290549427_Pilot_-_Cases_-_Landing_Copy)

First image shows what a user will see when they login for the first time before they create any case. It indicates the number of cases for each unit with a "add case" button. 

Second image is when cases are created. Top right hand corner dropdown to show how users can logout as current logout option is hidden in the logo area on the left.

Third image is the mobile view

**Comment by kaihendry** [comment]
Be good if **before** & **after** images are uploaded together so it's visually clear to see what's changed and what needs to implemented. URLs to the image are best.

What do the hamburgers mean? Priority ?

**Comment by franck-boullier** [comment]
I feel that the title of the issue is a bit misleading as it implies that:
* if the user logs in for the second time OR
* if the user is not a new user
then he/she will see a different screen...

@michkwt, maybe we can rename this issue to something like "Update landing page after user login"

**Comment by franck-boullier** [comment]
"What do the hamburgers mean? Priority ?"
Severity (not priority)

**Comment by franck-boullier** [comment]
about @kaihendry's comment "URLs to the image are best"
@michkwt maybe you can 
* keep the pictures 
* add the link to the corresponding screen in Invision

**Comment by franck-boullier** [comment]
@nbiton implementing this design
![image](https://user-images.githubusercontent.com/31331637/41885191-6f82eff0-7929-11e8-8563-05e3a215e0b8.png)

will solve a major issue reported by user today: it is no easy to scroll through the list of units to choose the correct unit when someone wants to create a case -> This design will enable us to pre-populate the case with the correct unit information

**Comment by franck-boullier** [comment]
Closed too fast.
PR #321 only implement the UX, we still need to make sure that the unit is pre-populated when the user clicks on the 'Add Case' link

**Comment by franck-boullier** [comment]
Make sure that we remove the 'Create Case' button at the bottom of the screen too: this becomes redudant once the 'Add Case' link next to each unit is implemented.

![image](https://user-images.githubusercontent.com/31331637/42145681-3943b318-7df5-11e8-8c7e-73c127a4c40d.png)

**Comment by sophieyang0813** [comment]
@nbiton will help with pre-populating a unit title section of the form, as it involves BZ API.  I will remove the Create New Case button.
