### ISSUE TITLE
Sign Up - "email already exist" error message should be displayed on screen

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#206]
Signup of existing email, should show an error message

(Screenshot shows the "result" after clicking submit)
![screen shot 2018-04-12 at 5 03 53 pm](https://user-images.githubusercontent.com/17175484/38667270-910ef79a-3e73-11e8-8930-84527b374d82.png)

Note that according to console.log, the API does respond appropriately for this.

![screen shot 2018-04-12 at 5 05 21 pm](https://user-images.githubusercontent.com/17175484/38667355-ce898ab8-3e73-11e8-9a23-ae888bcbdf8c.png)

**Site Tested**
+ https://dev.case.unee-t.com/signup
+ https://demo.case.unee-t.com/signup

**Browser Tested**
+ Chrome

**Comment by kaihendry** [comment]
Moving forward, how do we regularly (daily) test signup then? A random user every time? And then somehow nuke (teardown) the user later?

Or was the idea to reset the dev/staging DB @franck-boullier regularly?

**Comment by franck-boullier** [comment]
We test that in the Demo environment which we will nuke/reset every week

**Comment by franck-boullier** [comment]
If daily reset is need we can probably do that too

**Comment by franck-boullier** [comment]
If daily reset is need we can probably do that too

But we won't reset the dev as often...

**Comment by mariorodriguespt** [comment]
Bugzilla is another reason to add error messages #209
