### ISSUE TITLE
Media upload structure

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#211]
Currently assuming **preset folder** is off and **Autocreate folder** is on in the Cloudinary env settings we upload media prefixed by the Meteor ID:
https://github.com/unee-t/frontend/blob/a99c46198097b7c76fea242c0b642b4e78afd9df/imports/state/epics/create-attachment.js#L44

It looks pretty obfuscated to me in the [Media library](https://cloudinary.com/console/media_library). I think I would prefer to upload by case id and then tag by meteor ID. I'm assuming that media doesn't have fine grained access once its been shared in the case itself. I'm also assuming the media isn't shared between cases.

**Comment by franck-boullier** [comment]
Clarification 
"assuming that media doesn't have fine grained access once its been shared in the case itself."
I was talking about these

**Comment by kaihendry** [comment]
Media structure will be defined upon https://github.com/unee-t/s3-transfer-acceleration-cloudinary
