### ISSUE TITLE
Deleting of cases / Hiding of resolved cases

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#213]
This is more of a UX issue, especially for landlords. Where over the years, a property will pile up cases. Which would be probably be more then what i shown below.

![screen shot 2018-04-18 at 6 51 54 pm](https://user-images.githubusercontent.com/17175484/38927886-ba65786a-4339-11e8-95d8-2d98cbd4c942.png)
(PS : the automated test script, chooses a random pet name for each run)

There should either be a way to delete cases, which i understand would be difficult as most issue tracker disallow this : https://devzing.com/blog/index.php/how-to-delete-bugs-from-bugzilla/

Alternatively, would be to simply hide from the UI resolved cases by default unless it is enabled, aka like how github does it.

![screen shot 2018-04-18 at 6 55 53 pm](https://user-images.githubusercontent.com/17175484/38928040-2e03d1e0-433a-11e8-8a9c-0e33312875e1.png)

**Comment by michkwt** [comment]
![screen shot 2018-05-28 at 11 03 27 am](https://user-images.githubusercontent.com/38183796/40595394-cacd7c9c-6266-11e8-9403-641cc020b8c2.png)

https://invis.io/HMJKV8TKNC9#/299554760_unit_cases

@nbiton screens for hiding resolved cases.

**Comment by nbiton** [comment]
@michkwt Thanks, looks good :+1:

**Comment by franck-boullier** [comment]
Housekeeping - this is duplicate of issue #60 and issue #259
