### ISSUE TITLE
Simple unit listing interface

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#219]
https://projects.invisionapp.com/d/main#/console/12250377/262125865/preview
Lists the user's accessible units, links to the unit detail view, shows the button for adding a new unit (pending implementation of that feature). The current implementation will be for a single unit list only, multiple list management will be developed in a later phase.

**Comment by franck-boullier** [comment]
Changing the milestone from may 10th to may 20th.

In PR 227, the only thing missing is the "Add Unit" element

**Comment by franck-boullier** [comment]
Closing this as there is nothing more to do this exists in the master already since PR #227 has been merged
