### ISSUE TITLE
need to display the 'Solution' and 'next step' fields

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#22]
A lot of valuable information are stored in the 'solution' (field [cf_ipi_clust_1_solution]) and 'next_step' (field [cf_ipi_clust_1_next_step]) fields.
We need to add more field in the MEFE (read only is fine at first if read/write is too complex...

The Description and Comments fields are not useful enough to be able to interact meanigfully with a case.

**Comment by nbiton** [comment]
Is there an existing design we can refer to for implementation?

**Comment by franck-boullier** [comment]
Design for pinned message:
https://marvelapp.com/1112648g/screen/34325322
We use pinned messages for solutions and next steps.

**Comment by franck-boullier** [comment]
Idea is probably to replace the text 'pinned message' with 'Next Step' and 'Solution' Respectively

**Comment by franck-boullier** [comment]
See issue #48 for how this behaves in PR41

**Comment by franck-boullier** [comment]
This works on PR 53
