### ISSUE TITLE
Unit detail view

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#220]
https://projects.invisionapp.com/d/main#/console/12250377/262125862/preview
List the cases, inspection reports, general info and people for this unit.
Provided a link to create new inspection reports

**Comment by michkwt** [comment]
@nbiton This should be the right link for the unit detail view: https://invis.io/T4IE2L45YXJ#/291973455_Unit_-_Case_Created_With_Report

**Comment by franck-boullier** [comment]
Thos work except for inspection report listing as inspection report is still WIP
Closing this as this exists in the master today

**Comment by franck-boullier** [comment]
incorrect: this was NOT implemented in the master yet...

**Comment by franck-boullier** [comment]
First release of this feature now works in the Master.
We have a few improvements identified which will be implemented in future releases.
