### ISSUE TITLE
Call Web hook to process invites on new invite

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#228]
https://invite{{STAGE}}.unee-t.com as documented in Postman under **Process invitations**.

Implemented at https://github.com/unee-t/invite

**Comment by nbiton** [comment]
It does work now, but MEFE was not prepared to handle the immediate reception of a new user to case in the UI. It is only seen after refreshing. This requires manipulation of the data subscription logic.
I'm currently cracking that solution.
