### ISSUE TITLE
PR227 - top navigation bar and add case button are not docked

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#229]
On PR227 in the page which list the units for a given case the top navigation bar and 'Add case' button are not docked.
Landing:
![image](https://user-images.githubusercontent.com/31331637/40048348-9afca364-5864-11e8-9a50-0dd35dfc71f3.png)

if you scroll down:
![image](https://user-images.githubusercontent.com/31331637/40048395-b2d6ccda-5864-11e8-83e4-b1bc3c83de2c.png)

**Comment by nbiton** [comment]
I tried to recreate locally, but couldn't (the button was fixed and didn't move with the scrollable content).
Can you provide me with the credentials of a user on dev with enough cases to test this?

**Comment by franck-boullier** [comment]
Credential: leonel@example.com
Tested with Firefox browser in inspect mode
I have no issue on my Galaxy S8 (tested on Chrome and the Samsung default browser) though so this seems to be browser specific...

**Comment by nbiton** [comment]
Fixed in #227 . Please review again
