### ISSUE TITLE
No access to the full description of the case

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#23]
Case description is truncated with no possibility to expand this.

**Comment by nbiton** [comment]
We need to find a UI solution for this

**Comment by franck-boullier** [comment]
You can have a look here:
https://marvelapp.com/1112648g/screen/34393248
for design solution to display more information about a specific case.

**Comment by kiatlim** [comment]
> so for #23 I could just make the text multiline, and for #22 I create two adjacent fixed "rows"  that looks like the "pinned message" in your design?

Yes, actually it doesn't have to be pinned, I just placed it at the top as the first thing the user will see when they load the case. Next steps and solutions can be shown there as well. 

If the information ends up getting too much, we can always make the "Title" Aircon is leaking in Living Room clickable and it goes to the details.

**Comment by nbiton** [comment]
The message list is automatically scrolled to the bottom when this screen is loaded (like other conversation UIs). I think that if we place these two items next to the title, they should not be scrolled with the message list, but remain fixed so they're visible at all times. Otherwise, once the list needs to be scrolled, it wouldn't be very intuitive to scroll all the way up to find them.

**Comment by kiatlim** [comment]
Good point, then in that case putting them in a separate screen together with the next steps / solution might be more ideal.

**Comment by nbiton** [comment]
Is there a design we can refer to for this?

**Comment by kiatlim** [comment]
Let me put something together quickly tonight.

**Comment by franck-boullier** [comment]
My 2 cents...
Alternatively we could "pin" these 2 thing always at the top of the screen, just below the truncated case title...

We can keep only the first 2 lines of the Next Step and/or Solution (if they are not empty, if empty, they're not displayed).
- Click/Tap will show more lines.
- Long press will allow edit of the Next Step or solution.

We're loosing screen real estates for other messages but since Next Step and Solution are key information this is not too much of an issue...

**Comment by franck-boullier** [comment]
This works well in PR41
