### ISSUE TITLE
PR227 - Unit description should come from the MEFE

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#230]
The unit description is currently exported from the BZ side. This shouls be changed and we should use the Unit description from the MEFE.

![image](https://user-images.githubusercontent.com/31331637/40048621-42dbd438-5865-11e8-8811-02e9bfb4314e.png)

**Comment by nbiton** [comment]
There's nowhere to get this info in MEFE yet, as it is dependent on the unit creation feature. Shouldn't we remove this from milestones until it is not blocked?

**Comment by franck-boullier** [comment]
Let's push this back to after we have the unit creation interface up and running (see PR #237

**Comment by kaihendry** [comment]
I noticed the description seems to contain:
* name of condo
* address
* sqft size
* sometimes markup ?

In free format.

Shouldn't it be better structured? The title often seems a little unstructured to me too. If there is a method to this, just let me know.

**Comment by franck-boullier** [comment]
@kaihemdry: you are right this should be structures and will be in the MEFE once we have the unit creation module up and running.
What we have now is a temporary solution.
See the design in Incision if you want to have an understanding of how it will be done...

**Comment by nbiton** [comment]
Ok, not dependent on #145, as we decided to import unit information manually
