### ISSUE TITLE
PR227 - Pictogram seem to display bug priority (should be severity)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#231]
@nbiton it seems that the pictogram on the left side of each case are for the case priority (P1, P2, P3, P4), 

The design is to display the case severity instead (Critical, Major, etc...)

Can you confirm that this is the case?

**Comment by franck-boullier** [comment]
![image](https://user-images.githubusercontent.com/31331637/40049010-306c450c-5866-11e8-88e8-539bc9242f5d.png)

**Comment by nbiton** [comment]
It already does represent "severity" (which is also the severity field in BZ). "DEAL BREAKER!" corresponds to 5 lines, "critical" is 4... minor is 1

**Comment by franck-boullier** [comment]
Perfect!
