### ISSUE TITLE
PR227 - Case overview - People displayed - missing co-tenant

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#232]
In PR 227, in the overview for the people the list of people invited to this unit seem to miss the co-tenant (people that are invited to the unit but NOT the default assignee to a role/component)

Ex: in the DEV staging
Logged as Leonel
Unit #283
There are 2 co-tenant there (Jocelyn and Marina)
![image](https://user-images.githubusercontent.com/31331637/40049307-fd87368c-5866-11e8-8ac5-dcf24dd826f6.png)

The MEFE only shows 1

![image](https://user-images.githubusercontent.com/31331637/40049260-d0a04d70-5866-11e8-96a6-27387624c10b.png)

**Comment by franck-boullier** [comment]
@nbiton my guess is that this one was fixed thanks to the unitRoleData Based upgrade, can you confirm that my understanding is correct and close this Issue if all OK

**Comment by nbiton** [comment]
I can't check if that particular scenario acts out differently, but the code definitely should be using unitRoleData to resolve the roles in this case, instead of the previous method used when this issue was reported

**Comment by franck-boullier** [comment]
Closing this issue for now...
