### ISSUE TITLE
PR227 - Unit overview - link to case - back button issue

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#234]
In PR 227 go to Unit Overview >> pick a unit >> click on a link to a case
![image](https://user-images.githubusercontent.com/31331637/40049693-fc1cabb4-5867-11e8-9570-7c486404a6a5.png)

We go to the case details, this is expected
![image](https://user-images.githubusercontent.com/31331637/40049722-1047620a-5868-11e8-8fdb-1781da36d927.png)

Click on the 'back' arrow on the top left
Expected result: return to the List of case from the unit overview

Actual result: return to the list of all the cases.
![image](https://user-images.githubusercontent.com/31331637/40049793-3c74bac6-5868-11e8-9272-ec451bb2224c.png)

**Comment by nbiton** [comment]
Check on #227

**Comment by franck-boullier** [comment]
Fixed in latest version of PR #227
