### ISSUE TITLE
Create unit API

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#237]
IIUC similar to the **list invites** as documented in our postman@unee-t.com account, https://github.com/unee-t/unit needs an API to scrape in order to create the Unit.

**Comment by sebdeckers** [comment]
@kaihendry Not sure why this was assigned to me.

Is this just another good newbie issue? If so, perhaps use a semantic issue label instead of directly assigning a person.

FYI: I'm currently tasked with Unit Creation screen (#225). Once done I'd like to evaluate the next best chunk of work.

**Comment by franck-boullier** [comment]
See https://github.com/unee-t/unit for latest status on this
