### ISSUE TITLE
User not notified when assigning the case

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#245]
On a563744 on https://case.unee-t.com/case/66388/details (production) I impersonated my landlord with hendry+ownertest, but I didn't receive the email or notification? Was one sent?

I can see in the logs a user was created, but shouldn't the user be notified?

<a href="https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=meteor;stream=80b4b1c9546b989e2eae28fe0b31d855a27506097dff9df07dd11246ebbb498b;filter=hendry"><img src="https://s.natalian.org/2018-05-23/1527040468_2558x1406.png"></a>

Bonus points: Would be nice to be able to tell if a user has been already invited/notified.

**Comment by franck-boullier** [comment]
Until the invitation is processed in full nothing is sent
Once the invitation is processed in full you are informed: a message is added to the case
I need more information to know if this is a real issue or not but it doesn't seem to be at first glance...

**Comment by franck-boullier** [comment]
I just processed an invite which was pending in the queue
@kaihendry this might have answered your questions, can you check and report in this GH issue please?

**Comment by kaihendry** [comment]
Yes, I have the message now.

Can I assume it's because https://github.com/unee-t/frontend/issues/228 is not yet closed?

**Comment by franck-boullier** [comment]
> Can I assume it's because #228 is not yet closed?

Yes, this is absolutely right!
