### ISSUE TITLE
Attachment not rendered

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#246]
Any ideas why?

<img src="https://s.natalian.org/2018-05-23/1527042377_2558x1406.png">

Upon https://dev.case.unee-t.com/case/61918

The [image URL](https://res.cloudinary.com/unee-t-staging/image/upload/v1524122967/yyDSKfD3pRno3LRqo/ec8wkc7st6rddlzphqkc.jpg) does work.

**Comment by nbiton** [comment]
I employed a temporary fix (but stable). Which was to change the cloudinary url to the proper value (it should end with 'image/upload' and not 'auto/upload'). It's temporary since we're going tp switch over to uploading directly to S3 instead.

**Comment by franck-boullier** [comment]
this works in the dev/staging envo now
