### ISSUE TITLE
Use https instead of http for the MEFE

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#25]
URLs in the MEFE are http.
We need to route all http URL to the https version of the URL

**Comment by kaihendry** [comment]
https://dev.case.unee-t.com/

**Comment by franck-boullier** [comment]
https://dev.dashboard.unee-t.com/ does work all right but

http://dev.dashboard.unee-t.com/ does not seem to re-rout to https://dev.dashboard.unee-t.com/

This is the same for:
* http://dashboard.unee-t.com/
*http://case.unee-t.com/
*http://dev-case.unee-t.com/
These do not route automatically to the https (canonical) version of the site.

**Comment by kaihendry** [comment]
Oh, I see, so we need redirect in place.

I guess this best done by some Apache rule in https://github.com/unee-t/bugzilla-customisation
