### ISSUE TITLE
https re-routing for the MEFE (Case) - incorrect domain name in DEV

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#250]
In the DEV/Staging, when re-routing http calls to https the urls are re-written as 'https://dev.case.unee-t.com' 
The new syntax for the url for our environment are 
- case.dev.unee-t.com (instead of dev.case.unee-t.com)
- case.demo.unee-t.com (instead of demo.case.unee-t.com)

We need to make sure to use the new url syntax when we re-route http to https:
- https://case.unee-t.com for the PROD
- https://case.dev.unee-t.com for the DEV
- https://case.demo.unee-t.com for the DEMO

@kaihendry feel free to chip in if you see an issue with that.

**Comment by nbiton** [comment]
Test on dev server (pushed directly, as it is un-testable on a review app)

**Comment by nbiton** [comment]
It doesn't work yet... I'm waiting a few minutes to see if the deployed changes are already in effect

**Comment by nbiton** [comment]
Seems to work now.
@franck-boullier close it when you see fit

**Comment by franck-boullier** [comment]
this works in the dev/staging envo now
