### ISSUE TITLE
Unit View - Need to differenciate between open and closed case

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#259]
In the current version of the Master, there are no differences between open and closed cases

![image](https://user-images.githubusercontent.com/31331637/40667572-19d84126-6395-11e8-8d87-4cfff4d98aeb.png)

We need to implement the design to discriminate between open and closed cases
![image](https://user-images.githubusercontent.com/31331637/40667732-6936c79c-6395-11e8-9adb-86b532341aab.png)

**Comment by franck-boullier** [comment]
The suggested design is available here:
- https://projects.invisionapp.com/d/main#/console/12250377/299554760/preview
![image](https://user-images.githubusercontent.com/31331637/40732752-8cce0f0e-6466-11e8-963e-d48672eafe20.png)

- https://projects.invisionapp.com/d/main#/console/12250377/297379268/preview#project_console
![image](https://user-images.githubusercontent.com/31331637/40732772-a37b9348-6466-11e8-96e7-84d483e3a2ec.png)

**Comment by franck-boullier** [comment]
This was implemented in the June 25th release

**Comment by sophieyang0813** [comment]
@franck-boullier I see `open` and `closed` under a unit in the latest version. Could you help me understand the issue better? 

![image](https://user-images.githubusercontent.com/25441733/43189766-f9a2264e-9029-11e8-9b29-d6e74a0f5e8e.png)

**Comment by franck-boullier** [comment]
But I updated the wrong issue (my bad)
