### ISSUE TITLE
New Comment disappear after succesfull posting

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#26]
The test:
In the MEFE, as user franck go to claim 12345.
This claim is accessible and modifiable for franck.
In the MEFE, using FF on a desktop, create a new comment.
Post the comment.
The comment is posted.
After a short period of time the additional comment disappear in the MEFE.

Once the browser is refreshed the comment re-appears again.

New comment is visible on the BZFE too (good, this was expected)

**Comment by nbiton** [comment]
This probably means there was some error on the BZ API which signals to MEFE that the comment couldn't have been created (even though it was). I've seen it happening when the email related BZ config parameters are not set correctly, so when a new comment is created, and BZ tries to notify all stakeholders via email, the failure to send the email causes the API request to return a failure http code.
We need to check the logs on the BZ instance and see if that's the case.
Can @kaihendry assist?

**Comment by franck-boullier** [comment]
fixed in latest version of PR 28
