### ISSUE TITLE
Unit View - We need to differentiate enabled and disabled units with new design

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#260]
A unit in Unee-T can be either:
-  **Enabled** (it's possible to create new cases) 
or 
- **Disabled** (not possible to create new cases)

As of today we are not making any distinction between enabled and disabled units in the MEFE.
![image](https://user-images.githubusercontent.com/31331637/40667906-d3ec5e3a-6395-11e8-868a-1e1764f6d837.png)

This is an issue for several reasons the most visible is that when we are trying to create a case for a disabled unit in the "unit" view:
![image](https://user-images.githubusercontent.com/31331637/40667966-f6f4b026-6395-11e8-9f5f-14b50fdbc6ac.png)

Then the MEFE is stuck: the BZFE will not allow the creation of a new case for this unit (which is expected) and this appears as a bug to the MEFE user.

![image](https://user-images.githubusercontent.com/31331637/40668035-1fd91d60-6396-11e8-9086-2705b3025777.png)

**Comment by sophieyang0813** [comment]
What frontend design do we use for enabled and disabled properties? Is there anything required from meteor side? How would this work vis-a-vis BZFE? We can also consider a different name with a single property that has true or false boolean value (i.e. locked & unlocked).

An alternative to this feature is to hide disabled ones?

**Comment by nbiton** [comment]
That's a good question! :smile: The indication that a unit is disabled should appear on the unit list. Hiding it is not a good option, unless we have an on/off filter.
We'll probably need some input from @kiatlim 

Other than the list, the "+" button on the unit's cases list should not appear.
The property you need to check to know whether a unit is disabled or not is "is_active" of a unit (https://bugzilla.readthedocs.io/en/5.0/api/core/v1/product.html#get-product)
For now, it will be toggled on and off only via the BZFE until we implement a similar feature in MEFE

**Comment by franck-boullier** [comment]
@sophieyang0813 and @nbiton the design is there already, see Invision or the RealtimeBoard for more about that

**Comment by franck-boullier** [comment]
This looks like this (more screens in the RealTimeBoard)
![image](https://user-images.githubusercontent.com/31331637/41525088-6ea0707a-7312-11e8-8604-f3f72217bc53.png)
@kiatlim can help you navigate these for sure

**Comment by nbiton** [comment]
![screenshot from 2018-06-18 16-18-41](https://user-images.githubusercontent.com/2662819/41525374-59490d08-7313-11e8-8471-e165f935bd0a.png)
Yeah, I just saw this on Realtimeboard. I'm guessing this is the option to implement after reading your comment. I can't find these screens on Invision btw.

The implementation of the UI is not exactly what I thought it would be...

**Comment by franck-boullier** [comment]
Latest design and flow is available in the [RealTime Board](https://realtimeboard.com/app/board/o9J_k0ckGU4=/)

![image](https://user-images.githubusercontent.com/31331637/42146083-019d57f4-7df8-11e8-9c4b-7fd36d109615.png)

**Comment by sophieyang0813** [comment]
Afternoon, @nbiton ! `ownerId` is still not accessible even after adding `ownerIds: 1` to the list of fields. MetaData of unitList (props in unit-explorer) returns only `name` and `_id`. 

![image](https://user-images.githubusercontent.com/25441733/42365694-c89708b4-8131-11e8-9087-74ca77ee1b53.png)
<img width="847" alt="screen shot 2018-07-06 at 3 32 59 pm" src="https://user-images.githubusercontent.com/25441733/42365800-171e4a42-8132-11e8-8570-ce8106265d63.png">

**Comment by nbiton** [comment]
Oh, I think you won't see it as this unit was not created in your local system.
Try this with a unit you created yourself instead

**Comment by sophieyang0813** [comment]
Thank you! How do I get values for INVITE_LAMBDA_URL and UNIT_CREATE_LAMBDA_URL?  Unit creation with the values from`aws-env.dev` raised the following error: `url must be absolute and start with http:// or https://`. Now, I am trying`env.sample`. For values, I am supposed to <run the “unit” project on a separate port and place the url here, add ‘/create’ at the end>. I am not sure how I configure a separate port and wonder if there is any preferred port number?

**Comment by franck-boullier** [comment]
Implemented in Production already
