### ISSUE TITLE
Attachment - full view for an attachment you just uploaded is broken

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#269]
Clicking on an attachment you just uploaded, without refreshing, changes the url to '/case/:id/attachment/:attachmentId', which is expected, but the view remains on 'messages' and doesn't show the attachment in full view.

Workaround: refresh the page, or go out of the case and back in

**Comment by sophieyang0813** [comment]
Yesterday's Conversation on leonel@example.com (post here for future reference) 
<img width="585" alt="screen shot 2018-08-10 at 10 46 22 am" src="https://user-images.githubusercontent.com/25441733/43936371-c1f83c7a-9c8a-11e8-8a67-52d63382436e.png">
<img width="591" alt="screen shot 2018-08-10 at 10 46 34 am" src="https://user-images.githubusercontent.com/25441733/43936373-c34f0298-9c8a-11e8-872e-41c51dce8e03.png">
