### ISSUE TITLE
Always use API_ACCESS_TOKEN when calling internal APIs

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#274]
For example, with no token APIs will fail:
```
[hendry@t480s ~]$ curl -X POST https://apienroll.dev.unee-t.com
Unauthorized

```

Create token is stored as **API_ACCESS_TOKEN** in the parameter store.
```
[hendry@t480s ~]$ curl -X POST -H "Authorization: Bearer $(aws --profile uneet-dev ssm get-parameters --names API_ACCESS_TOKEN --with-decryption --query Parameters[0].Value --output text)" https://apienroll.dev.unee-t.com
Invalid JSON
```

It's invalid JSON since the payload is not correct. Just an example.

This will be the case with **ALL APIs**. E.g. This will become _Unauthorized_ without correct token:
```
[hendry@t480s ~]$ curl -X POST https://invite.dev.unee-t.com
Worked
```

**Comment by nbiton** [comment]
We are doing that currently. Closing the issue
