### ISSUE TITLE
Several mandatory user/unit attributes are needed

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#278]
# Overview:
We need to be able to know several key information about user and units.

One (easy) way to record this is to keep a mapping table where we store these information so we can enforce several rules.

This is marked as critical as a lot of things will be depending on the information stored there, namely the permissions for this user and that unit, notably the capability to add/remove users to a role in that unit.

# The rules we need:
- A user can only have 1 role in any given unit (occupant is not a role, it is an additional attribute for the user) -> The key unit_id/user_id must be unique in this table
- There is a finite number of possible roles that we can assign to a user in a unit
- We can only create the user if the unit and the user role exist in the MEFE.

# The information we need:
For each unique record user_id/unit_id we need to be able to easily retrieve:

### Possible values:
As of today, the user role in a unit can be either one of the following:
- 1: Tenant
- 2: Landlord/owner
- 3: Contractor
- 4: Management Company
- 5: Agent

### Default assignee for this role
Whether this user is the default assignee for this role for this unit
  - 1 = yes (there can be ONLY 1 default assignee for each role in each unit)
  - 0 = no

## Is the user an occupant?
Whether the user is an occupant in that unit or not:
- 1 = yes
- 0 = no

## Is this user publicly visible or not:
Whether any user can see this user in the list of possible assignee or invited people or not
- 1 = Publicly visible
- 0 = NOT publicly visible

# Who invited this user:
The MEFE user if of the user who invited this user in the first place. This will enable us to always display this user to the invitor (for this unit only) if appropriate.

# Permissions:
Permissions for that user for that unit are used to enable/restrict what is this user allowed to do in this unit or not. 
These permission will be added as we develop Unee-T. 
At the moment, we are using default permissions. This will change VERY soon as we need to restrict the ability to remove/add user in role for a unit.  
The permissions for a user will be grouped in different categories:

## Permissions related to that unit:
This is NOT dependent from the user role and should be managed separately. Example of permissions are
- Add a user in a role in a unit (can invite)
- Remove a user in a role in a unit
- Change the default assignee for a role in a unit
- Edit the unit information (name, address, etc...)
- Can make a unit inactive (prevent creation of new cases in that unit)
- ...

## Permission related to cases for that unit:
Examples of permissions are:
- Invite/Add a user to a case
- Create a new case
- ...

**Comment by franck-boullier** [comment]
@nbiton can you have a look at this and comment/update if needed
Thanks!

**Comment by franck-boullier** [comment]
This is necessary so we can do issue #194 properly (we should only enable user to remove another user in a role for a unit if the user is allowed to do that)
This should help fix issue #138, issue #82 and issue #107

**Comment by nbiton** [comment]
Some of these bits of information are already stored today.
The ones that aren't are:
* Default assignee for a role in a unit
* Is the user publicly visible on a unit
* Everything that is related to the mentioned fine-grained permissions
* All of the TOS and agreement acceptance items

**Comment by franck-boullier** [comment]
Please see also Issue #107 on why some attributes are need for each user (Especially the 'publicly visible' part)

**Comment by nbiton** [comment]
The items related to TOS were split off to https://github.com/unee-t/frontend/issues/359

**Comment by nbiton** [comment]
Closing as the items on here are all stored in the mongo.

@franck-boullier feel free to reopen if you find something that I missed
