### ISSUE TITLE
Migrate all unit data to Mongo

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#283]
This will involve 2 parts:
* Write a migration to fetch all unit data from BZ, create a "units" collection on Mongo that contains the id, bzName ("name" from BZ) retrieved from BZ API and empty schema fields for new meta data: displayName, streetAddress, city, country, state, zipCode (to be implemented by @nbiton)
* Populate the new empty schema fields in Mongo with real data related to the units (to be done by @franck-boullier)

**Comment by franck-boullier** [comment]
@nbiton 
Let me know when the DB is ready and the update of the mongo DB with the information for the units will be done within 4 to 8 hours (depending of the time of day when Mongo is ready...)

@nbiton If writing a migration takes you more than 15mn then please do NOT write a migration script, just prepare the empty Mongo collection for the units and I will do the updates.

**Comment by nbiton** [comment]
The migration creates the following types of documents: 
* In a new collection called "unitMetaData", one document is created per unit that looks like this: 
![screenshot from 2018-06-19 15-06-01](https://user-images.githubusercontent.com/2662819/41581874-9a554a90-73d2-11e8-9860-1eec6d55e32f.png)
* In a new collection called "unitRolesData", 5 documents (one for each possible role type) are created per unit, and they look like this:
![screenshot from 2018-06-19 15-06-38](https://user-images.githubusercontent.com/2662819/41581917-c4171c78-73d2-11e8-85b2-fcb08ad166cb.png)

The "members" field is designed to hold objects of the following format:
```
{
  id: user's mongo _id,
  isOccupant: Boolean,
  isVisible: Boolean (is publicly visible),
  isDefaultInvited: Boolean (is invited to new cases by default)
}
```

**Comment by franck-boullier** [comment]
Cool, thanks! I will have a look at this later today

**Comment by franck-boullier** [comment]
@nbiton where in mongo do we store the information "unit created by user xxx"?
I can't see where I could record that in the collection `unitRolesData`

**Comment by franck-boullier** [comment]
@nbiton maybe we should put  "unit created by user xxx" in the `unitMetaData` collection as an array of bz user id in a field `unitOwner`?

**Comment by nbiton** [comment]
We don't record that information... neither do we record "additional information". And I think we also need "Unit type" (although I'm not sure what would be the enum values for that).

It looks like I could add another migration to create the empty base for these additional fields

**Comment by nbiton** [comment]
Yes, I also think it should go into `unitMetaData`

**Comment by franck-boullier** [comment]
We should probably also add a timestamp to record when that unit was created too

**Comment by franck-boullier** [comment]
`unitType` could be something like:
- Unspecified (defautl value until the user changes it)
- House
- Flat/Apartment
- Shop
- ...

This would impact the icon that we will display in the MEFE too and will be useful for statistical purposes too...

**Comment by franck-boullier** [comment]
@nbiton can you check in the Mongo DB in the DEV/Staging that the format after the import in the collection `unitRolesData` is what you expect?

**Comment by franck-boullier** [comment]
Done in the DEV/Staging and in the PROD environment
