### ISSUE TITLE
Report creation- list reports in the unit's reports tab

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#287]
https://projects.invisionapp.com/d/#/console/12250377/300869284/preview
It should look like that, but the list should help differentiate between finalized and drafted reports. The green check mark next to the report icon on the left will be changed to something else in case the report is still a draft.
![screenshot from 2018-06-14 11-21-17](https://user-images.githubusercontent.com/2662819/41389839-9673b774-6fc5-11e8-9cac-da811806dc6d.png)

**Comment by franck-boullier** [comment]
Implemented in PR #422
