### ISSUE TITLE
Report creation- main report drafting view

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#288]
https://projects.invisionapp.com/d/#/console/12250377/300869258/preview

It should look like the design mentioned above, and allow the user to take the following actions:
* Change the title of the report.
* Add an image attachment.
* Finalize the report (When 'Complete' is pressed)

The rest of the actions implied by this design will be addressed by separate GH issues

**Comment by franck-boullier** [comment]
Implemented in PR #422
