### ISSUE TITLE
case/xxx - The time format inside the date container is not 24h

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#29]
The container that display the date separator between messages sometimes display time.

When time is displayed, it's not using a 24 hours format (the standard we chose to display time information).

![image](https://user-images.githubusercontent.com/31331637/33418676-f9b5c710-d5e1-11e7-867e-43f895012690.png)

**Comment by franck-boullier** [comment]
Also, why do we display time there?

**Comment by nbiton** [comment]
It's a bug :)

**Comment by franck-boullier** [comment]
fixed into the latest version of PR28
