### ISSUE TITLE
invite user to a case - screen is stuck (endless load) - invitation email not received

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#297]
# The test:
Invite a user to a case
Specifics:
- the invited user already exists in Unee-T
- the invited user has no role in the unit (yet)

# Expected result:
- Invitation is sent to the user
- Invitation has been sent to the user message is displayed in the case interface
- email notification is sent to the invited user

# Actual result:
- Unee-T is stuck
![image](https://user-images.githubusercontent.com/31331637/41632614-5563e7d4-746d-11e8-8d95-dca56230b56f.png)
- after a 10mn, the invitation email has still not been received
- Invitation is processed in the BZ backend: invited user is visible in the dashboard
- InvitOR can access the case in the dashboard
- InvitOR CANNOT access 'more info' for the case in the MEFE anymore

In order to allow the invitor to access the 'More Info' part of the case we had to:
- remove the invited user from the list of the users in CC to the case in the dashboard
- force refresh the browser for the case interface

**Comment by franck-boullier** [comment]
# More test:
Send an invite to a user who is NOT an admin user with a role in this unit

# Actual result:
- Invitation confirmation message is correctly displayed BUT with some errors in the console
![image](https://user-images.githubusercontent.com/31331637/41633164-0f79a5ee-7470-11e8-81b9-52153ad36300.png)
- user is created in the BZ back end

- user invitation does NOT appear in the table `ut_invitation_api_data` 
@kaihendry : there seems to be an issue with the API to auto process the invitation...

**Comment by franck-boullier** [comment]
# More test:
This is the result I get when I try to manually trigger the API with postman:
![image](https://user-images.githubusercontent.com/31331637/41633343-fc582534-7470-11e8-8be7-8faad736156b.png)

**Comment by franck-boullier** [comment]
# More test:
In the Meteor DB for the PROD, check is there are unprocessed invitation

# Result:
There are 8 unprocessed invitation in the prod as of now

**Comment by kaihendry** [comment]
There was a bug I introduced yesterday. Just processed the back log.

Btw your Postman test should look like https://s.natalian.org/2018-06-20/1529460833_2558x1406.png


Notice the domain is **invite.unee-t.com**

**Comment by franck-boullier** [comment]
> Notice the domain is invite.unee-t.com

@kaihendry : I see no difference in the domain... What am I missing?
![image](https://user-images.githubusercontent.com/31331637/41633778-0961f320-7473-11e8-89ca-39fab44fca5c.png)

**Comment by franck-boullier** [comment]
OK I see the 8 records in the BZ table `ut_invitation_api_data` now
Still confused why your screenshot only shows 3 though...

**Comment by kaihendry** [comment]
Had to run it twice since it timed out after doing 5. Wish I new why running the SQL takes so long!

**Comment by franck-boullier** [comment]
> Wish I new why running the SQL takes so long!

I know this is a script with several hundreds (close to 3,000) lines of code which has to run in a precise sequence too
You have to  that you have to run for each of the invitation -> long time

**Comment by franck-boullier** [comment]
>  Fix unee-t/frontend#297 

This only fix one part of the problem (API invitation not being triggered)
There are also some MEFE related fixes that need to happen too to make sure:
- The MEFE is not stuck after the user is invited to a case
- The link included in the email notification works as intended

**Comment by franck-boullier** [comment]
@kaihendry do we have to do a release of the unee-t front end in order for your fix to be implemented in the production environment?

**Comment by kaihendry** [comment]
I am not sure why it is stuck. Can this be reproduced on dev?

What is wrong with the link in the email?

**Comment by franck-boullier** [comment]
Issue is fixed in the prod environment now
