### ISSUE TITLE
Voice memos

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#3]
https://voice-memos.appspot.com/ is a nice example to draw inspiration from and should be working from [Safari 11](https://twitter.com/Paul_Kinlan/status/903155403877482496).

**Comment by franck-boullier** [comment]
What needs to happen if we want to fast track that?
there are 3 different issues AFAICT:
- @kaihendry : where do we store the voice messages (I'm guessing S3 - can you provide insights on that)
- @ongdominic: the UK to select "voice memo"when creating an attachment <--- I think we have it somewhere.
- @nbiton: update the MEFE so that we can capture voice memos as a link to a S3 resource (based on what @kaihendry 's reco is)

Can I have an estimate of how hard/complex it'll be to implement?

**Comment by kaihendry** [comment]
Yes S3 would be a natural choice for storage. I guess we would store them in the same way we do inspection reports for consistency.

**Comment by franck-boullier** [comment]
> Yes S3 would be a natural choice for storage. I guess we would store them in the same way we do inspection reports for consistency.

@kaihendry when can you start working on that so we can have that piece of the puzzle ready at least?

**Comment by ongdominic** [comment]
So here are the screens related to voice memo:

<img width="233" alt="Screenshot 2019-07-17 at 4 38 11 PM" src="https://user-images.githubusercontent.com/46714451/61360682-8117a900-a8b1-11e9-9b20-7299c49daf62.png">
<img width="200" alt="Screenshot 2019-07-17 at 4 38 33 PM" src="https://user-images.githubusercontent.com/46714451/61360684-8117a900-a8b1-11e9-93d1-0cf40e04342b.png">


Here the figma [link](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=0%3A6538)

**Comment by nbiton** [comment]
@ongdominic We need more info on how this is going to look while it's playing. Also, I imagine the voice memos would appear in the conversation view, so we need to decide how that looks like too.

**Comment by kaihendry** [comment]
I would recommend using the default audio element https://html.spec.whatwg.org/multipage/media.html#the-audio-element at least without styling at first. https://caniuse.com/#feat=audio

**Comment by franck-boullier** [comment]
> I imagine the voice memos would appear in the conversation view

that is my assumption too

**Comment by kiatlim** [comment]
For the conversation view of the audio element, I tested the audio element on the mobile browsers (Chrome/Safari), it appears more like the one on the right. On desktop browser, it's the one on the left. Not sure if we can customise the mobile appearance of the same element. 

![image](https://user-images.githubusercontent.com/641679/61617628-a899b780-ac9d-11e9-9c0f-8bf77009c88d.png)

**Comment by nbiton** [comment]
Yes, we can style it

**Comment by kiatlim** [comment]
On the attachments listing, playback can have 2 options, depends on whats easier. Both playbacks are activated on tap of the voice memo item. 

![image](https://user-images.githubusercontent.com/641679/61618887-63c35000-aca0-11e9-878f-52a3fae909f4.png)

**Figma link:** https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=3581%3A5546

**Comment by franck-boullier** [comment]
I vote for option 2

**Comment by ongdominic** [comment]
Here's how users can record their voice memos on the comments page. Its a press and hold function and once you are done speaking, you release it and the message gets send immediately. 

<img width="755" alt="Screenshot 2019-07-25 at 4 32 33 PM" src="https://user-images.githubusercontent.com/46714451/61859060-f579ca00-aef9-11e9-856b-86d676a70925.png">

Details are in [figma](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=3732%3A488)

**Comment by ongdominic** [comment]
Based on the feedback from Naor, there won't be a press and hold interaction. Instead, we will use a static screen to record voice memo. 

<img width="850" alt="Screenshot 2019-07-25 at 5 13 23 PM" src="https://user-images.githubusercontent.com/46714451/61861931-87380600-aeff-11e9-8471-08ddc4f5706b.png">


Details are in [figma](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=3749%3A6)

**Comment by ongdominic** [comment]
Here is another alternative solution:

<img width="710" alt="Screenshot 2019-07-25 at 5 48 21 PM" src="https://user-images.githubusercontent.com/46714451/61864754-8f467480-af04-11e9-88b9-0db9c3cef65b.png">

Details are in [figma](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=3759%3A0)

**Comment by kaihendry** [comment]
Voice could be transcribed with [Amazon Transcribe](https://aws.amazon.com/transcribe/)

**Comment by nbiton** [comment]
Resolved in #858
