### ISSUE TITLE
Need to configure the Time Zone for the user

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#30]
The default Time Zone for the BZFE installation will be UTC.

When we create a user in the BZFE, we need to make sure that we record the TimeZone preference of the user in the BZFE.

In the BZFE back end, this is a parameter which is controlled by the user in Preferences > General Preferences > Timezone used to display dates and times.

**Comment by nbiton** [comment]
I think this issue belongs to [unee-t/bugzilla-customization](https://github.com/unee-t/bugzilla-customisation), no?

**Comment by franck-boullier** [comment]
@nbiton 
"I think this issue belongs to unee-t/bugzilla-customization, no?"

Yes but not only: in the MEFE we need to have an way (an interface) for the user to configure his preferred time zone.
Probably not needed in the MVP but will be necessary sometimes down the road...

**Comment by nbiton** [comment]
I'm not sure if it will be, unless the user prefers to see in a fixed timezone and not the local one. Currently, the time shown always matches the local client system's timezone, by using the browser's core Date interface. This is unlike BZ which renders the presented date/time on the server, so it needs a timezone setting to do it properly.

**Comment by franck-boullier** [comment]
good point, let's assume that the TZ we will use for the user will always be the TZ from the user's browser then (simpler)

**Comment by franck-boullier** [comment]
In the latest version of the PR, the timezone displayed is NOT the user timezone.

Test: post a comment on the MEFE (or the BZFE - behavior is the same).

Expected behavior: timestamp of the comment will be the time from the user client and displayed as the time for the user client.

Actual behavior:
Timezone displayed for the comment is not accurate
Comment made at 11h55 SGP time by a user using the default configuration (UTC) in the MEFE:
- Stored as made at 03h55 in the BZFE 'longdesc' table
- The timestamp for this comment in the MEFE is 07h55
- The timestamp for this comment in the BZFE is 07h55

BZ default preference: use UTC
BZ server time: ???
BZFE user perference: use default (UTC).

Not sure what the issue is...

**Comment by franck-boullier** [comment]
For the records: this might be a BZ issue though I don't understand why BZ display 07h55 in the first place... It should be 03h55 since the BZFE user is configured to use UTC (same as the BZ installation), there should be no conversion...

**Comment by franck-boullier** [comment]
More details about this
In latest verion of the PR31 the time zone are different on a mobile and on a desktop.

How to replicate the issue:
1- create a comment on FBO galaxy S8 (logged as FBO)
Result: time of the comment is 13h28 on the phone when the phone time is 17h28
2- check the comment on a browser 
Result time of the comment in the browser is 17h28 which is consistent with the time when the comment was made.

**Comment by nbiton** [comment]
Is it possible the phone is set manually to a different time zone?

**Comment by kaihendry** [comment]
Perhaps cook up a test page and print:

```
var offset = new Date().getTimezoneOffset();
console.log(offset);
```

**Comment by franck-boullier** [comment]
closing this issue for now as this does not seem to be a problem anymore
