### ISSUE TITLE
Check email is verified before sending notification emails to it

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#310]

**Comment by franck-boullier** [comment]
@kaihendry I seem to remember that we closed this one, can you confirm/close if appropriate?

**Comment by kaihendry** [comment]
I think @nbiton's code here does close this issue:
https://github.com/kaihendry/frontend/blob/f66e4f42373df558aba48ae577d178d45ec470b8/imports/api/rest/post-process-db-change-message.js#L100-L101
