### ISSUE TITLE
IE is not supported - Need to display a message to users

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#311]
If a user is using IE to access case.unee-t.com, the application can't work as expected
The login page looks like this
![image](https://user-images.githubusercontent.com/31331637/41827792-12e32c8a-7864-11e8-8ff0-f5e672451f66.png)
It is impossible to see the signup link which is white on white.

Since we do NOT plan to support IE we should let the IE users know that their browser is not supported and suggest that they use an alternative browser.

Below is an example of whatsappweb does it:
![image](https://user-images.githubusercontent.com/31331637/41827848-5c6ed6f6-7864-11e8-8827-b5a9192c2b4e.png)

**Comment by PicoCreator** [comment]
See : https://github.com/unee-t/frontend/pull/442#issuecomment-417394972

> IE 10, and 11 loads alright. Except 64bit IE 10 missing the logos
> 
> As for IE 9 and below, its a lost cause. So unless you plan to support warning those (hopefully not), you can consider this closed
