### ISSUE TITLE
MEFE User - We need to be able to disable a user

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#322]
In time, some user will stop being active. We need to be able to disable a user in the MEFE and make sure that this information is sent to the BZFE too.

This probably means that we need to add one element to the user collection in the Mongo database to record this.

**Comment by kaihendry** [comment]
Since the source of truth is the Mongo DB, we should be able to point to a schema of the User collection and how we define the user as being disabled. Guess we don't want to overload the **verified** attribute or do we?

**Comment by franck-boullier** [comment]
We now hav teh DE-ASSIGN API to do that
