### ISSUE TITLE
'List Cases Assigned to Me' - Pilot User feedback

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#325]
# The Problem:
Today a user can have several responsibility in a case:
- The reporter (I am the one who created the case)
- The Assignee (I am the one accountable to do something on this case)
- Invited (I need to know what's happening and I can see the case, interact, add comment, etc...)

Today the [default 'case' view](https://case.unee-t.com/case) shows the case where the logged in user is either:
- The reporter
- The assignee
- A user invited to this case

See the [design on Invision](https://projects.invisionapp.com/d/main#/console/12250377/299154525/preview) for more details.
![image](https://user-images.githubusercontent.com/31331637/41885804-1f8d6aae-792c-11e8-8826-9475db4f0efe.png)

As reported by several pilot users, it would be good to be able to have a view to "know about the cases that I need to take care of".
See the  ["Road Book" issue](https://unee-t.slack.com/archives/C9JKCF0KX/p1529547720000147) for more details.

# Suggested solution:
## Long term solution: 
We will have a workaround/fix when we implement the ['Filter case' functionality](https://projects.invisionapp.com/d/main#/console/12250377/280835805/preview).

## Short term fix:
Can we create a screen which would display only the list of cases that are assigned to me?

# Open Questions:
@kiatlim and @nbiton what do you think?
How would you tackle this?

**Comment by franck-boullier** [comment]
@kiatlim maybe we can add a tickbox "Assigned to Me" (Yes/No) which will toggle between the full list and only the list of cases assigned to me on the right side of the'4 Open 2 Closed' area?

**Comment by kiatlim** [comment]
@franck-boullier thats a possible quick fix, question is I would put this higher on the hierarchy below the title bar, otherwise the user has to click on the checkbox for multiple units.

**Comment by franck-boullier** [comment]
> I would put this higher on the hierarchy below the title bar, otherwise the user has to click on the checkbox for multiple units

Good point!

**Comment by franck-boullier** [comment]
> I would put this higher on the hierarchy below the title bar, otherwise the user has to click on the checkbox for multiple units

On second thoughts we can do this below the title bar (as for the Open/Closed toggle) and when this is selected, then the change is made for all the units (as it is done today for the Open/Closed toggle)...

**Comment by franck-boullier** [comment]
Latest design for this screen so we can allow a user to filer cases he/she is assigned to:
# Expected behavior:
This should work in tandem with the 'Open' / 'Closed 'option: user should be able to choose 'Assigned to me / Opened' and 'Assigned to Me / Closed'.
- First press on the 'Assigned to Me' button will:
  - Change 'Assigned to me' button to dark grey
  - Add a filter to display only the cases assigned to me

- A second press on 'Assigned to Me' button will:
  - Change 'Assigned to me' button back to light grey
  - Remove the filter on "only the cases assigned to me"

![image](https://user-images.githubusercontent.com/31331637/42143248-c381513e-7de6-11e8-93df-d671b3f4658f.png)

**Comment by sophieyang0813** [comment]
<img width="976" alt="screen shot 2018-07-04 at 5 11 38 pm" src="https://user-images.githubusercontent.com/25441733/42268250-9d43f4fe-7fad-11e8-95ba-beddbf7d0625.png">
Do we want a dropdown menu like this for assignee?  @kiatlim @franck-boullier 
credit to: @sebdeckers

**Comment by franck-boullier** [comment]
@sophieyang0813: we have a ['filter cases' screen in Invision](https://projects.invisionapp.com/d/main#/console/12250377/280835805/preview) that will be implemented at some stage:

![image](https://user-images.githubusercontent.com/31331637/42270460-849eea2a-7fb3-11e8-93da-1a9c5dd58a65.png)

**Comment by franck-boullier** [comment]
We have a solution for this issue ('List Cases Assigned to Me') in PR #356
