### ISSUE TITLE
Minor - Behavior when closing an attach preview is "scroll back to the top of the conversation"

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#33]
In the MEFE, when we tap on a attachment picture, the picture is shown in full screen (expected behavior).

When we tap on the 'back' arrow, the picture preview is closed and we are sent back to the top of the conversation, we have to scroll back to where the attachment was in the convo.

A better behavior would be:
When we tap on the 'back' arrow, the picture preview is closed and we are sent back to the place in the conversation where the attachment is.

**Comment by nbiton** [comment]
b01325e contains a change that makes the message list scroll down to the bottom after tapping the 'back' arrow on the attachment view

**Comment by franck-boullier** [comment]
tested and work as intended in PR31
