### ISSUE TITLE
CLOUDINARY key names

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#34]
We need to add to https://github.com/unee-t/bugzilla-customisation/blob/master/aws-env.dev#L1
the cloudinary keys.

We'll have different accounts for staging & production. Proposal:

* CLOUDINARY_ACCOUNT (can be public)
* CLOUDINARY_PRESET (probably should be secret)
* CLOUDINARY_ACCESS_KEY_ID (public)
* CLOUDINARY_SECRET_ACCESS_KEY (secret!)

**Comment by kaihendry** [comment]
CLOUDINARY_URL=https://api.cloudinary.com/v1_1/${CLOUDINARY_ACCOUNT}/image/upload

**Comment by franck-boullier** [comment]
Based on convo with @nbiton it seems we only need 2:
- CLOUDINARY_URL
- CLOUDINARY_PRESET

**Comment by franck-boullier** [comment]
OK those have been created.
