### ISSUE TITLE
Implement New Signup flow (with email verification step)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#343]
We need to implement the latest SignUp flow: This will make sure that:
- We have a valid email address for the new user
- A new user is not signed up 'Against his/her will'
- We have a proper 'Opt In' Mechanism for email notification -> less risk that the user will mark our email notification as spam + compliance with the recommended 'Opt In' practices including GDPR

@kaihendry can you take care of the 'email verification' routine: make sure we have the ablity to send and process email verification emails.

![image](https://user-images.githubusercontent.com/31331637/42142689-69650360-7de3-11e8-8ccd-d3eda29f4ed1.png)

**Comment by nbiton** [comment]
Just to make it clear: this should not require an external API to Meteor. Most of the needed operations are already available with Meteor's internal APIs

**Comment by kaihendry** [comment]
Ok, this is not the same as a new signup via an invitation https://github.com/unee-t/frontend/blob/master/imports/util/email-invite.js right?

Comments on this flow:
* why ask for name, locality, number & password? this will reduce signups
* verify email button should be one-click login, like the invitation? asking user to fill the password form results in friction and drop off
* similarly, like the invitation flow iirc, why not present a dialog to complete signup by putting name (and perhaps number/localilty) Btw with locality, this is possible to derive from IP address etc

Presenting the notification UI is probably a good idea but:
* is it clear how users can find that again?
* it's not clear to users what the utility of these messages are, so I am wondering what goes through people minds when they make this decision. Probably click through

**Comment by franck-boullier** [comment]
Updated flow to sign up via an invitation:
![image](https://user-images.githubusercontent.com/31331637/42143454-b3bc4046-7de7-11e8-914a-ccebc153f974.png)

**Comment by franck-boullier** [comment]
> Comments on this flow:

@kaihendry, probably best to discuss this directly with the UX/UI design team in the relevant slack channel or in the Realtime Board:
- RealtimeBoard and slack/design channel are the chosen communication tool to talk about design changes and suggestions.
- GH issues should only be dedicated to implementation/clarification on the chosen design IMO...

**Comment by michkwt** [comment]
New User Signup Flow
![unee-t user flow - self sign up](https://user-images.githubusercontent.com/38183796/42366800-bc0ccfa4-8134-11e8-95d8-8a80eeb70540.jpg)
https://invis.io/BYMNBFW76JC#/307228725_0-3-1_Launch_-_Reset_Password_Filled_Copy
Signup via Invitations
![unee-t user flow - new user through invitations](https://user-images.githubusercontent.com/38183796/42366817-c7d06832-8134-11e8-814f-5a7201d8d588.jpg)
https://invis.io/ESMNBMHQ3KA#/307228715_Case_Detail_Copy_19

**Comment by kaihendry** [comment]
Hi! Just coming back to this after a 2 week vacation. After staring at https://github.com/unee-t/frontend/issues/343#issuecomment-402958421

I have a couple of comments. First, thanks for putting the PNG in the Github issue comment. Handy. However I still wish that each mockup was a PNG so it is sane to reference. e.g.

1. new_sign_up/1_sign_up.png
2. new_sign_up/2_filled_form.png
3. new_sign_up/3_signed_in.png
4. new_sign_up/4_email_verify.png

I can give you AWS credentials to upload mockups to S3 @michkwt btw.

Since I can't reference the individual screen, I have to resort to taking screenshots.
E.g. https://s.natalian.org/2018-07-23/1532308695_2558x1406.png
* Why the First Name* ? It's inconsistent
* Do we allow the user to change his email address? This is a complex flow I'd rather avoid.
* What does the pencil next to the password mean?

Why a modal [here](https://s.natalian.org/2018-07-23/1532309107_2558x1406.png), but not [here](https://s.natalian.org/2018-07-23/1532309132_2558x1406.png). Again consistency please, since I personally dislike modals, I prefer [this option](https://s.natalian.org/2018-07-23/1532309132_2558x1406.png) & a well defined route, e.g. `/notification-settings`.

RE the **sign up via invitations** flow, the user gets the system prompt to enable notifications when exactly?
After a user posts a new message without "notify after each new message" enabled? Couldn't this be annoying?

**Comment by franck-boullier** [comment]
@Kaihendry.
You can find each individual screen and the links to them in invision

@Kiat maybe we can add the individual links to the GH issue so that it's faster to get to these?

**Comment by kiat** [comment]
@franck-boullier I do not know about your project.  You got the wrong account name?

**Comment by franck-boullier** [comment]
> @franck-boullier I do not know about your project. You got the wrong account name?

@kiat  ooops, sorry I had the wrong handle indeed I meant @kiatlim. Apologies 😊

**Comment by franck-boullier** [comment]
@kaihendry 
The links for each screens are:
- https://projects.invisionapp.com/d/main#/console/12250377/307228725/preview
- https://projects.invisionapp.com/d/main#/console/12250377/307228724/preview#project_console
- https://projects.invisionapp.com/d/main#/console/12250377/307228718/preview#project_console
- https://projects.invisionapp.com/d/main#/console/12250377/307228719/preview#project_console
- https://projects.invisionapp.com/d/main#/console/12250377/307228716/preview#project_console
- https://projects.invisionapp.com/d/main#/console/12250377/307228717/preview#project_console
- https://projects.invisionapp.com/d/main#/console/12250377/307228720/preview#project_console
- https://projects.invisionapp.com/d/main#/console/12250377/307228723/preview#project_console
- https://projects.invisionapp.com/d/main#/console/12250377/307228722/preview#project_console

**Comment by franck-boullier** [comment]
@kaihendry 

> Why the First Name* ? It's inconsistent

Good eyes!

> Do we allow the user to change his email address? This is a complex flow I'd rather avoid.

Probably not as part of the MVP but something that we will do at a later stage yes.
What we **might** have in the future is a distinction between:
- user login 
- user email 

So it is possible for a user to change his/her email address but keep his/her login credential.
Once again this is not part of the current scope to have the user change his/her email address 
BUT 
it IS in the current scope to allow an incorrect email address to be changed.
The scenario is as such
- an invitor invites another person
- the invitor makes a typo in the email address
- the email bounces back
- we need to alter the invitor and let him/her change the incorrect email address
We have this documented in a GH issue already if memory serves...

> What does the pencil next to the password mean?

"click here to change your password"

**Comment by kaihendry** [comment]
I'm a fan of keeping to email address, but there is a lot of debate about this topic on HN. Email is especially moot with some demographics who are unlikely to have email. However I would imagine all of our potential property managers have email, so we should keep to email.

Having a login and email opens up a world of confusion I'd rather avoid.

> "click here to change your password"

So inconsistent to how the other forms are edited?

**Comment by franck-boullier** [comment]
Update... At this point I think the only think left is 

![image](https://user-images.githubusercontent.com/31331637/44968922-2fa64a00-af7d-11e8-915c-612e2c4d5ad4.png)

**Comment by kaihendry** [comment]
Can we have a status update here? I am not sure if I am supposed to do the work or if @sophieyang0813 is, or even it has been done already. Perhaps we should leverage tasks lists and break this down a bit: https://help.github.com/articles/about-task-lists/

**Comment by sophieyang0813** [comment]
@kaihendry Good morning! I haven't worked on this. How would you like to break this down?

**Comment by kaihendry** [comment]
There is a email verification step now. Please re-open if I've mis-understood this one.
