### ISSUE TITLE
Unit make sure we can edit unit info

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#352]
We need to make sure that the Unit >> Overview screen allows a user to update a unit if needed (name, address, additional description, etc...)

**Comment by kiatlim** [comment]
@nbiton Is this what we are looking for?
https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=1441%3A3864

Except the edit mode of the unit overview i have 2 options:
Option 1: FAB edit > shows edit fields of unit overview, ability to invite user/remove user, disable unit etc

Option 2: FAB edit > only allows users to edit the unit overview information

In both cases, the DONE action is at the top right. Do you have Edit cases on your end?

**Comment by franck-boullier** [comment]
> In both cases, the DONE action is at the top right

I'm not too convinced by this option: in other places in the UI the confirm/done/send button is at the bottom of the screen. Shouldn't we be more consistent on that?

**Comment by franck-boullier** [comment]
> Option 2: FAB edit > only allows users to edit the unit overview information

We will roll this out first until we have the "invite/edit users for the unit" part working.

> Option 1: FAB edit > shows edit fields of unit overview, ability to invite user/remove user, disable unit etc

This is the "end state" as of today and what we want to implement eventually

**Comment by lironz** [comment]
what about a scenario in which the user started editing unit fields and navigated away before "Done" is pressed?

should we pop a dialog for "save/discard" before leaving editable mode?

**Comment by franck-boullier** [comment]
> should we pop a dialog for "save/discard" before leaving editable mode?

This looks like a great idea to me yes👍
@kiatlim do you see any issue with that?

**Comment by ongdominic** [comment]
yes i think we can pop a dialog just like in the design for the edit inventory screens. Would a similar screen work for you?

**Comment by ongdominic** [comment]
This is the link that I am referring to  for the pop up. https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=1631%3A208

**Comment by ongdominic** [comment]
@kaihendry based on the comments on the video do we want to implement a site/app-wide rule to auto save any changes or would a save button still be needed?

**Comment by franck-boullier** [comment]
> would a save button still be needed?

Yes save button is needed for a few reasons: 

- As @kaihendry pointed out in one of his video: "how do I know if this has been saved or not?" ---> we need a save button.
- If we save "on the fly" we sometime trigger unnecessary action assuming the user is done with editing when the user is actually NOT done editing ---> we need a save button.

**Comment by franck-boullier** [comment]
> do we want to implement a site/app-wide rule to auto save any changes

This has already been discussed at lenght and we have decided that we do NOT want to have a site/app-wide rule to auto save any changes (see my previous comment on some of the reasons for that).

**Comment by franck-boullier** [comment]
> is the "done" button at the top-right corner is final?

IMO and for consistency reasons, the "Done" button should be at the bottom of the screen (always visible) @ongdominic any recommendation?

**Comment by franck-boullier** [comment]
> 2nd is under the overview tab, 3rd has it's own page, which one are we going for?

To me:
1- 2nd is the future version of 3rd. We do 3rd first because the functionalities are not ready to do 3rd (invite user to a role in a unit is not functional yet)
2- When the user presses the "Edit" icon (the pencil) user should be sent to a dedicate page for editing (no tabs in the context of editing something)

@ongdominic feel free to add/comment/recommend better option

**Comment by ongdominic** [comment]
instead of the word "Done", I would rather use "Save". It is to make it even clearer. but yes for consistency, for every edit mode the save button will be at the top right-hand corner. and users who press back will get the prompt to save their work before they exit. I am actually in the midst of reviewing every edit and create flow after our conversation yesterday.

**Comment by ongdominic** [comment]
For option 2 I might even change the header to "Edit Overview"

**Comment by ongdominic** [comment]
<img width="375" alt="unit - edit unit details - option 2" src="https://user-images.githubusercontent.com/46714451/51662762-d607f000-1fef-11e9-99ad-ef0c5ead6803.png">

**Comment by franck-boullier** [comment]
"Save" should not be at the top right (consistency)
It should be docked at the bottom of the screen (always visible) IMO

**Comment by nbiton** [comment]
As we've reviewed in other apps yesterday (mostly Facebook)- the "Save" button can be both above in the top right corner and sticky at the bottom, so the user can always easily locate it

**Comment by ongdominic** [comment]
so i would standardise the 2 different type of flows:
1. for edit and saving, it will always be at the top right. 
2. for new cases or adding of new items, the button would be sticky at the bottom

**Comment by nbiton** [comment]
@ongdominic I understand from your latest screenshot that the desired behavior after clicking the "Edit" button, is to edit the unit's details in a different context/view that does not contain the tabs. Is that correct?

**Comment by ongdominic** [comment]
yup that is correct.
