### ISSUE TITLE
Handle scenario when user clicks on 'Reply to' when notification email is received

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#354]
# The problem:
Today we send email notification to a user there are certain user that will directly click on "reply to" on their email client.

The user then assumes that his/her email reply has been included in the case -> this is not the case.
As of today, these email replies are lot to Unee-T

For an example of that see [this support case](https://secure.helpscout.net/conversation/613322168/157/?folderId=2155399).

# Long term solution:
Add capability for the user to add a comment to a case by simply replying to the email notification

# Short term fix:
Suggestions/recommendations are welcome!

**Comment by kaihendry** [comment]
Been thinking how to do this, and we could leverage AWS SES Email Receiving on case@unee-t.com, that would in turn trigger a lambda function that we could insert the email body into the relevant case number.

However the main issue with that is that we would need to put some sort of secret in the email so we identify the sender. Github does this be setting the Reply-To to something like:

`reply+000bafaf5487d560ccf516f2e862ca16f5f466499e59a1a292cf001000011753eab292a169ce13e82266@reply.github.com`

And then I am sure they check that hash against some table and if all checks out, it gets popped into the right issue.

**Comment by franck-boullier** [comment]
> we would need to put some sort of secret in the email so we identify the sender

@kaihendry I think you are absolutely right
We should also be able to differentiate replies to the initial email sent and only accept these as valid.
We should reject any input coming from:
- a reply to the reply
or 
- from a email coming from someone who has received the notification via an email forward'

Tricky I know but as you mentioned, possible: many people out there are doing it

**Comment by franck-boullier** [comment]
@kaihendry any idea when we could implement that?
We notice that there are several users who are replying to the notification email and this would be a nice feature.

Apparently the standard way to do this is to have a disclaimer like

##- Please type your reply above this line -##

Then we should probably use some sort of unique Id to make sure the reply is legit and sanitize the input too in order to accept the reply 

What are your thoughts?

**Comment by kaihendry** [comment]
I can spend time working on it. I don't think it will be easy.

Perhaps a better approach would be to modify our templates to more clearly state in order to reply, you need to go to the case id? At least in the interim.

`##- Please type your reply upon https://case.dev.unee-t.com/case/61937 -##`

**Comment by franck-boullier** [comment]
> I can spend time working on it.

Thanks, that'll be good. It's a very important feature (some pilot users have already requested this BTW)

> modify our templates to more clearly state in order to reply, you need to go to the case id? At least in the interim.

We will do that as a stopgap in the interim but the reality is that this is a needed feature to make Unee-T as straightforward to use as possible

**Comment by kaihendry** [comment]
foobar

**Comment by kaihendry** [comment]
foobar Wed Sep 12 16:21:49 +08 2018

**Comment by kaihendry** [comment]
Have a prototype working:
https://media.dev.unee-t.com/2018-09-14/email2case.mp4

Incoming emails are checked by:
* a specially generated reply to address which is signed by the API_ACCESS_TOKEN shared secret
* makes the Bugzilla comment after looking up the API key of the user from user_api_keys table

https://github.com/unee-t/email2case is the source of the lambda.

https://github.com/unee-t/email2case/blob/master/tests/hmac/index.js now needs to integrated to the reply-to of the notifications... https://github.com/unee-t/frontend/blob/master/imports/api/rest/post-process-db-change-message.js

**Comment by nbiton** [comment]
> https://github.com/unee-t/email2case/blob/master/tests/hmac/index.js

@kaihendry so exactly the same function needs to be implemented in unee-t/frontend so it used to fill the "reply-to" of the emails sent to users?

**Comment by kaihendry** [comment]
This is blocked by https://github.com/unee-t/frontend/issues/520

**Comment by nbiton** [comment]
Why is this blocked by #520? It's already implemented on the MEFE side

**Comment by franck-boullier** [comment]
# The test:

In the [DEV environment on case id 62323](https://case.dev.unee-t.com/case/62323):
- create a case as user 1
- Invite franck to the case
- Franck accepts the invitation and logs in for the first time
- user 1 adds one more comment
- Franck receives an email notification about the new comment
- Franck replies to the email

## Expected result:

- Email reply is added as an additional comment to the case

## Actual result:

- After 10mn the update done via the email is still not visible in the case

**Comment by kaihendry** [comment]
Please look at the logs:
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/lambda/email2case_ses;stream=2018/09/26/[$LATEST]b5e8f0facfbb484ba577deec633287d0;start=2018-09-25T03:27:56Z

You are not authorized to access case #62323

Did you reply from the same email address that has access to the case?

**Comment by franck-boullier** [comment]
# The test:

In the [DEV environment on case id 62323](https://case.dev.unee-t.com/case/62323):
- create a case as user 1
- Invite franck to the case (make sure to use an email address that can reply to the email)
- Franck accepts the invitation and logs in for the first time
- user 1 adds one more comment
- Franck receives an email notification about the new comment
- Franck replies to the email
- Email reply is added as an additional comment to the case - PASSED

All works as intended 🎉 
Well done!

**Comment by kaihendry** [comment]
This is done https://github.com/unee-t/email2case

Some things to think about going into the future:
* handling attachments
* handling HTML since right now we rely on a text counterpart
* documenting a process of removing a comment, since it might be an error
