### ISSUE TITLE
Get users' acceptance to TOS and record information for each related item

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#359]
Implement according to the UI on RealltimeBoard and record the following items for each user.

# User acceptance of our Terms and Conditions:
This is needed so that we are compliant with the various laws and regulation we are subject to:

## Terms and conditions:
- Date and time when the user as accepted our terms and conditions
- How did the user accepted our terms on condition (ex: click on 'accept button' on [URL of the page])
- Version of the Terms and conditions that the user accepted.

### Opt-in:
- Date and time when the user as Opted in
- How did the user accepted (ex: click on 'accept button' on [URL of the page])

### Unsubscribe:
- Date and time when the user asked to unsubscribe from receiving emails
- How did the user chose to unsubscribe (ex: email sent to 'unsubscribe list')

## Agreement to let us use Cookies:
- Date and time when the user as accepted our cookies policy
- How did the user accepted (ex: click on 'accept button' on [URL of the page])
- Version of the Terms and conditions that the user accepted.

## Privacy Policy:
- Date and time when the user as accepted our Privacy Policy
- How did the user accepted (ex: click on 'accept button' on [URL of the page])
- Version of the Terms and conditions that the user accepted.

## Acceptable use policy:
- Date and time when the user as accepted our Acceptable Use Policy
- How did the user accepted (ex: click on 'accept button' on [URL of the page])
- Version of the Terms and conditions that the user accepted.

**Comment by franck-boullier** [comment]
this is needed so we can do #343

**Comment by franck-boullier** [comment]
this is WIP in PR #374

**Comment by franck-boullier** [comment]
Fixed in the current master
