### ISSUE TITLE
User confused by the 'Add unit' Interface - Need to dock the 'Add Unit' button - Pilot User Feedback

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#365]
# The problem:

Feedback from a user: "The Add Unit functionality does not work"

# What happened:

![image](https://user-images.githubusercontent.com/31331637/42366115-f3e75f04-8132-11e8-8833-c44c162dfb9f.png)

# Next Step:

@kiatlim can you try to think of a way to improve the UI so we can avoid this misunderstanding in the future?

**Comment by franck-boullier** [comment]
@kiatlim , maybe replacing the text 'Add Unit' at the top with 'Enter the unit details' will be good enough :thinking: ?

**Comment by kiatlim** [comment]
Yes, changing the title will be good enough. Additional things we can do is to add a tick icon on the top right, user can press on that to complete adding unit.

A subtitle one is changing the background of the title vs buttons so it’s more differentiated.

**Comment by franck-boullier** [comment]
@nbiton where in the MEFE code can I change this text?
![image](https://user-images.githubusercontent.com/31331637/42368385-7a6a8c4e-8139-11e8-919d-ddc926d98ac9.png)

But do NOT change the button title:
![image](https://user-images.githubusercontent.com/31331637/42368453-a528de72-8139-11e8-8bda-01ae6156ff7e.png)

In the MEFE the text 'Add Unit' appears
here (which I guess is probably the correct one): 
https://github.com/unee-t/frontend/blob/58a702521b8e71938feaa4aa162541237ce4cb47/imports/ui/unit-explorer/unit-explorer.jsx#L49
and here (not my first choice):
https://github.com/unee-t/frontend/blob/eb9a94d9f208c0215cac16691e37495b465cd0a2/imports/ui/unit-wizard/unit-wizard.jsx#L200

**Comment by michkwt** [comment]
![screen shot 2018-07-06 at 4 27 37 pm](https://user-images.githubusercontent.com/38183796/42368418-8d561e5e-8139-11e8-930d-3d9beae10731.png)
@franck-boullier Is this clearer?

**Comment by franck-boullier** [comment]
> Is this clearer?

I would completely remove 'Add Unit' from the top bar and replace with 'Enter Unit Details' instead.
Any concerns with that?

**Comment by franck-boullier** [comment]
Maybe we can also dock the 'Add Unit' button at the bottom of the screen so it is always visible: today a user has to scroll down to see this

**Comment by michkwt** [comment]
![screen shot 2018-07-06 at 4 44 02 pm](https://user-images.githubusercontent.com/38183796/42369210-dca4b400-813b-11e8-9db9-ac18779824a1.png)
Nope. it's just difference with the wording. you're right it would be clearer if it is Enter Unit Details.

**Comment by kiatlim** [comment]
@franck-boullier @nbiton yes docking the button at the bottom as a sticky footer would be preferred so the user sees it instead of scrolling below to see the button.

**Comment by franck-boullier** [comment]
Partial fix has been implemented in PR #366 

Next step is to dock the button at the bottom as a sticky footer

**Comment by franck-boullier** [comment]
fixed with PR #366

**Comment by franck-boullier** [comment]
# The problem:

Despite the improved text on top of the screen, user are still confused about what needs to be done.

We need to implement the recommended solution: dock the 'Add Unit' button at the bottom of the screen so it is always visible: today a user has to scroll down to see this button and many user are NOT saving their unit because of that issue.

**Comment by franck-boullier** [comment]
> I change this to non-transparent grey color?

@michkwt not sure why we'd need to change the color: can you clarify your reasoning for changing this?

The recommended fix is to make sure the button is always visible (docked) so that there is no confusion in the user's mind about what he/she needs to do to save/create/add a new unit

**Comment by sophieyang0813** [comment]
@franck-boullier the color suggestion was due to `Administrative Region` almost overlapping with `Add Unit`. Another suggestion made in slack was docking (+) round button that you liked at the bottom right position. I can easily implement either button. 😄😄 Currently,  I am working on requested changes in #396
