### ISSUE TITLE
'New message' and 'Case updated' email notifications are not routed to the proper users

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#376]
Any user gets notified when he himself created a message on a case

**Comment by franck-boullier** [comment]
That's an issue indeed: expected behavior was the for each notification, the user who initiated the change would be excluded from that notification...

**Comment by nbiton** [comment]
Renaming "Users get notified by email when they create a message" => "'New message' email notification 
 is not routed to the proper users" as I see that the case's reporter won't get any notifications...

**Comment by nbiton** [comment]
Same goes for notifications of type "case updated"

**Comment by franck-boullier** [comment]
fixed in latest PR
