### ISSUE TITLE
Display version on https://dev.case.unee-t.com/

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#38]
Using the COMMIT variable, which is the short hash of the git repo revision its on.

https://github.com/kaihendry/frontend/commit/3290af3b12052ce1ba925df44cba82630e69ef47

**Comment by nbiton** [comment]
Some basic design idea should be provided if this would be done externally

**Comment by kaihendry** [comment]
Can it at least be embedded in HEAD?

**Comment by nbiton** [comment]
Yeah, good idea :)
