### ISSUE TITLE
'Add Unit' Button is just over the 'Add case' button ---> impossible to click 'Add case'

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#386]
# The problem:

On the 'Unit page', in some cases, the 'Add Unit' (the '+' sign) button is right over the 'Add case' button. If the list is not long enough, you don't have the possibility to scroll down ---> it is not possible to click on the 'Add Case' link.

![image](https://user-images.githubusercontent.com/31331637/42719154-06fe1986-8744-11e8-870e-93f3ceec54ee.png)

**Comment by nbiton** [comment]
Add bottom padding to each scroll container when a FAB is over it

**Comment by sophieyang0813** [comment]
@nbiton Afternoon!  

> "Add bottom padding to each scroll container when a FAB is over it"

Could you clarify scroll container for me? Does adding refs makes div a scroll container? Scrollheight property was accessible after adding ref to `<div className=overflow-auto>`. But I was not sure how to indicate that FAB was overlapping with a specific unit though.  
 
specific unit container = scroll container? 
<img width="330" alt="screen shot 2018-08-27 at 5 08 59 pm" src="https://user-images.githubusercontent.com/25441733/44651424-f1a8a380-aa1b-11e8-8cd8-d4808ad2eefe.png">
 
A temporary solution? (adding padding top to each unit..😅😅??) 
<img width="326" alt="screen shot 2018-08-27 at 5 26 58 pm" src="https://user-images.githubusercontent.com/25441733/44652481-8f04d700-aa1e-11e8-8669-69dd967e2c61.png">

Thank you!

**Comment by nbiton** [comment]
Hey @sophieyang0813 ! By scroll container, I meant the `<div />` that has `overflow-auto` in its "className" attribute

**Comment by sophieyang0813** [comment]
@nbiton understood! Do I use refs (scrollHeight) to figure out when FAB hovers the container? or did you have another approach in mind?  Sorry, it might be an obvious question... 😅😅 but I was confused for past couple hours.
