### ISSUE TITLE
Create unit - Scrolling the whole all country list is painful - pilot user feedback

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#387]
# The problem:

When  a user creates a unit, he has the option to add the unit address.
The UI to select the country is a drop down list.
This is extremely painful to scroll.

![image](https://user-images.githubusercontent.com/31331637/42719282-a4b1e256-8745-11e8-875f-d42c7e04b705.png)

# Possible solutions:

- Replace the drop down with a data entry fiedl ---> user starts typing the country and we narrow the list down. @kiatlim any recommendation there?
- Once the user has completed his/her profile and added a country, pre-populate the 'country' information for the unit with the 'country' information from the user profile. USer will still have the possiblility to change the country of the unit

**Comment by franck-boullier** [comment]
Moving this up in the list of UI improvement: 100% of the user I talked to are telling me that this is a problem for them

**Comment by kiatlim** [comment]
@franck-boullier @nbiton a search and list component is suggested e.g. https://js.devexpress.com/Demos/WidgetsGallery/Demo/List/ListWithSearchBar/Angular/Light/

![](https://i.stack.imgur.com/w1PLF.gif)

**Comment by franck-boullier** [comment]
This is fixed in PR #411

**Comment by kaihendry** [comment]
The canonical name of what you are looking for is a **[datalist](https://html.spec.whatwg.org/multipage/form-elements.html#the-datalist-element)**.

* https://leaverou.github.io/awesomplete/
* https://www.youtube.com/watch?v=LpgddDKoR_8

There is also a bunch of ways to fairly straightforward ways detect the country the user is in. Actually AWS supply a header, [Cloudfront-Viewer-Country](https://aws.amazon.com/blogs/aws/enhanced-cloudfront-customization/) if we used CloudFront.

**Comment by franck-boullier** [comment]
> There is also a bunch of ways to fairly straightforward ways detect the country the user is in. Actually AWS supply a header, Cloudfront-Viewer-Country if we used CloudFront.

Good idea ---> @kaihendry can you create a separate issue for this (enhancement).
That way we'll have it in the to do list and we'll see how we can implement that when all the other more pressing issue are taken care of
