### ISSUE TITLE
Simplify Case creation - Remove Priority and Severity - Pilot user feedback

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#388]
# The problem:

We want to make it as simple, fast and easy as possible for users to create cases.
Today some pilot users are confused with the "Priority" and "Severity" fields on the 'Add Case' screen: they do not understand why this is needed.

Pilot user have a tendancy to inflate the criticity of a problem (everything is always Urgent) which makes this field less effective.

# Solution:

"Priority" and "Severity" are advanced tags that can be set by the user at a later stage.
We should:
- Set the "Priority" and "Severity" field to their default value at case creation
- Remove the "Priority" and "Severity" fields from the 'Add Case' interface
- Only have the interface to update these fileds in the 'More information' screen for a case

![image](https://user-images.githubusercontent.com/31331637/42719459-345bfce6-8748-11e8-9665-74ca96648ec1.png)

**Comment by sophieyang0813** [comment]
@franck-boullier What are default values for Priority and Severity? Do we want to indicate in case creation page that these values can be updated at More Information page?

**Comment by franck-boullier** [comment]
> What are default values for Priority and Severity?

Priority: `P3`
Severity: `normal`

> Do we want to indicate in case creation page that these values can be updated at More Information page?

No but I'm not sure I understand the question  ---> how would you do that since this line (the line where priority and severity is)  is supposed to be removed entirely so we can simplify the interface 🤔 ?

**Comment by nbiton** [comment]
Is adding "priority" and "severity" setting option to "Case- More information" a part of the desired solution to this issue?

Since it will be more complex for @sophieyang0813 to implement, I suggest we create a different issue for that.

**Comment by franck-boullier** [comment]
> Is adding "priority" and "severity" setting option to "Case- More information" a part of the desired solution to this issue?

No, adding "priority" and "severity" setting option to "Case- More information" is NOT a part of the desired solution to this issue.

We should create a separate issue to add "priority" and "severity" setting option to "Case- More information"

**Comment by sophieyang0813** [comment]
@nbiton @franck-boullier oh, understood.  I was working on implementing to add 'priority' and 'severity' given  
>"Only have the interface to update these fileds in the 'More information' screen for a case" 

This addresses all my confusion! The question I asked was relating to that implementation. 
> "No but I'm not sure I understand the question"

**Comment by franck-boullier** [comment]
fixed in current version of the master
