### ISSUE TITLE
Message posted by user are not displayed correctly

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#389]
# The problem:

In the latest version of the master.
I tried to post a message as Leonel

## Expected result:
The message is displayed on the right of the screen and with a green background

## Actual result:
The message was posted 
BUT
The message was displayed as if posted by another user (left of screen and white background

![image](https://user-images.githubusercontent.com/31331637/42730182-d90d33d0-8820-11e8-8307-8b46d927ed77.png)

**Comment by nbiton** [comment]
I need to look into it, but it's very likely that it's due to mismatch between the 'bugzillaCreds.login' for this user in mongo and the actual email login name in BZ

**Comment by franck-boullier** [comment]
> I can fix it

I'd like that 👍

**Comment by nbiton** [comment]
Closing as the related PR has been tested and merged
