### ISSUE TITLE
Unit name is incorrect in the Case view

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#394]
# The problem:

On the 'Case page, the Unit name for a new unit still has the "-xxx" part --->  this is a sign that the unit name is coming from the BZ Database and not from the Mongo database

![image](https://user-images.githubusercontent.com/31331637/42753261-ea058cac-8922-11e8-8fa2-bc08e3d7e34a.png)

Notice how the name of the newly created unit has the BZ id appended at the end (
![image](https://user-images.githubusercontent.com/31331637/42753112-70e798f6-8922-11e8-913e-7610c802a949.png)

The Unit name should come from the MEFE (same as on the 'Unit' Page)
![image](https://user-images.githubusercontent.com/31331637/42753219-c3ff8224-8922-11e8-8b4f-8e7edc2644f8.png)

**Comment by franck-boullier** [comment]
this will become important as we will soon be able to update the unit in the MEFE interface.
If this is not fixed, updates in the MEFE will never be visible (source of the field today is coming from the BZ side).
Keep in mind that the source of truth for unit information is a the MEFE (NOT the BZ db)

**Comment by PicoCreator** [comment]
Note : This issue seems to be resolved in the latest dev build - will indicate once again when it moves to demo

**Comment by PicoCreator** [comment]
Nope, unfortunately further testing on 30th shows that its back =|
