### ISSUE TITLE
Differentiate participants in a case with different colors

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#40]
Each participant's avatar and name should be assigned a color that remains unique in the context of the current case. This should match these designs:
https://projects.invisionapp.com/d/#/console/12250377/266322188/preview
https://projects.invisionapp.com/d/#/console/12250377/266321280/preview#project_console

**Comment by franck-boullier** [comment]
This works well in PR41.
See issue #49 for a suggestion of how to use the color code for user based on their role in the unit (tenant, landlord, etc...)
