### ISSUE TITLE
MEFE invitation id partially processed - Pilot user

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#400]
# The problem:

An existing user is invited to a case in an existing unit.
The invited user did not received the email notification that he/she has been invited to the case.

I checked the BZ log and it seems that the MEFE inviation id: uZzQY5bpbxfiKyMsW was not fully processed:
- User was invited to the case and has a role for that unit.
- The API call to send the email seems to have failed for some reason...

**Comment by nbiton** [comment]
I checked the logs:
* This error was logged by MEFE: `[TypeError: Cannot read property '0' of undefined]`
* Shortly after, this error was received from the lambda: `{ [Error: failed [500] 1 error occurred: * uZzQY5bpbxfiKyMsW strconv.Atoi: parsing "{}": invalid syntax ]`

I need to look into this a bit more to see what caused it. My current guess is malformed BZ data.

**Comment by nbiton** [comment]
Closing this while skimming through the issues. It seems we'll never know at this point what caused this, and it might've been fixed anyway
