### ISSUE TITLE
Notification not appearing in the UI

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#401]
# The problem:

A case is updated:
- A comment is added
- The status of the case is changed to RESOLVED (Closed)

## Expected result:
For users who have been invited to that case:
-  Notifications in the UI for that case: a new message has been added
-  Notifications in the UI for that case: the status of the case has changed
- The case disappears from the list of Open cases
- The case appears in the list of Closed case

## Actual Result:
For users who have been invited to that case:
-  Notifications in the UI for that case: a new message has been added: FAILED
-  Notifications in the UI for that case: the status of the case has changed: FAILED
- The case disappears from the list of Open cases PASSED
- The case appears in the list of Closed case PASSED

**Comment by nbiton** [comment]
I tried to recreate the same scenario as described, but I got the expected result:
![screenshot from 2018-07-19 14-00-25](https://user-images.githubusercontent.com/2662819/42924317-310d372c-8b5c-11e8-882c-dc61161c63e1.png)

I'll need more details to figure out what went wrong in your test

**Comment by franck-boullier** [comment]
> I'll need more details to figure out what went wrong in your test

@nbiton I don't really know what to add 🤔...
I'll try to see if I can replicate that again

**Comment by franck-boullier** [comment]
I have been unable to replicate this again.
I'm closing this issue for now.
We will reopen it if needed
