### ISSUE TITLE
Warn user has not verified their email

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#407]
What is should be https://projects.invisionapp.com/d/main#/console/12250377/307228718/preview#project_console

Currently upon registering it looks like /unit

Part of #343

**Comment by kaihendry** [comment]
@nbiton might need your help to implement this https://media.dev.unee-t.com/2018-07-23/nesting.mp4

**Comment by kaihendry** [comment]
Discussing what UI component and where this warning goes on Slack https://unee-t.slack.com/archives/C76A4FZK9/p1532334769000284

**Comment by franck-boullier** [comment]
This is currently in PROD
