### ISSUE TITLE
PDF snapshots of inspection reports

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#412]
IIUC we need to make snapshots of the state of a unit.

I created a video https://media.dev.unee-t.com/2018-07-25/pdf-generation.mp4 which outlines how I think this feature will be generated using [Wikipedia's](https://en.wikipedia.org/wiki/Durban) **Download as PDF** feature as an example.

It differs here in the sense we store & display previous snapshots IIUC. Some things to think about:
1. can i assume the inspection report will be a static HTML page I can convert into PDF? If it's a heavy JS / react app, this might be very tricky.
2. do we generate snapshots at will? only when the report is signed off? when exactly?
3. can snapshots be deleted?
4. can reports be shared on a public URL (i.e. stored on s3 like the video above), with a secret hash?? If no, then Download only is fine, e.g. `2017-07-20-Unit-foobar.pdf`

If we want to chat about diffs between PDF snapshots, I think we should create a new issue.

**Comment by kaihendry** [comment]
On topic of 4, noticed that a sharing via email mechanism has already been defined here https://projects.invisionapp.com/d/main#/console/12250377/300869273/preview

Tbh I'd rather have users download the PDF and send it via whatever themselves. What happens if the PDF is shared accidentally >1 ? All this extra logic would need to be implemented.

**Comment by franck-boullier** [comment]
To answer a few of @kaihendry's question from the video: 
- Inspection report are exported to pdf when one of these happens:
  - an IR is finalized. When the inspection report is finalized, a pdf is generated from the collection of BZ bugs that we have created during the inspection report generation process and stored as an inspection report. If the user present have endorsed the report, signatures are included in the pdf. 
  - a user request to create a pdef export of the IR report now to have a snapshot of the current status of each of the bugs that are part of the IR. In that scenario, the IR is no "endorsed" (there is no signature in the pdf export).
- "diffing" is NOT part of the scope
- There is no "auto generation" of inspection reports (see above and see the RTB: we ALWAYS need a user action to generate a pdf export.

**Comment by franck-boullier** [comment]
> What happens if the PDF is shared accidentally >1 ?

I don't see how this could be an issue

**Comment by franck-boullier** [comment]
> can i assume the inspection report will be a static HTML page I can convert into PDF? If it's a heavy JS / react app, this might be very tricky.

This is a question for @nbiton

**Comment by franck-boullier** [comment]
> can snapshots be deleted?

No (this might change at a lateer stage but this will be complex to implement ---> this is NOT part of this issue)

**Comment by franck-boullier** [comment]
> can reports be shared on a public URL (i.e. stored on s3 like the video above), with a secret hash?? If no, then Download only is fine, e.g. 2017-07-20-Unit-foobar.pdf

I'm tempted to say: lat's go with the simple option of download only for now.
For most of the users we are targeting link sharing is way too complex and most certainly overkill

**Comment by nbiton** [comment]
> can i assume the inspection report will be a static HTML page I can convert into PDF? If it's a heavy JS / react app, this might be very tricky.

We can have all the rendering done server side like we do with email templates, and serve it on a non-app server endpoint. I don't see a problem with that if it makes the PDF generation on the backend easier

**Comment by franck-boullier** [comment]
Additional information/scope: when a IR is shared as pdf with other user, the email notification should also include the pdf as an attachment too and NOT as a link.
This is so that the user can save the pdf in one click as opposed to follow a link to open the pdf and save the document.

**Comment by nbiton** [comment]
@franck-boullier Is it correct to assume that a snapshot is basically the inspection report and all its dependent cases (of various sub-types) when it was finalized? So all of these entities can't be modified after finalization (they're a snapshot), only duplicated to a new "draft" that represents the updated report in current time (until that is finalized too and becomes a snapshor)?

**Comment by franck-boullier** [comment]
> Is it correct to assume that a snapshot is basically the inspection report and all its dependent cases (of various sub-types) when it was finalized?

yes it is correct

> So all of these entities can't be modified after finalization

No: the bugs can be modified after finalization (and it is expected that they will be) BUT the pdf will NOT change ---> we have to store the PDF somewhere when it's generated and display this file if this version of the IR is requested at a later stage

**Comment by franck-boullier** [comment]
Duplication of an IR is needed for another scenario: "I want to do an IR in that unit again but I don't want to re-create all the rooms and/or all the items again"

**Comment by kaihendry** [comment]
I came up with a rough prototype here: https://github.com/unee-t/wetsignaturetopdfprototype

* wet signatures via canvas https://github.com/szimek/signature_pad seems to work well enough
* pdf generation currently with https://pdf.cool/ also works well enough to proceed

Closing in favour of more focused https://github.com/unee-t/frontend/issues/427
