### ISSUE TITLE
When a unit is disabled, replace the 'Add Case' link with 'Disabled Unit'

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#418]
# The Problem:
When a unit is disabled, it is not possible to create new cases for that unit BUT existing cases are still visible in the 'Case' view.

We want to add a message/visual cue in the Case view to explain why the "Add Case" button is not available for some units (why it's not possible to add a case to these units).

# Suggested Solution:

![image](https://user-images.githubusercontent.com/31331637/43350149-a1e3d1c2-9237-11e8-9104-b3a893a45f57.png)

@kiatlim if there is no issue with this suggetion, can you make sure that the design is updated in the RTM and also in Invision?
Thanks

# Background information:

We already touched upon this suggestion the conversation for PR #396 See @sophieyang0813 's comment about the current code:

----
Case view(case-explorer.jsx) and unit view (unit-explorer.jsx) are in different files, so I naturally thought this is a separate issue. For what I skimmed, case view and unit view have different 'add case' button displaying logic. One in unit view is displayed when current user id matches with metadata.ownerid, while one in case view is displayed with bzId(?). It can be a minor issue but it might not be an issue that can be fixed in 10 min.

@nbiton do we update the case view add button with unit view display logic (i.e. do I add same metadata to UnitMetaData in cases.jsx)? If yes, do I replace or keep bzId?

```
 {bzId && (
  <div className='no-shrink flex items-center'>
    <Link
      className='f6 link ellipsis ml3 pl1 mv1 bondi-blue fw5'
      to={`/case/new?unit=${bzId}`}>
      Add case
    </Link>
  </div>
)}
```
----

**Comment by franck-boullier** [comment]
Design has been agreed (see above)
OK to implement
@kiatlim and @michkwt can you please add the figma link to the mockup is added to this GH issue so we can implement the design faster

**Comment by michkwt** [comment]
@franck-boullier 
Design updated. 
https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=0%3A6252

**Comment by sophieyang0813** [comment]
@kiatlim @michkwt @franck-boullier
Good morning! my user intuition tells me that button(disabled) looks more clickable than link (add case). Also, having link and button seems inconsistent to me. What do you think about bondi-blue button for `add case` and grey button for `disabled` ? I am happy to implement the current design and also thought I would share my two cents ...🌻🌻

**Comment by franck-boullier** [comment]
> What do you think about bondi-blue button for `add case` and grey button for `disabled` ? 

That sounds like a vert good idea to me yes!
@sophieyang0813 you should work on that idea IMO unless @kiatlim sees a big issue with that
