### ISSUE TITLE
PR#41 The case page is not loading

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#42]
In the Heroku version of PR41 I am able to log in as franck.boullier

When I try to go to a specific case (case 12345) the page is ever loading.
This error appears on 
- FF 57.0.2 (64bits) on a W10 destop
- Chrome on Android (Galaxy S8)

**Comment by franck-boullier** [comment]
The error is also present on https://dev.case.unee-t.com/case/12345 (page never loads)

**Comment by kaihendry** [comment]
What login am I supposed to use again on staging? https://dev.case.unee-t.com/

Or I should create one anew?

**Comment by franck-boullier** [comment]
@kaihendry probably best if you can create a new login on staging.
If you have issue with that let me know and I'll create one for you.

**Comment by kaihendry** [comment]
Do we have an issue tracking this "steps to test on staging" process? This needs to be _very smooth_ else I might lose my mind.

This might be already https://github.com/unee-t/frontend/issues/14 or shall I create a new issue?

**Comment by franck-boullier** [comment]
@kaihendry probably best to create a dedicated issue...

**Comment by franck-boullier** [comment]
I guess we need to add some test profiles in the dev.dashboard.unee-t.com envo so we can play around...

**Comment by nbiton** [comment]
@kaihendry normally, there wouldn't be any additional steps to make after deployment. The BUGZILLA_ADMIN_KEY should remain the same, unless otherwise revoked.
The only part that needs to be resolved is the "user journey" for the tester to access a case and test, if one doesn't have an existing user with access to that case. That might deserve an issue of its own

**Comment by kaihendry** [comment]
Previously test profiles were setup here: https://github.com/unee-t/bugzilla-customisation#login-info-set-by-sqldemosqlgz If this is not the case, the docs should be updated.

**Comment by franck-boullier** [comment]
This works now in PR41
