### ISSUE TITLE
Some notification messages do not mention the Unit Name and/or the Case title

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#421]
# The problem:

A few information which should be obvious for the user receiving a notification are missing in some notification messages.

# The solution:

We need to make sure that each notification message include the following information:
- The Name of the Unit
- The title of the case
- What was changed in the case (new assignee or new invitee or the beginning of the new message, etc)

We need to makes sure that this is done for each of the templates here: https://github.com/unee-t/frontend/tree/master/imports/email-templates

**Comment by kaihendry** [comment]
Would be easier to implement is there was an explicit proposal for the template / mock up.

After a quick scan of exiting templates, it would seem we are missing the unit names? Since title and "what has changed" is already expressed.

**Comment by franck-boullier** [comment]
Fixed in the latest release. See #814
