### ISSUE TITLE
Inspection report template

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#427]
Design reference: https://www.figma.com/file/LPv1IUfOtu4YdsBBi4bXiANx/Unee-T-Inspection-Report-v3-01?node-id=0%3A121

**Comment by kaihendry** [comment]
Bit harder than I thought. Doing header/footer on PDF is a challenge. Struggling to right align the header, nevermind the repeating footer https://s3-ap-southeast-1.amazonaws.com/dev-media-unee-t/2018-08-07/ok.pdf

**Comment by kaihendry** [comment]
* https://s3-ap-southeast-1.amazonaws.com/dev-media-unee-t/2018-08-14/johndoesallypeters.html
* https://s3-ap-southeast-1.amazonaws.com/dev-media-unee-t/2018-08-14/p-johndoesallypeters.pdf

Using https://docraptor.com/signup which costs.

Still trying to work out how to best back the images in a two column layout.

Signature for some reason won't go side by side.

**Comment by franck-boullier** [comment]
This is taking shape so 👍 but

> Using https://docraptor.com/signup which costs.

@kaihendry... 😨 this might be a temp solution until we figure out something else.
We'll have to do the math on this (or change our pricing plan to charge on a per/report basis which I do not like TBH...)

**Comment by nbiton** [comment]
We discussed this to be a probably temp solution. It's likely that we can replace the PDF generation with our own thing once we gain more momentum.

**Comment by kaihendry** [comment]
Current state using Prince 12: https://media.dev.unee-t.com/2018-08-16/state.pdf

**Comment by nbiton** [comment]
This is starting to look pretty good. So it's not using DocRaptor anymore?

**Comment by kaihendry** [comment]
Not docraptor since I am hoping now to run Prince 12 directly in a lambda pending a negotiation.

Prince 12 also has flex box support (unlike docraptor, which uses perhaps an older prince? idk), that's why the signature don't look good on docraptor. We also need flex to deal with multiple images well imo.

**Comment by franck-boullier** [comment]
@kiatlim maybe we can add a page break before each new item ---> this should make the pagination cleaner

**Comment by kaihendry** [comment]
Now using Prince 12, e.g. https://s3-ap-southeast-1.amazonaws.com/dev-media-unee-t/2018-08-17/1534496898.pdf
Hosted on AWS Lambda: https://github.com/unee-t/lambdaprince

Next week I want to experiment with flex box and images.

**Comment by kaihendry** [comment]
This is mostly done https://github.com/unee-t/inspectionreportgenerator

Btw design reference currently is out of sync.
