### ISSUE TITLE
Misc improvement to the Look for Notification Messages - Design Suggestions

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#437]
Moving @sebdeckers comments from Slack in a GH issue. @kiatlim and @sophieyang0813 can you take a quick shot at this?

- Weird monospace "system" message. Should be styled as a CTA button.
- Same link again. Avoid duplication and style it as a button or clean link, not just ugly URL.
- Random link for "Unee-T" in body. Should be plain text.
- Message body is printed as a plain string. Not clear that this is the actual message. Make it look like in the app's chat UI.
- Slogan is added below content for no clear reason.
- Configure notification settings should be de-emphasised and in a footer.

<img width="1093" alt="screen shot 2018-08-15 at 3 55 03 pm" src="https://user-images.githubusercontent.com/31331637/44202939-ff3e6d80-a17f-11e8-96ff-9ce3fc55dfa3.png">

**Comment by kiatlim** [comment]
@franck-boullier @nbiton @sophieyang0813 do you happen to know where is the template of this file? We can possibly adjust the template similar to how we adjust the inspection report.

**Comment by franck-boullier** [comment]
@kiatlim email templates are here: 
https://github.com/unee-t/frontend/tree/master/imports/email-templates

**Comment by kaihendry** [comment]
Just a note that things have changed since the screenshot above.

One quick design inconsistency / question is that the Inspection report sharing email has the logo at the bottom, whilst notification emails have the logo at the top. Shall we change the notification emails to have the logo at the bottom signature area?

**Comment by franck-boullier** [comment]
Fixed in the latest release. See #814
