### ISSUE TITLE
Expose more functionalities to user - Change the default landing page

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#439]
# The problem:

Today when a user logs in to Unee-T we bring the user to the 'Case' page.
This was OK when we only had the 'Case' interface up and running.
Now that we have the 'Unit' interface and the 'Inspection Report' interface it will be good that the user immediately knows what is possible to do with Unee-T i.e show more functionalities to the user at login.

# Suggested solution:

After user logs in to Unee-T show the user the case page with the Unee-T menu expanded:
![image](https://user-images.githubusercontent.com/31331637/44203634-43327200-a182-11e8-8bc6-b838b13732fe.png)

**Comment by sophieyang0813** [comment]
@franck-boullier Could you clarify this for me? I see the suggested solution(the expanded Unee-T menu with the case page in backdrop) when I logged in as a user 🤔?  

on login: **the case page** with the expanded Unee-T menu  
on signup: **the unit page** with the expanded Unee-T menu

**Comment by franck-boullier** [comment]
>Could you clarify this for me? I see the suggested solution(the expanded Unee-T menu with the case page in backdrop) when I logged in as a user 🤔?

>on login: the case page with the expanded Unee-T menu

Yes the default page that a returning user should see IMO is the case page with the expanded Unee-T menu.

>on signup: the unit page with the expanded Unee-T menu

No need to do this on signup ---> we expect/assume that what the new user wants/needs to create his/her first unit so no change needed there.

@sophieyang0813 any other clarification needed?

**Comment by sophieyang0813** [comment]
Suggested solution seems to be already implemented.  When I log in as a user in my local environment, I see the case page with the expanded Unee-T menu...🤔

What do you see when you log in?

**Comment by franck-boullier** [comment]
> Suggested solution seems to be already implemented.

@sophieyang0813 OK then, I'm closing this :blush:
