### ISSUE TITLE
Inspection Report - User can't find DRAFT reports

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#446]
# The  Problem:

First feedback from pilot user on the Inspection Reports: user do not see the 'Draft' Tab on the Inspection Report Menu item ---> user is confused and don't know where to find the Report that have not been Finalized yet.

![image](https://user-images.githubusercontent.com/31331637/44521413-95850d00-a705-11e8-9c49-61832807d9e3.png)

# Suggested Solution:

Use the same idea that we have in the Units/Report interface where Draft and finalized reports are differentiated by 2 icons.:
- Completed Reports: 
![image](https://user-images.githubusercontent.com/31331637/44521188-dc263780-a704-11e8-82e9-295502bafd05.png)
- Draft Reports:
![image](https://user-images.githubusercontent.com/31331637/44521213-e6e0cc80-a704-11e8-9b09-1a6b218c647e.png)

See:
![image](https://user-images.githubusercontent.com/31331637/44521161-c31d8680-a704-11e8-939c-ffac4a2cd6ee.png)

We could split the screen in 2 __scrollable__ boxes:
- Completed
- Draft

And list the Inspection reports on the same page.
This would look like something similar to the Unit page (with the important difference that the 2 boxes will be the same size and scrollable - this is not the case on the Unit Page UI):
![image](https://user-images.githubusercontent.com/31331637/44521323-3aebb100-a705-11e8-9f5c-d59ab3c7e205.png)

# Additional Remarks:

## Wording:

We probably need to use a consistent wording for Inspection Report: today we use 'Finalized' and 'Completed' to describe the same thing: the report can't be modified anymore.

We should use the same word for the same concept.
I suggest we use 'Finalize' and 'Finalized' instead 'Complete' and 'Completed'

## Existing Filters:

We'll need to keep the existing 'Created By Me' filter but will probably need to design it slightly differently
![image](https://user-images.githubusercontent.com/31331637/44521390-78e8d500-a705-11e8-9668-2c4861f31718.png)

@kiatlim and @michkwt can you help us and update the design?

**Comment by franck-boullier** [comment]
> Is that what is needed from us to update the design

@kiatlim, yes please

> are there any thing specific to the solution?

I can't think of anything else (but I'm not sure I understand the question completely TBH 😁 

> How can we view the above in browser anyway?

You can go to case.dev.unee-t.com ---> login as leonel and navigate to Inspection Reports (from the main menu) and to Units >> Reports

**Comment by kiatlim** [comment]
![report listing](https://user-images.githubusercontent.com/641679/44653997-9da9b900-aa33-11e8-8c92-4eedcaaeb253.png)

@franck-boullier Capturing your comments here:
1- I will make sure that both the 'Finalized' and 'Draft' windows are scrollable: if there are a lot of report in the 'Finalized Reports' pane then we should still be able to see the 'Draft Reports' pane
2- We still have a way for the user to filter the Reports `Created by Me`

I'm not in favour of having to the scrollable panel interaction, its going to make it clutter and hard to use, imagine having 20-30 reports created over time. 

For such requirements of finalized, draft and created by me, going with the Tab design is still the solution that makes sense, we can try to improvised the visual treatment.

**Comment by franck-boullier** [comment]
> For such requirements of finalized, draft and created by me, going with the Tab design is still the solution that makes sense, we can try to improvised the visual treatment.

OK let me know when I can review your latest idea :+1:

**Comment by kiatlim** [comment]
![image](https://user-images.githubusercontent.com/641679/44655524-caac9a80-aa38-11e8-8949-25cb3afb2e98.png)

Unfortunately, the tab solution doesn't work so well too because of the double layer of tabs. Will explore other possible solutions.

**Comment by kiatlim** [comment]
![image](https://user-images.githubusercontent.com/641679/44655825-e3698000-aa39-11e8-9e9c-afe5e8485a0d.png)

Another idea, using a drop down to filter the reports. Selecting the arrow will see:
- All reports
- Finalized reports
- Draft reports
- Created by me

**Comment by kiatlim** [comment]
Introducing this bar under the tab, we can also include sorting criteria if we want to and across other kind of similar listing e.g. case listing within unit details.

![image](https://user-images.githubusercontent.com/641679/44655958-67236c80-aa3a-11e8-8492-e2bc1dfba3f6.png)

**Comment by franck-boullier** [comment]
> Introducing this bar under the tab, we can also include sorting criteria if we want to and across other kind of similar listing e.g. case listing within unit details.

@kiatlim I really like that filter solution! That's my preferred choice
@nbiton do you see any major problem to implement that?


![image](https://user-images.githubusercontent.com/641679/44655958-67236c80-aa3a-11e8-8492-e2bc1dfba3f6.png)

**Comment by franck-boullier** [comment]
@kiatlim in this design how would I do a filter with 2 criterias?
Example: Draft reports created by me?

**Comment by kiatlim** [comment]
Drop down can be a check box I guess? Other than All reports option, the
other 3 options can be multi selected?

**Comment by franck-boullier** [comment]
> Drop down can be a check box I guess? 

I like that idea!

Can we have mockups and finalize the design for this?

**Comment by nbiton** [comment]
@franck-boullier Checkout https://v0.material-ui.com/#/components/select-field with the "Multiple selection example"

**Comment by franck-boullier** [comment]
I like that!

![image](https://user-images.githubusercontent.com/31331637/45017860-41f6b580-b05b-11e8-8ba4-aca998be5f52.png)

**Comment by franck-boullier** [comment]
@kiatlim and @michkwt the only thing left to do from the design perspective so we can implement is to make sure the links to the mockups in figma are added to this GH issue.

**Comment by franck-boullier** [comment]
Partially closed with PR #490 The rest is addressed in Issue #496
