### ISSUE TITLE
No clear solution to "verify your email address"

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#450]
# The problem:

The latest release added a message to all the user who have not verified their email address.
There is no possibility/explanation on how it is possible to verify an email address

![image](https://user-images.githubusercontent.com/31331637/44647618-219e7980-aa11-11e8-9e5e-a2bfb6e7e449.png)

**Comment by kaihendry** [comment]
Related to https://github.com/unee-t/frontend/pull/413#issuecomment-407988255

**Comment by franck-boullier** [comment]
Fix has been implemented in PROD
