### ISSUE TITLE
Regression - Invalid email format error on signup, showing wrong error message.

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#454]
Signup of new user, with invalid email format shows the error of "user exists" instead of the expected "Email address is invalid"

![unee-t-signup-invalid-format](https://user-images.githubusercontent.com/17175484/44775856-3a419780-aba9-11e8-81a0-15f20a684941.gif)

Possibly related to https://github.com/unee-t/frontend/issues/206 fix

For reference, login shows the error correctly.

![login-screen-invalid-format](https://user-images.githubusercontent.com/17175484/44776211-2b0f1980-abaa-11e8-98b1-4b0fed3aa3d3.gif)

**Site Tested**

+ https://dev.case.unee-t.com/signup
+ https://demo.case.unee-t.com/signup

**Browser Tested**

+ Chrome

**Comment by kaihendry** [comment]
Can confirm https://media.dev.unee-t.com/2018-09-10/email-already-exists.mp4

**Comment by franck-boullier** [comment]
Fixed in PR #491
