### ISSUE TITLE
Error code 500 - when signing up on "demo.case.unee-t.com"

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#463]
When signing up, on "demo.case.unee-t.com", 500 code is being shown

![screen shot 2018-08-30 at 9 35 03 pm](https://user-images.githubusercontent.com/17175484/44855107-eadc9380-ac9c-11e8-94bb-35e36bbd2976.png)

Subsequently trying to submit again, shows that account was created (which is confusing to users)

![screen shot 2018-08-30 at 9 35 14 pm](https://user-images.githubusercontent.com/17175484/44855190-18294180-ac9d-11e8-8e22-dca24551d9dd.png)

Fortunately, logging in with the registered user and password, is valid.

**Site Tested**

+ https://demo.case.unee-t.com/

**Browser Tested**

+ Chrome
+ Firefox

**Comment by franck-boullier** [comment]
This `500 error` message appears sometimes when an email address already exists and the user is trying to re-create an new account with that same email address.

We need to give a better error message and improve the UX when a user tries to create an account with an email address which already exists.

**Comment by kiatlim** [comment]
@franck-boullier we can consider to use the new Login flow for Sign up as well:
- User enters email on email field. 
- When he presses "Sign up" and if account exists
- Goes to the reset password screen with email pre-filled and with a message like this "Woops, you already have an account with Unee-T. Did you forget your password?"
- Button says "Yes, reset my password"

The issue with indicating that users have an account with Unee-T is possibly security / privacy issue whereby attackers can see whether a particular email address already has an account with Unee-T. 

Can discuss further on Wed.

**Comment by ongdominic** [comment]
@franck-boullier We can also consider this 2 options:
1. Consider re-use the 2 step log in for creating an account. If a user has an existing account, we should prompt them for their password.
2. We can check if their email has been used when they enter their email and prompt them to either log in or use another email.

**Comment by franck-boullier** [comment]
Closing this issue: 
- the initial problem has been solved (email sending capability was disabled in the DEV envo)
- The UX improvement is already discussed in another Figma [here](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=870%3A83)
