### ISSUE TITLE
Facilitate Case creation - Allow user create a case with no additional description

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#467]
# The problem:

We want to minimize the number of click and the amount of data entry the user has to do before a case is created.

Today the "Details" field in the MEFE is a mandatory field
![image](https://user-images.githubusercontent.com/31331637/44943060-de1d8400-adf1-11e8-8dc1-bd87700fcf9e.png)

This adds one more hassle for the user to create a case.

# Suggested solution:

When a case is created in the MEFE, allow the case to be create without an additional description.

If there is no additional description entered in the MEFE then we duplicate the case title/summary of the case as the corresponding (and mandatory) BZ `description` of the bug in the BZ back end.

**Comment by sophieyang0813** [comment]
fixes #467

**Comment by franck-boullier** [comment]
Fix has been implemented in PROD
