### ISSUE TITLE
BUG - Frozen page when trying to create a new IR

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#468]
# The problem:

This happened in the PROD environment.

Try to create a new inspection report. Go to https://case.unee-t.com/report
![image](https://user-images.githubusercontent.com/31331637/44943172-8c2a2d80-adf4-11e8-8fad-4273b67b4f2c.png)

There are no units with an existing IR yet.
Click on the '+' button at the bottom right of the screen

## Expected result:
Go to the page https://case.unee-t.com/unit

## Actual result:

The page is broken/frozen

![image](https://user-images.githubusercontent.com/31331637/44943160-63099d00-adf4-11e8-8668-b12dc3b7b016.png)

**Comment by nbiton** [comment]
I can't reproduce this bug

**Comment by franck-boullier** [comment]
@nbiton 
# your test:
- Created a new account name "naor+1@net-comet.com"
- Used the signed panel to navigate to the "/report" view
- Clicked the "+" button
---> ended up on the units view and it was empty. Everything worked as expected

# Conditions for the bug to appear:

- User already exists
- User has a role in some units
- User has no Inspection Report

**Comment by franck-boullier** [comment]
Clarification (not sure if this matters), the user has been invited to unit and hasn't created any unit in the MEFE

I am able to replicate the issue with 2 different users: 
- me as admin
- me as tenant/idividual account

![image](https://user-images.githubusercontent.com/31331637/44954753-c7eaf300-aed9-11e8-9c3c-2be667b73374.png)

**Comment by nbiton** [comment]
I still can't reproduce, which makes me start to suspect it's not the conditions but a timing/ race condition related issue which pops up due to different network latencies. I'm going over all the code that might have an impact on this views to track down potential race conditions

**Comment by nbiton** [comment]
I'm refactoring a few things that might have a hand in making this error pop up (or not). We'll know soon :sweat_smile:
