### ISSUE TITLE
Implement a Selection Mechanism to 'select your unit' for New Inspection Report (and New Cases)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#469]
# The problem:

- User wants to create an Inspection Report
- User goes to the 'report' page: https://case.dev.unee-t.com/report
- The unit is not in the list ---> user clicks on the '+' sign at the bottom right of the page

![image](https://user-images.githubusercontent.com/31331637/44943220-28eccb00-adf5-11e8-9c79-9dd74049ed0b.png)

- User is is sent to the list of units: https://case.dev.unee-t.com/unit
- There is no clear call to action to create an Inspection Report ---> where is the user supposed to click?

![image](https://user-images.githubusercontent.com/31331637/44943242-76693800-adf5-11e8-955c-21b058e02e41.png)

@kiatlim and @michkwt do you have any suggestion/recommendation?

**Comment by kiatlim** [comment]
Prob we can have a separate “Select unit” listing which allows the user to pick the unit, and not going to the default /unit listing screen. This screen should then be universal suitable for other types of content the user may create in the future. 

I think this was discussed when we were talking about creating case for units that have no cases. 

The requirement here is that we don’t list units where there is no case or reports in their respective landing screen.

**Comment by franck-boullier** [comment]
> have a separate “Select unit” listing which allows the user to pick the unit, and not going to the default /unit listing screen

@kiatlim I like this idea.
Can you suggest a design for that? 

It should probably include a search functionality to allow the user to type something and automatically narrow down the selection (same as what we are doing when the user has to pick a country).

**Comment by michkwt** [comment]
<img width="826" alt="screen shot 2018-09-03 at 5 48 54 pm" src="https://user-images.githubusercontent.com/38183796/44980166-ab19f280-afa1-11e8-8f2d-e4a0ace8099d.png">

1. “Select unit” listing which allows the user to pick the unit, and not going to the default /unit listing screen.
2. include a search functionality to allow the user to type something and automatically narrow down the selection

@franck-boullier

**Comment by franck-boullier** [comment]
@kiatlim I like the design :+1: 
We probably want to make the title more generic as this would also be used to select the Unit to create a new case too (in the context of case creation)

@nbiton do you see any major issue with this design?
IMO we should put this high on the priority list as we currently have a problem if a user wants to create an Inspection Report from the "Report" page...

**Comment by kiatlim** [comment]
@franck-boullier The generic part is the text - Select the Unit you wish to create a _____ for.
And we can supposedly replace it with Report or Case for now?

**Comment by franck-boullier** [comment]
> we can supposedly replace it with Report or Case for now?

Yes we probably can BUT what if/when we want to add something like "Items" in the future to facilitate inventory tracking?
The generic part of the text would have to be changed to
"Select the Unit you wish to create __an__ _____ for" and only for object where the name starts with a vowel ---> unnecessarily complex ---> I suggest we use "Select your Unit" instead

**Comment by michkwt** [comment]
<img width="838" alt="screen shot 2018-09-04 at 8 30 03 pm" src="https://user-images.githubusercontent.com/38183796/45031442-6a91a600-b081-11e8-8fd4-5ea1f6e16515.png">

Changed text to generic copy

@franck-boullier @nbiton

**Comment by franck-boullier** [comment]
@michkwt Excellent thanks!
Can you make sure the design is available in Figma (or Invision) to facilitate the Dev.

@sophieyang0813 we should also implement that soon ---> this is very important to have so user can generate Inspection Reports easily.

**Comment by franck-boullier** [comment]
Additional comment: if the "search" functionality is too complex/long to implement it is OK to release an intermediate version without the "search" and implement the search a little later.

**Comment by michkwt** [comment]
@franck-boullier @sophieyang0813 

It is on figma! Here is the link: https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=218%3A640

**Comment by kiatlim** [comment]
> hendry [8:57 AM]
Couldn't modals be avoided? https://github.com/unee-t/frontend/issues/469#issuecomment-418349416 i.e. just navigate between well defined pages? I guess X on the top right means back, but I am not sure. All I know is Modals _suck_

> hendry [8:59 AM]
In my ideal world, if I ask a customer to complete an action, i can say to that customer, please navigate to /ir/selectunits?title=blah&units=foo,bar confirm and boom report done
modals break up everything and make URLs damn hard
design imo starts from the URL

> franck_b [10:06 AM]
> replied to a thread:
> I personally have 0 preferences between modals or URLs...
> - @Kiat from a UX/UI perspective do we know what's best: modals or 1 more page?
> If there is documented evidence that modals are best from the user perspective then I will favor user experience over any other criteria.
> If there is no data about that or if there is no difference from a UX perspective between modals and dedicated page then I see no issue to implement a new URL as per @hendry’s suggestion
> 
> - @nbiton is there any differences from a dev/front end perspective between creating a modal or creating a dedicated page (I don't expect there is any but just checking...)?

Modals don't suck, they just need to be used appropriately. Further reading from https://uxmag.com/articles/modals-on-mobile-how-to-use-them-wisely suggests that modals should be applied only to meet the following objectives:

- Interruption: Forcing the user to make a decision or complete a task at an important part of their workflow. Ask yourself, “do I really want to interrupt the user?”
- Feedback or Correction: Confirming decisions. E.g., “are you sure?” moment.
- Deep Dive: Focusing the user on a single piece of content, be it an image, article, or a video.

The reason when we used modal for the invite user was originally for consistency sake as it retains the same invite user / assign user flow designed in the Case pattern.

Removing modal for selecting units is not an issue:

<img width="754" alt="screen shot 2018-09-05 at 12 05 10 pm" src="https://user-images.githubusercontent.com/641679/45071304-24cbf080-b108-11e8-853f-512f2aba8b55.png">

The issue will be making it consistent across other modal screens, do we want to consider changing the invite user / assign user from modal to a screen?

**Comment by franck-boullier** [comment]
>Further reading from https://uxmag.com/articles/modals-on-mobile-how-to-use-them-wisely suggests that modals should be applied only to meet the following objectives:
> - Interruption: Forcing the user to make a decision or complete a task at an important part of their workflow. Ask yourself, “do I really want to interrupt the user?”
> - Feedback or Correction: Confirming decisions. E.g., “are you sure?” moment.
> - Deep Dive: Focusing the user on a single piece of content, be it an image, article, or a video.

@kiatlim 
Based on this, I think modal is the right call
Thanks for the clarification

**Comment by franck-boullier** [comment]
> going with modal might be difficult to implement and get it "right" across different devices.

@kiatlim, Fair point...
@nbiton I'll let you make the final call since I know we had issues in the past to implement modals which would work on various screens...

**Comment by franck-boullier** [comment]
URLs will also facilitate some integration scenarios.
Is we have a URL that we can use to pass some contextual information that's way simpler...

**Comment by nbiton** [comment]
@kiatlim @franck-boullier we've integrated modals for other things, such as inviting users, and report creation. Not sure why this should be different? From a code perspective, a modal is just another component on the page. Most modals we used so far are bound to a specific sub-route (navigating to that irl just makes the modal appear), and we can definitely do the same for this modal.

**Comment by franck-boullier** [comment]
@nbiton thanks for the clarification

As a summary my understanding is:
- Modals are a good UX solution in this context.
- Modals are not more complex to implement than urls.
- We are currently using modals in some other interface.
- Consistency matters a lot as far as UX.
- Using modals will not complicate future integration if/when needed  (we have specific sub-routes we can use).

For all these reasons let's keep the Modal design and implement this

<img width="838" alt="screen shot 2018-09-04 at 8 30 03 pm" src="https://user-images.githubusercontent.com/38183796/45031442-6a91a600-b081-11e8-8fd4-5ea1f6e16515.png">

Feel free to correct me if I got it wrong

**Comment by sophieyang0813** [comment]
@michkwt Good morning! Looking forward to seeing the new design mockup 🌻🌻

**Comment by kiatlim** [comment]
@sophieyang0813 here you go: https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=390%3A1923

![image](https://user-images.githubusercontent.com/641679/45275374-fa56aa80-b4ee-11e8-9153-7fe6ee23eb3a.png)

**Comment by nbiton** [comment]
@franck-boullier and I just had a discussion about this issue.
The non-modal design lacks context for the current operation being done by the user. This makes it harder to remind the user what he was doing. 
It also doesn't flesh out the search feature like the modal design does..
So it seems like the modal design actually makes more sense it this scenario.
Also, implementing the non-modal design involves more complex data context management, and makes it harder for code reuse (using the same component for both case and report creation).

For these reasons, we'll be going for the earlier modal design (from @michkwt comment) for now, as it'll definitely yield a more consistent experience with a shorter implementation time.

**Comment by franck-boullier** [comment]
The design @nbiton is referring to is here:
<img width="838" alt="screen shot 2018-09-04 at 8 30 03 pm" src="https://user-images.githubusercontent.com/38183796/45031442-6a91a600-b081-11e8-8fd4-5ea1f6e16515.png">

**Comment by franck-boullier** [comment]
this works in PR #519
