### ISSUE TITLE
Suggestion to make it easier to update some case fields

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#473]
# The Problem:

We want to minimize the number of clicks a user has to do and the number of screens a user needs to see so he/she can perform an action.

As of today, we have some drop down fields which can be updated in the 'More information' view of a case.

![image](https://user-images.githubusercontent.com/31331637/44943940-47f15a00-ae01-11e8-89fa-cba0da3c38da.png)

# Suggested solution:

During our meetup yesterday one idea was put forward to allow a user to edit these fields directly from the 'conversation' screen for a case.

The main concept is to leverage the exiting toolbar at the top of the screen and make it horizontally scrollable.

Apologies for the very crude rendition but this would look something like that:

- Make the toolbar horizontally scrollalbe

![image](https://user-images.githubusercontent.com/31331637/44943958-b209ff00-ae01-11e8-9be5-3f6501b78ad0.png)

- Add more option to this toolbar (ex here: update the status of a case)

![image](https://user-images.githubusercontent.com/31331637/44943960-be8e5780-ae01-11e8-94f8-73ac06311189.png)

![image](https://user-images.githubusercontent.com/31331637/44943964-f3021380-ae01-11e8-8e24-665f50c32e16.png)

@kiatlim and @michkwt what do you think?

**Comment by kiatlim** [comment]
Discussed with @franck-boullier on Friday (7 Sep) that we probably don't need this right now as clicking on the More Information is just 1 click away to see all the options they can edit.

**Comment by franck-boullier** [comment]
Closing this as this issue is obsolete.
