### ISSUE TITLE
PR41 - case screen displays either solution or next step (it should display both if exists)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#48]
When a case has both a solution and a next step, the expected behavior is to display BOTH the solution and the next step in the main screen for the case.

Today it only displays the solution.

See case 54178 for an example of that

**Comment by nbiton** [comment]
It should work now as expected. Please verify

**Comment by franck-boullier** [comment]
PR41is not accessible via Heroku
I ha e there ever loading page issue again...

**Comment by nbiton** [comment]
I closed PR #41 and merged to master... unfortunately, the build on master is currently failing :(

**Comment by franck-boullier** [comment]
Oh!
OK
Let me know when I can test 😁

**Comment by franck-boullier** [comment]
@nbiton I have a meeting soon when I need to be able to show a demo of what we do. 
When can I expect dev.case.unee-t.com to be up and running again?

**Comment by franck-boullier** [comment]
This is now workiin in PR 55
