### ISSUE TITLE
Bug - Unable to access some unit page

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#489]
# The test:

In the DEV/Staging environment.
- Log as leonel - PASSED
- Go to the [Unit page](https://dev.case.unee-t.com/unit).
- Click on any unit

# Expected result:

The details of the unit are displayed

## Actual result:

Endless loading page
![image](https://user-images.githubusercontent.com/31331637/45219561-e38d3980-b2dd-11e8-83fe-07f65754c347.png)

**Comment by franck-boullier** [comment]
Latest hot has partially fixed the issue:
Tests done in the DEV/Staging environment.

# The FAILED test (only for specific units):

- Click on on 'Add Report' for a specific unit (ex unit Store-431) 

## Expected result:

- The window to name the inspection report appears.

## Actual result:

- We are sent to the following link: https://case.dev.unee-t.com/unit/not_listed/reports/new
- Endless loading page

![image](https://user-images.githubusercontent.com/31331637/45249405-3ef90f00-b352-11e8-97d4-08011d0a84e4.png)

## Comment:

My guess is that this is happening for all the units that were created as part of the Heroku based tests ---> we have no record on the unit in the Mongo DB associated to the DEV/Staging environment.

# The PASSED :

- Log as leonel - PASSED
- Go to the [Unit page](https://case.dev.unee-t.com/unit).
- Click on any unit ---> details of the units are displayed - PASSED
- Go to the 'Reports' Tab PASSED
- Click on the '+' sign to add a report PASSED
- Go to the [Report](https://case.dev.unee-t.com/report) page via the main menu PASSED
- Click on 'Add Report' for one of the unit associated with leonel ([unit 283](https://case.dev.unee-t.com/unit/283/reports/new)) PASSED

**Comment by franck-boullier** [comment]
# Suggestion:

Maybe we can just hide the "Add Report" link for the Units were there are no details on the Unit in the MEFE ---> This should never happen in the prod and would be an elegant workaround for the "orphan" units.

I think this is how we handle these in the '[Case](https://case.dev.unee-t.com/case)' page

![image](https://user-images.githubusercontent.com/31331637/45249512-0f4b0680-b354-11e8-96f6-7d91b37a4717.png)

**Comment by nbiton** [comment]
This bug is not due to the last PR

**Comment by franck-boullier** [comment]
This is working now: The unit like "Store-43" are not visible in the list anymore

**Comment by franck-boullier** [comment]
Closing as this issue is now fixed
