### ISSUE TITLE
Improvement - Behavior - Color code for user should be based on user role

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#49]
Today in PR41 each user is displayed with a different color code.
This works well and is useful

A interesting way to use color code would be to have the same color code for each user in the same role for the unit (ex: blue for all user with a property management role for the unit).

This is not key for the MVP but would be a nice additional feature as we move forward.

**Comment by kaihendry** [comment]
You could hash the role and use that as a colour? E.g. https://hendry.jsbin.com/yojoki/quiet

**Comment by nbiton** [comment]
Nicr idea, but I think the color needs to match with the general color scheme

**Comment by nbiton** [comment]
I used two colors that appear on Kiat's designs, and generated additional ones that match them using https://coolors.co

**Comment by kiatlim** [comment]
Just saw this thread and thought its interesting, for the color codes, actually i chose the colors quite randomly, so long its dark in shade and can fit white text. I suppose we can use the ones that match what we have and just assign it to different roles, since we only have a few roles now. 

Good to park this as future enhancement. Is there a label for that?

**Comment by franck-boullier** [comment]
@kiat I just added the "enhancement" label

**Comment by franck-boullier** [comment]
In PR #112:
the color code for the same user is different when:
- User is the same
- User is involved in the case in several capacity, example: user is the Reporter AND the Assignee. This is counter intuitive...

**Comment by franck-boullier** [comment]
@mariorodriguespt
Yes the overall app is very BZ dependant today for a number of things

That being say the source of truth for user role is in the MEFE and then passed down to BZ
It is safe to query the mongodb to get the user role for the MEFE (MEteor Front End - I know I need to post our glossary in the documentation and will do)

This is the most sustainable and future proof approach

The BZ integration gives us a ton of built in functionalities: fine grain user permissions, security, searches, reports, history, and the list goes on

**Comment by franck-boullier** [comment]
Also the default environment has 0 case today and only a few users yes, we need to beef this up so that it's possible to play around with various scenario

There are a few issues in there which document that and we are working on that

**Comment by kaihendry** [comment]
@mariorodriguespt Sounds like your solution is seriously over engineered to me if you need to write "some hooks to populate MariaDB and MongoDB so that things stay in sync" to solve this issue.

In my mind the ultimate source of truth is the Bugzilla DB, but I am the Devops guy, so I what do I know? ;)

**Comment by franck-boullier** [comment]
@mariorodriguespt
No need to do sync between mongo and BZ at this point: changes in a user role is beyond the scope of this issue but I like that you considered that!

@Kaihendry source of truth depends on what info your are looking for actually
Some things are stores in the MEFE because the BZFE can't handle these and it makes more sense to have Mongo as the source of truth (ex: address for a unit)

**Comment by franck-boullier** [comment]
The single source of truth for the role is meteor/lingo
No need for a REST call to the BZ here just get this directly from mongo

**Comment by franck-boullier** [comment]
BTW most of your questions are valid and interesting and should help you understand the nitty gritty details of the choices we made (And we do NOT do cron jobs) but these are way beyond the scope of this issue

This is really a simple case which you can solve 100% by just slightly altering the Meteor code.

**Comment by mariorodriguespt** [comment]
Still on this, I'm taking a while since because I'm reading docs and understanding the schema.
I found tables like `ut_role_types`, is `ut_` a prefix for tables manually created that belong o `Unee-T` ?

**Comment by franck-boullier** [comment]
yes 'ut_...' tables are Unee-T specific table.
This table stores the list of the roles we are using in Unee-T and a few additional info about these roles
Wondering why you need to do anything in the BZ DB for that issue though 🤔, keep in mind that the source of truth for a role for a given user is in the MongoDB, and NOT in the BZ db

**Comment by mariorodriguespt** [comment]
I was able to find the roles in SQL database but not in Mongo.

I don't believe the source of truth is Mongo but Bugzilla itself.
Lets take a look at the following code:


```
[`${collectionName}.insert`] (params, { newUserEmail, newUserIsOccupant }) {
    if (!Meteor.userId()) {
      throw new Meteor.Error('not-authorized')
    }
    if (Meteor.isServer) {
      const { bugzillaCreds: { token } } = Meteor.users.findOne(Meteor.userId())
      const { callAPI } = bugzillaApi

      let unitItem
      try {
        const requestUrl = `/rest/product?names=${encodeURIComponent(params.selectedUnit)}`
        const unitResult = callAPI('get', requestUrl, {token}, false, true)
        unitItem = unitResult.data.products[0]
      } catch (e) {
        console.error(e)
        throw new Meteor.Error('API error')
      }

      // Checking the role is valid
      const relevantRole = unitItem.components.find(({ name }) => name === params.assignedUnitRole)
      if (!relevantRole) {
        throw new Meteor.Error(
          `The designated role "${params.assignedUnitRole}" does not exist on the unit "${params.selectedUnit}"`
        )
      }
```


1. We use Bugzilla API to fetch the unit
2. **We use Bugzilla to check if the role is valid**

When I wrote about syncing about Bugzilla's SQL database with Mongo, I was referencing to this. Even if I store the role in MongoDb, if it's not present in Bugzilla it will fail. So either we sync or switch the approach.

**Comment by nbiton** [comment]
Hey @mariorodriguespt , you shouldn't worry about diving into such low-level concerns for this task.
Generally, the user roles in the scope of a unit are resolved by querying both Bugzilla's API and the invitations collection in Mongo, and combining the results. If you're interested in seeing how that is done (although unnecessary for this task), you can review the [getUnitUsers function](https://github.com/unee-t/frontend/blob/master/imports/api/units.js#L24).
For this task, you should look into a data structure already present in the UI (but retrieved by the above), which is the [unitUsers property of the Case component](https://github.com/unee-t/frontend/blob/master/imports/ui/case/case.jsx#L221).
You can see that it is being used to create caseUserTypes which matches the user by email to resolve its role, and also passed down to CaseDetails where it eventually trickles down to UsersSearchList which uses it to label the presented users with their corresponding role in the associated unit.
You can pass unitUsers to CaseMessages as well, and then use it in all the related case components to determine to colors used for each user.

I'll be happy to explain anything else related to this I might have omitted.

**Comment by franck-boullier** [comment]
Tested and works in PR #215
