### ISSUE TITLE
Standardize Look and feel for Filters and Sorts

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#496]
# The problem:

Today we have several different ways to display Sorts and Filters in the UI

## List of units:

The [unit](https://dev.case.unee-t.com/unit) page.
![image](https://user-images.githubusercontent.com/31331637/45459894-295a5f80-b72d-11e8-9122-cfcbe9470887.png)

## List of Cases for a given unit:

See [this link](https://dev.case.unee-t.com/unit/303) as an example.

![image](https://user-images.githubusercontent.com/31331637/45459940-66beed00-b72d-11e8-9023-c891754db541.png)

## The Report Page:

See the page [here](https://dev.case.unee-t.com/report).

![image](https://user-images.githubusercontent.com/31331637/45459987-a1288a00-b72d-11e8-9a52-452f5a67dca9.png)

## The Case page

See the page [here](https://dev.case.unee-t.com/case).

![image](https://user-images.githubusercontent.com/31331637/45460043-e64cbc00-b72d-11e8-892f-4c095e4dbffa.png)

# The solution:

Standardize the look and feel to the latest iteration of UI for Sorts and Filters 

See the conversation in Issue #446 for more context

The sort and filter UI should look like this:

<img width="918" alt="screen shot 2018-09-06 at 11 18 56 am" src="https://user-images.githubusercontent.com/38183796/45133262-dcbfd300-b1c6-11e8-9276-6a5604413715.png">

https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=297%3A65

**Comment by franck-boullier** [comment]
@michkwt and @kiatlim It'll be great if we have updated designs in Figma so that we can implement more easily 😋

**Comment by yvonnechia** [comment]
> @michkwt and @kiatlim It'll be great if we have updated designs in Figma so that we can implement more easily 😋

Hi @franck-boullier, 
Regarding the standardized filters across all pages, we've updated everything in Figma on one page here for your ease of further review / implementation:

https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=604%3A0
