### ISSUE TITLE
Inspection Report - User can't see the preview for the report

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#497]
# The problem:

A pilot user is trying to generate an inspection report.
The Report is created fine
BUT
It is not possible to see the Preview of the report.
User has a 500 Error (See screenshot)

For more details, see also the [Ticket created by the user](https://secure.helpscout.net/conversation/661807731/261/?folderId=2155403).

![image](https://user-images.githubusercontent.com/31331637/45461807-9115a800-b737-11e8-815c-4eb0a95b06e4.png)

**Comment by franck-boullier** [comment]
@nbiton case number for the inspection report with this issue is 68631

User is the same user that has the problem reported in issue #504

**Comment by franck-boullier** [comment]
@nbiton more information for debugging.

# Reports the user IS able to preview are:

## Finalized Reports:

- 68333

# Reports that the user is NOT able to preview are:

## Finalized reports

- 68571
- 68587
- 68606

## Draft Reports
- 68627
- 68631

Error message is 
![image](https://user-images.githubusercontent.com/31331637/45461807-9115a800-b737-11e8-815c-4eb0a95b06e4.png)

# Details about the Units:

## Preview is accessible for:

User reports that the report 68333 (finalized) that he can access was created for a unit that he has manually created in the MEFE.

The Report 68659 (draft) that he can access was also created for a unit that he has manually created in the MEFE. IMPORTANT INFO: there is ANOTHER issue on this inspection Report (see #504)

## Preview is NOT accessible for:

The reports where the preview is NOT accessible have been created by a different user (mass imported in MEFE).

**Comment by nbiton** [comment]
Thanks for the extra info @franck-boullier 
I'm still trying to figure out where the error is coming from

**Comment by franck-boullier** [comment]
My guess is that this is a permission issue somehow: If a user creates a report in the MEFE and then we change the assignee for the related bug in the BZFE ---> new assigned user can see the report in the MEFE list of report BUT can't access with the same 500 error message

**Comment by franck-boullier** [comment]
Hotfix in PR #507 solved the issue :tada:
