### ISSUE TITLE
Unit list

### ISSUE THREAD

**Issue by sebdeckers** [unee-t/frontend#5]
- Discussion https://unee-t.slack.com/messages/C6YDJ9X3K/
- Mockups https://share.proto.io/TAPKWL/

**Comment by franck-boullier** [comment]
the BZ API is pretty straight forward to get information about products/units:
http://bugzilla.readthedocs.io/en/5.0/api/core/v1/product.html:

---
To get a list of product IDs a user can select such as for querying bugs:

GET /rest/product_selectable

To get a list of product IDs a user can enter a bug against:

GET /rest/product_enterable

To get a list of product IDs a user can search or enter bugs against.

GET /rest/product_accessible

Response

{
  "ids": [
    "2",
    "3",
    "19",
    "1",
    "4"
  ]
}

**Comment by franck-boullier** [comment]
This works and we are able to list units in the MEFE today
