### ISSUE TITLE
"Magic Link" on invitations is not working

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#502]
# The Problem:

- User is creating a case
- User invites a new user to a case (new email address)
- Invited user receives an email with a link to see more information about the case
- Invited user clicks on the link

## Expected result:

- New invited user is automatically logged in to the case he was invited to

## Actual result:

- Error message "you must be logged in first"

## Workaround:

- New invited user has to reset his/her password 

# Why this is critical:

This is a 'Silent killer': we most certainly loose conversion from invited users who give up when they see the error message and get the perception that "This thing does not work"

**Comment by nbiton** [comment]
Unable to reproduce (this is working consistently as it should). Closing or now
