### ISSUE TITLE
Pilot user feedback - Some fields are missing in the Inspection Report Previews

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#504]
# The problem:

- User is creating an Inspection Report.

![image](https://user-images.githubusercontent.com/31331637/45592599-aa6f5c00-b9a4-11e8-9a84-c93038ef9bec.png)

![image](https://user-images.githubusercontent.com/31331637/45592605-bbb86880-b9a4-11e8-8a26-be0b9e7129b3.png)

- User wants to see the preview of the Inspection Report

## Expected results:

All the fields in the inspection report are visible in the preview.

## Actual Result:

Some fields are missing in the Inspection Report:
- Remarks and Comments
- Cases associated to the Inspection Report

![image](https://user-images.githubusercontent.com/31331637/45592758-ae9d7880-b9a8-11e8-992d-177dad7f851b.png)

# More information:

See the [helpscout ticket #264](https://secure.helpscout.net/conversation/663502867/264/?folderId=2155394).

**Comment by franck-boullier** [comment]
More information: When the user tries to scroll down, nothing happens, there are nothing more visible.

Can this be an outlier case when there is a lot of pictures to display?

**Comment by franck-boullier** [comment]
@nbiton more information (not sure if related) but the same user has a different problem on Inspection Reports too (not sure if related) please see #497

**Comment by nbiton** [comment]
I can't reproduce this bug.
I tried by creating an inspection report with enough pictures (17) and going to preview.
I tested it on Chrome / Galaxy S8+
Maybe this is a Safari/iOS specific issue? Can the user/ someone else check this report's preview on a different device?

**Comment by franck-boullier** [comment]
> Maybe this is a Safari/iOS specific issue? Can the user/ someone else check this report's preview on a different device?

OK I'll see if I can try to have user do this from another device/browser...

**Comment by franck-boullier** [comment]
We checked on different browser with the user account:
- This works on Chrome
- This works on Safari

We also noticed a weird issue as the report was not the same in Safari and in other browser.
We cleared the Safari cache on the User's iphone ---> Preview is now visible

:tada:
