### ISSUE TITLE
Use Bugzilla's API to fetch all the cases relevant to the user

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#51]
Blocks #50

**Comment by nbiton** [comment]
A potentially useful observation: the "CC list" field for each bug/case can contain multiple users and is relatively easy to query by. It could be useful if it's updated accordingly and the query is made in combination with "assignee" and "reporter" matchings.

**Comment by franck-boullier** [comment]
I agree: cc is the correct mechanism to make sure someone who is not the assignee is kept in the loop of what's happening on that case if one is not the assignee...

It goes like this:
1- case is create and assigned to a role.
BZ sends the case to the default user for that role.
2- If you need to add more user to the case, we add BZ users as CC for this case.
3- regardless of who is in CC a case should always be assigned to an assignee (a BZ user)
5- if a user is not the assignee anymore we add the user in the BZ CC list unless it is explicitely required (via user action) to remivrtne

**Comment by nbiton** [comment]
@franck-boullier So you agree that a case should be listed for a user if one of these three conditions applies? 
- The user is an assignee for this case
- The user is the reporter of this case
- The user is listed in CC for this case

**Comment by franck-boullier** [comment]
Side comment: I think we need to make sure that 
- we only get the open cases first and then give the option to include the closed cases next.
- limit the number of cases we fetch to a certain number (the 20 most recent cases maybe?) And then offer the option  to see the next page with the next 20 cases

Fetching ALL the cases for a given user might result in a very long list so we want to make sure that this would not cripple the perf...

**Comment by franck-boullier** [comment]
The PR53 works but fetches a long list of cases and is slow to load

**Comment by nbiton** [comment]
I added a limit for max 20 results. Let me know if the performance is acceptable in this state.

**Comment by franck-boullier** [comment]
Loading time is much faster with a limit for max 20 results.

We need to add a "see next" page for the next 20 results.
We could also make it a variable with a default value of 20 and give the option for the user to change this value from 20 to 50 to 100 for instance...

**Comment by nbiton** [comment]
It was completed by #53
