### ISSUE TITLE
Convert to premium - User wants to add his/her own logo to Inspection Reports

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#510]
# The problem:

How can we make it easy for free user to convert to Premium user when the user wants to have a personalized logo for the Inspection Reports he/she creates?

**Comment by yvonnechia** [comment]
<img width="626" alt="screen shot 2018-10-08 at 3 04 48 pm" src="https://user-images.githubusercontent.com/43780040/46595561-8a4a3d00-cb0b-11e8-8d61-e2d4898caba4.png">

**Comment by nbiton** [comment]
I can't find the designs for actually changing the logo, once the user was converted to premium. Can anyone please share a link?

**Comment by franck-boullier** [comment]
@nbiton I think you can find it here: https://realtimeboard.com/app/board/o9J_k0ckGU4=/ in the "Upgrade to Premium" section
@kiatlim can you help?

**Comment by franck-boullier** [comment]
![image](https://user-images.githubusercontent.com/31331637/47762971-9932a280-dcf9-11e8-81b0-1eb4db34a5f0.png)

**Comment by nbiton** [comment]
![screenshot from 2018-10-31 10-42-58](https://user-images.githubusercontent.com/2662819/47763014-cbdc9b00-dcf9-11e8-9489-7f17cf93bdf6.png)
@franck-boullier It actually appears to be this section here.
I can't find this on Figma though

**Comment by franck-boullier** [comment]
@kiatlim and @yvonnechia can you help us find the designs in Figma so @nbiton can work faster?
Thanks!

**Comment by kiatlim** [comment]
@nbiton it starts from here but somehow the text are wonky now, let us fix it in a bit. 
https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=631%3A625

**Comment by yvonnechia** [comment]
@nbiton hi, fixed the text and alignment. You can try again:
https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=874%3A5

**Comment by franck-boullier** [comment]
It is now possible to change logo on Inspection Reports
