### ISSUE TITLE
Search bar not functional on the 'Case' page

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#517]
# The issue:

After the search functionality was implemented (see #167) we now have a working simple search functionality for units BUT
- The search icon is also visible in the 'Case' Page
- When clicking on the Search icon on the 'Case' Page, the search is activated
- When typing search keyword in the search bar nothing happens

![image](https://user-images.githubusercontent.com/31331637/45738346-ba946f00-bc22-11e8-9e64-de22ca207ee1.png)

# Short term fix:

- Remove the Search icon from the 'Case' page

**Comment by sophieyang0813** [comment]
@franck-boullier @nbiton @kiatlim  Does a user search for a **unit** or  a **case** in a search bar of the case page? 

If searching for a case, displaying a unit name along with a case title can be helpful. This can reduce confusion in the case of duplicate/similiar case titles. If so, what would be the design like? 

<img width="322" alt="screen shot 2018-10-01 at 4 46 04 pm" src="https://user-images.githubusercontent.com/25441733/46278715-8bbeb700-c599-11e8-8234-9d35a9c72557.png">

**Comment by franck-boullier** [comment]
@kiatlim any recommendation/suggestion for a design for the search interface on the case page?

**Comment by kiatlim** [comment]
@franck-boullier @sophieyang0813 yes, if we would like to search for cases, then the case results should be accompanied by the unit. We currently don't have another way of presenting cases with units so think of the results screen like the case landing but filtered.

**Comment by franck-boullier** [comment]
fixed in PR #678
