### ISSUE TITLE
"Category" and "Sub-category" selection needs to be easier

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#525]
I think it's not user-friendly for new users. I found myself thinking for too long which categories fot my actual case. Not a good experience

**Comment by franck-boullier** [comment]
@kiatlim any suggestion?

**Comment by kiatlim** [comment]
Changing it to a single field where the user can expand and collapse each category might work better. The tree menu thing we talked about: https://material.angular.io/components/tree/overview may be a solution?

Other than that is to re-organise the categories and keep it simpler but I don't have the context as to which categories are more important and used by the other to make a decision on the categorisation naming.

**Comment by franck-boullier** [comment]
> Changing it to a single field where the user can expand and collapse each category might work better. The tree menu thing we talked about: https://material.angular.io/components/tree/overview may be a solution?

Might be a good idea... @nbiton can we do an A/B testing for that somewhere down the road?

**Comment by franck-boullier** [comment]
Ideal Solution should be auto-categorization based on the case title, case description and pictures of the case but this might take a significant amount of time to implement...

@kiatlim can you start thinking about how would the UI/UX look if we get this auto categorization working from a back end perspective?

**Comment by kaihendry** [comment]
Shouldn't they be more like labels? Labels seems the order of the day today. If they have to be one or the order thanks to a schema issue, what are the consequences if it is omitted or filled in with some placeholder?

**Comment by franck-boullier** [comment]
> Shouldn't they be more like labels?

Sure why not, this should not impact the back end side of things as it exist today IMO, we'll have to see what is the recommended UX / User flow first and decide how we can best implement that in the back end: we have both options available anyway...

**Comment by nbiton** [comment]
> @nbiton can we do an A/B testing for that somewhere down the road?

I guess much down the road... we have'nt setup a way to do A/B testing yet

**Comment by kaihendry** [comment]
aka the datalist paradigm? https://leaverou.github.io/awesomplete/

Here's my demo: https://dl.natalian.org/?polyfill=true

**Comment by ongdominic** [comment]
![screenshot 2019-01-22 at 12 40 04 pm](https://user-images.githubusercontent.com/46714451/51512831-e9c22380-1e42-11e9-913b-488bec29a1e7.png)

**Comment by ongdominic** [comment]
With this, at one glance users can see the categories and sub-cat together so they won't have to do a trial and error to find the best fit.

**Comment by ongdominic** [comment]
This will be shown at the end of the selection 
![screenshot 2019-01-22 at 12 43 09 pm](https://user-images.githubusercontent.com/46714451/51512933-4f161480-1e43-11e9-947a-94ed839db1df.png)

**Comment by ongdominic** [comment]
If we were to add a search bar, this will how it looks.

![screenshot 2019-01-22 at 12 45 57 pm](https://user-images.githubusercontent.com/46714451/51513037-b92eb980-1e43-11e9-9558-c9814786b9f9.png)

**Comment by franck-boullier** [comment]
This looks way too scary/complex to me :fearful: 

> ![screenshot 2019-01-22 at 12 40 04 pm](https://user-images.githubusercontent.com/46714451/51512831-e9c22380-1e42-11e9-913b-488bec29a1e7.png)

**Comment by franck-boullier** [comment]
List of the Case Categories and Case Types have been re-vamped based on user feedbacks
