### ISSUE TITLE
Make invitations look more inviting

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#531]
The invitations will be probably the most common way of new users to encounter Unee-T for the first time, so it's definitely important to have a good first impression.

This is how the current invitation email looks like
![screenshot from 2018-09-25 12-16-34](https://user-images.githubusercontent.com/2662819/45992842-64aa4600-c0be-11e8-987e-250ee7e56136.png)

Issues I see:
* The subject line doesn't suggest what this is about. A new user will not understand why an entity called "Unee-T" is sending emails about "New Case".
* "Unee-T" shown as the sender of the email looks unfamiliar.
* The email lacks anything to assure the user it is really coming from the invitor, aside from mentioning the invitor's email.
* The format looks unpolished, creates a connotation with spam emails.
* "this link" is small and hardly looks like a call for action.
* The full link with the invitation code is the same size as the rest of text. I think that the long hash might look suspicious to many users, as it is more associated with spam/phishing emails. It should probably appear more like a footnote to the rest of the email.
* There's no option for the invitor to attach a personal message to the invitation (unlike to how many other services do it).

I believe we should figure out how to avoid losing users at the invitation phase, as they won't feel comfortable of opening/accepting the invitation.

**Comment by kaihendry** [comment]
Link to template https://github.com/unee-t/frontend/blob/master/imports/util/email-invite.js

I personally don't like the line breaks which makes it feel unnatural.

Like the "attach a personal message" sentiment.

Be good if the from/reply-to address was perhaps a human face.

Be good if there was a way for the inviter to grab that URL to send via WhatsApp or whatever other side medium they choose.

**Comment by franck-boullier** [comment]
@kiatlim can you give us some recommendations/suggestions?

**Comment by franck-boullier** [comment]
See also #437 on the same topic

**Comment by franck-boullier** [comment]
Design has been updated in the latest version of the master.
See #828 and #814 and #815
