### ISSUE TITLE
Email notification is using the incorrect name for the unit

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#535]
# The problem

When we send a notification message we indicate the name of the unit.

## Expected result:

The name of the unit should come from the Mongo DB which is the source of truth for that information.

## Actual result:

The name displayed in the name from the BZ back end

![image](https://user-images.githubusercontent.com/31331637/46055380-4f94ec00-c17e-11e8-8850-d1ffd460df36.png)

# More information:

This is also related to #421 and #394

**Comment by kaihendry** [comment]
Please link to the template to make it crystal clear.
https://github.com/unee-t/frontend/blob/master/imports/util/email-invite.js#L10

**Comment by franck-boullier** [comment]
Looking at that code I suspect that the unit description is also coming from the BZ back end which is not the expected behavior either: the source of truth for information related to units should be the MongoDB

**Comment by nbiton** [comment]
That seems to be correct. Currently, the notification handler does not query Mongo for fetching the unit's metadata, it just uses the information sent with the notification payload.

**Comment by kaihendry** [comment]
IIUC this is the metaData struct:

```
{
        "_id" : "j4JNasKaogweAmy9t",
        "bzId" : 268,
        "bzName" : "A Test Unit - SMB-268",
        "city" : "",
        "country" : "",
        "createdAt" : ISODate("1999-09-09T09:09:09Z"),
        "displayName" : "A Test Unit - SMB",
        "moreInfo" : "",
        "ownerIds" : [
                "Zun9DGWunPnrR8Lv5",
                "QMDJ2csjRSv3Jx6Fz"
        ],
        "state" : "",
        "streetAddress" : "",
        "unitType" : null,
        "zipCode" : ""
}
```

Are we using bzName for unitName & displayName for unitDesc or were there some other plans to print the address?

**Comment by franck-boullier** [comment]
fixed in the latest version of the master.
See #814
