### ISSUE TITLE
Pilot User - Impossible to access Finalized Report (PROD)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#546]
# The problem:

After roll out of the [latest version of the MVP](https://github.com/unee-t/frontend/releases/tag/beta-2018-09-30), user is not able to access the finalized Inspection Reports that were created in the past

- Preview is empty
![image](https://user-images.githubusercontent.com/31331637/46265943-c9055380-c55d-11e8-9ba7-c259ffed8f1e.png)

- Error Message:

![image](https://user-images.githubusercontent.com/31331637/46265953-dc182380-c55d-11e8-8aab-00077047ef4c.png)

More information are available in the [HelpScout ticket](https://secure.helpscout.net/conversation/675102717/399/?folderId=2155394).

**Comment by nbiton** [comment]
Should be fixed now. I have no previously finalized report to access on prod so I could verify it completely though

**Comment by franck-boullier** [comment]
Fixed in the latest release
