### ISSUE TITLE
Banner sized image

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#550]
We ideally need a banner or 2:1 sized Unee-T image, RE twitter:image in https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html

**Comment by kaihendry** [comment]
Also a header which is 3:1 https://help.twitter.com/en/managing-your-account/how-to-customize-your-profile

**Comment by kiatlim** [comment]
This one is for the twitter account profile header, need to test it out as there could be some cropping.
![unee-t twitter header](https://user-images.githubusercontent.com/641679/46270602-ee548a80-c57a-11e8-9021-d8ddfa5a5da4.jpg)

This is for the meta default image for social sharing, I think FB and Twitter could be sharing the same, need to check on FB sizes. 
![unee-t twitter share large](https://user-images.githubusercontent.com/641679/46270603-ee548a80-c57a-11e8-9cc8-08886320299f.jpg)

**Comment by kiatlim** [comment]
Another twitter header version without text.
![unee-t twitter header no text](https://user-images.githubusercontent.com/641679/46270872-4344d080-c57c-11e8-9201-a91b5788af00.jpg)

**Comment by kiatlim** [comment]
@franck-boullier any thoughts on the text? and can try updating the twitter profile header to see how it goes?

![unee-t twitter header v2](https://user-images.githubusercontent.com/641679/46295098-dd7f3580-c5c9-11e8-8760-dad7e300a77f.jpg)

**Comment by franck-boullier** [comment]
Not convinced by this text TBH...
We decided against "issue" a long time ago and for very good reasons.

Let me give it some more thoughts again

**Comment by franck-boullier** [comment]
Assuming there are no constraints in the format or lenght of the text, my recommendation is to stay consistent with what we have on the website.

H1: "Smarter Communication with Unee-T" (or "Smarter Communication" if the first option is too long)
H2: "The new way to record and manage issues in your properties"
H3: "Free if you create less than 5 units. Unlimited number of cases. Unlimited number of Inspection Reports"

**Comment by franck-boullier** [comment]
@kaihendry feel free to reopen if needed
