### ISSUE TITLE
Buggy log-in when joining a case as an invited collaborator

### ISSUE THREAD

**Issue by yvonnechia** [unee-t/frontend#564]
View screen recording: 

https://cl.ly/a9de3b4acc4d

**Comment by franck-boullier** [comment]
We need to fix this ASAP ---> this certainly has an impact on the conversion ratio invited user/active user.

It is critical that invited users have a super easy way to start working on a case.

Suggestion: remove the step where we ask the invited user to enter his/her first and last name and just send the user to the case directly.
This is possible now that we have a way to edit the user profile.
@kiatlim any comment on that idea?
@nbiton how long will it take for us to implement that quick fix {remove the step where we ask the invited user to enter his first and last name before he/she can see a case)?

**Comment by kiatlim** [comment]
@franck-boullier removing the first name last name input is a good way to remove obstacle and we can always highlight to the user to update their profile later in the screen.

Another thought was since it's the issue of the modal window thats causing it, we can move this into a full screen page? Maybe the technical effort is lesser to implement this?

**Comment by nbiton** [comment]
Fixing the modal window should be fairly straightforward, removing it should be even quicker.

I could do it myself today if it's urgent

**Comment by franck-boullier** [comment]
> I could do it myself today if it's urgent

Let's do this as a quick fix for this issue.
I still think that this could be a good first case for Liron: it's urgent but you have more important features to work on @nbiton.
My assumption is that if Liron takes this one this can still be done in one day anyway, correct me if I'm wrong

**Comment by nbiton** [comment]
Which do we prefer? Removal or fixing?

> My assumption is that if Liron takes this one this can still be done in one day anyway, correct me if I'm wrong

I can check with him later today. I think that since this would be the first code contribution into the project, it might take longer to get in properly. An urgent feature/fix isn't ideal for this

**Comment by franck-boullier** [comment]
> Which do we prefer? Removal or fixing?

Removal as a temporary fix until we have an improved UX/User flow for that.

> An urgent feature/fix isn't ideal for this

Your call @nbiton
