### ISSUE TITLE
If user tries registering after attempting to login, the user is forced to re-enter details

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#569]
We shouldn't make users re-enter the same information in the case the user wants to register instead of logging in.

<img src=https://s.natalian.org/2018-10-05/1538705973_2558x1406.png>
<img src=https://s.natalian.org/2018-10-05/1538705994_2558x1406.png>

**Comment by franck-boullier** [comment]
Fixed in the current version of the Master
