### ISSUE TITLE
Finalized Inspection Reports are not visible to invited user

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#572]
# The issue:

- User A creates an inspection report PASSED
- User A selects users to sign the Inspection Report PASSED
- All selected user sign the IR PASSED
- User A finalizes the IR PASSED
- User A sends the IR to the users who signed the report (who should be pre-selected by default). This includes User B.
- User B receives an email notification PASSED
- User B logs to Unee-T PASSED
- User B check the list of finalized IR and see the IR which was just signed FAILED.

**Comment by nbiton** [comment]
This will be resolved in conjuction with #443

**Comment by nbiton** [comment]
This was definitely resolved by #583
