### ISSUE TITLE
Inspection Report - Impossible to see larger version of the pictures

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#576]
# The problem:

User wants to see a larger of the version of a picture taken during an inspection report

- Go to Inspection Report
- Click/tap on a picture

## Expected Result:

A larger version of the picture is displayed.
User can zoom in on the picture to see more details
User can save picture if needed.

## Actual Result:

Nothing happens

**Comment by kaihendry** [comment]
This is at the Preview stage, correct?

IIUC the solution would be to have links that open the full image in a new tab? https://github.com/unee-t/inspectionreportgenerator/blob/master/templates/signoff.html#L308

**Comment by nbiton** [comment]
We'd probably want to keep the user in the app, like we're doing for case attachments. There wasn't a description of a maximized view for report attachments, which is why this wasn't implemented so far.

**Comment by franck-boullier** [comment]
> This is at the Preview stage, correct?

Both at the preview and at the finalized stage: we need a way for the user to access the full version of the picture if/when needed regardless of the state of the IR.

> IIUC the solution would be to have links that open the full image in a new tab? https://github.com/unee-t/inspectionreportgenerator/blob/master/templates/signoff.html#L308

That seems like a reasonable way to do it yes.

**Comment by franck-boullier** [comment]
> We'd probably want to keep the user in the app, like we're doing for case attachments

Yes, I agree with that

**Comment by franck-boullier** [comment]
Add the "critical" case to this issue:
As of today this is the number one issue reported by users ---> once a picture is taken in Unee-T they are never able to see the lager version of the picture anymore in the Inspection Reports

**Comment by franck-boullier** [comment]
fixed in the latest version of the master. See https://github.com/unee-t/frontend/commit/ac8d374138d5a70308086bdc48b1e648dad6fe71
