### ISSUE TITLE
UI hangs after login for "uilicious-test@inboxkitten.com"

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#584]
Currently affect both "https://case.dev.unee-t.com/case" and "https://case.demo.unee-t.com/case" specific to the following account : "uilicious-test@inboxkitten.com", just login and the system hangs at loading "cases"

Affects: chrome, firefox, edge, and safari

Minimum test steps can be found here (no login required) : https://snippet.uilicious.com/test/public/24cGksmsmiXe4y6XXuCShx

Error message in chrome

![screen shot 2018-10-10 at 3 41 50 pm](https://user-images.githubusercontent.com/17175484/46720455-2490b900-cca3-11e8-8e1d-5bd9579f7008.png)

- Checked that this does not affect newly created users (a seperate test case). 
- Issue was detected at : 10 Oct, 3pm
- last successfully log in was : 10 Oct, 10 am
- Last deployment was : [Build 583 at 9 Oct, 10pm](https://travis-ci.org/unee-t/frontend/builds/439153794), meaning no code change from last successful login.

Changes to this specific account since last successful login.
- Manually created a unit, and a case. However I was unable to reproduce this issue, using additional test accounts.

**Comment by franck-boullier** [comment]
Fixed
