### ISSUE TITLE
Twitter banner uses incorrect image

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#585]
The current image is this:
![image](https://user-images.githubusercontent.com/31331637/46722090-3e33ff80-cca7-11e8-8696-fb0cec3a2f61.png)

We should use this background instead:
https://unee-t.slack.com/archives/C76A4FZK9/p1538546147000100

![image](https://user-images.githubusercontent.com/31331637/46722192-86532200-cca7-11e8-8a4e-b3e554e2d0f5.png)

With the Unee-T "Bubble" logo on top (similar to current image)

**Comment by kiatlim** [comment]
![unee-t twitter share large](https://user-images.githubusercontent.com/641679/46795292-5e81be00-cd7c-11e8-946f-6454fa2a0740.jpg)

**Comment by kiatlim** [comment]
@franck-boullier Does this work?

![unee-t twitter share large](https://user-images.githubusercontent.com/641679/46795585-13b47600-cd7d-11e8-8328-f2f1ae042a51.jpg)

**Comment by franck-boullier** [comment]
yes it works
thanks!

**Comment by franck-boullier** [comment]
Fixed in the current version of the master
