### ISSUE TITLE
Navigation - We need a way to go back to the list of cases

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#59]
In PR58, the list of case works and could be the default 'go to' page for the mobile interface.

We need to have an easy way to navigate back to this page (list of open cases) when we are on a 'case' page.

Maybe we could make the Unee-T logo and make it clickable to do that...

**Comment by nbiton** [comment]
I think I'll change the logo to a back button on the case messages view. That fits with the design, and that was my plan.

**Comment by franck-boullier** [comment]
This works now
