### ISSUE TITLE
Unit creation - Need to signal the user that we are processing the user request

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#590]
# The problem:

When user creates a unit user is requested to enter several field and the click on 'Create Unit' button

Once user has done that there is a delay before going on to the next screen (we need time to process the request).
Because there is no feedback to the user on the screen the user gets the impression that his/her actions have not been successful and tries to click on the 'Create Unit' button several time.

# Suggested solution:

## Option 1:

Display a 'loading' icon once the 'Create Unit' button has been pressed

## Option 2:

Because creating a new unit takes time (it could be several seconds) use a couple intermediary messages like:
- "Unit is being created"
- "Default Roles for the unit are being created"

That would showcase to the user that some things are happening and that the application is not frozen.

**Comment by sophieyang0813** [comment]
@franck-boullier Afternoon! I don't see the same problem? 1) A loading icon replaces `add unit` button when the form was submitted. 2) Another loading icon in the blank page shows up, before transitioning into newly created unit page.  (this can be tested at https://unee-t-pr-565.herokuapp.com/unit)


<img width="150" align='left' alt="screen shot 2018-10-17 at 2 20 15 pm" src="https://user-images.githubusercontent.com/25441733/47066247-0c2b1c00-d218-11e8-825a-1d01f2a41f8a.png">
<img width="150" align='left' alt="screen shot 2018-10-17 at 2 20 27 pm" src="https://user-images.githubusercontent.com/25441733/47066189-e69e1280-d217-11e8-963b-e7f10967d44b.png">
<img width="150" align='left'  alt="screen shot 2018-10-17 at 2 24 24 pm" src="https://user-images.githubusercontent.com/25441733/47066377-717f0d00-d218-11e8-95c0-45d9f8cd1520.png">

**Comment by kaihendry** [comment]
Yes, I can confirm there is a loading interaction, though I do feel it's unacceptably slow. Just wondering if anything can be done, other than a whirring circle. I guess not (easily) so we move on.
