### ISSUE TITLE
email notification - content of new message is not visible enough

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#591]
# The problem:

When a user receives a notification, it is not obvious to see what the notification is about.

![image](https://user-images.githubusercontent.com/31331637/46942120-3a392080-d09f-11e8-9d71-f89f6aa297bb.png)

# Suggested solution:

Highlight the message better, 

## Option 1: placing the message in between clear separators:

Hi Franck Admin,

New message by Franck Boullier:

`---
Yes, I'll be there to open the doors
`---

Please follow https://case.unee-t.com/case/69090 to participate.

Unee-T is a combination of a To Do list, a Messaging System and an Issue Tracker when something needs to be done in your properties

To opt out of receiving "caseNewMessage" emails, please visit https://case.unee-t.com/notification-settings 

## Option 2: highlight the message is __bold__:

Hi Franck Admin,

New message by Franck Boullier:

__Yes, I'll be there to open the doors__

Please follow https://case.unee-t.com/case/69090 to participate.

Unee-T is a combination of a To Do list, a Messaging System and an Issue Tracker when something needs to be done in your properties

To opt out of receiving "caseNewMessage" emails, please visit https://case.unee-t.com/notification-settings 

## Option 3 ????:

Feel free to suggest alternatives!

**Comment by kaihendry** [comment]
I like bold in HTML and perhaps an indent or quote `>` in the text version.

**Comment by franck-boullier** [comment]
> I like bold in HTML and perhaps an indent or quote > in the text version.

Let's implement that ASAP then ---> quick win
