### ISSUE TITLE
Random REST API error and login slow down for past 

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#596]
Might be related to : https://github.com/unee-t/bugzilla-customisation/issues/75
And maybe more of load issue then an application bug.

Currently this is not consistent behaviour when viewed from a single test. And affects both dev and demo environment. At the login / signup step, it comes in 3 major forms.

Its rate of occurrence is however high enough when running 14 "user tests" concurrently, approximately half the tests will fail in one of the following steps.

**Login taking more then 15 seconds**
![screen shot 2018-10-19 at 11 31 55 am](https://user-images.githubusercontent.com/17175484/47196344-a0b98980-d392-11e8-964e-e923fc2dc9e1.png)

The "dont see" submit button is meant to pass if login took less then 15 seconds. The subsequent test step pass after 6 seconds, giving a very inaccurate approximate of 21 seconds to load the page after login. 

There been test where login failed beyond 30s as well

**Signup return REST API error**
![screen shot 2018-10-19 at 11 35 04 am](https://user-images.githubusercontent.com/17175484/47196429-0b6ac500-d393-11e8-9681-5dc97002cd00.png)

This is more consistent in occurrence, with the last known pass to be observed 10 hours ago in demo. As such this might be a completely seperate issue.

**Opening case**

Harder to replicate manually, but occur in historical reports randomly 
![screen shot 2018-10-19 at 11 41 01 am](https://user-images.githubusercontent.com/17175484/47196593-efb3ee80-d393-11e8-9ae8-1ea159df23a1.png)

**Creating a unit**

![screen shot 2018-10-19 at 11 52 43 am](https://user-images.githubusercontent.com/17175484/47196904-9b117300-d395-11e8-8945-24d70a8768ea.png)

On submission

**Comment by PicoCreator** [comment]
Note : currently trying to isolate each issue - and seperate them out as needed

**Comment by franck-boullier** [comment]
fixed
