### ISSUE TITLE
REST API error on signup - in demo environment

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#597]
**Environment :** Demo 
**Test case :** Signup with a random user, expected test to succeed.

![](https://user-images.githubusercontent.com/17175484/47196429-0b6ac500-d393-11e8-9681-5dc97002cd00.png)

Relevant Cloudwatch Error message:
```
'{"code":304,"documentation":"https://bugzilla.readthedocs.org/en/5.0/api/","error":true,"message":"Sorry, you aren\'t a member of the \'editusers\' group, and so you are not authorized to add new users."}',  
```

Full cloudwatch logs : https://media.dev.unee-t.com/2018-10-19/demo-meteor.txt
(Traced with @kaihendry)

Note: Originally reported under #596

**Comment by kaihendry** [comment]
As mentioned in #598, there is no progress feedback when you click to Login. I find this jarring.

**Comment by franck-boullier** [comment]
Fixed
