### ISSUE TITLE
Unable to access a unit page in latest version of the master

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#611]
# The problem:

- Log in as leonel
- Go to the unit page
- Click on the first unit

## Expected result:

See the details about the units

## Actual result:

Endless loading page
![image](https://user-images.githubusercontent.com/31331637/47451901-800e8b00-d7fb-11e8-8733-cdf1ea1b0bfc.png)

**Comment by franck-boullier** [comment]
Issue is still there after restoration of a clean BZ database and Mongo reset.

**Comment by nbiton** [comment]
The problem is caused by not initializing "statusFilter" properly in unit.jsx

**Comment by franck-boullier** [comment]
fixed in the lastest version of the master
