### ISSUE TITLE
Unable to invite users to new case

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#613]
**env:** case.dev.unee-t.com
**browser:** chrome & firefox

In a newly created user and case, I am unable to invite another user via email.

![55-click-beforeaction-9awgfkh1hyvmuvmi32pejz-target 156 468](https://user-images.githubusercontent.com/17175484/47476396-c4794580-d852-11e8-8dd0-44fca0a7cf11.png)
![56-see-endin-xsrhj4ub3zmigcgy6o2rqe](https://user-images.githubusercontent.com/17175484/47476397-c5aa7280-d852-11e8-98ed-3dc658f9c25d.png)

No noticeable JS / console error / network submission - it might be a UI bug

**Comment by kaihendry** [comment]
Just to confirm this issue. Also it's not because the email isn't verified, surprisingly.
https://s.natalian.org/2018-10-25/1540444191_2558x1406.png

**Comment by kaihendry** [comment]
I was testing and I think it's working again now.

**Comment by PicoCreator** [comment]
Thanks for quick fix - validated the following in dev environment

- authentication
- signup (of all roles)
- creation of case (of all roles)
- invitation of users to created case via email

Several test cases are currently shown to fail on our dashboard, but i have manually validated them as false negative caused by missing testing pre created testing data.
