### ISSUE TITLE
Regression : Unable to load "https://case.dev.unee-t.com/unit"

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#619]
**Env:** dev only (demo has been checked)
**Browsers:** Chrome & Firefox
**Last succesful test:** 2AM Singapore

Login to an existing account, and navigates to unit page - currently hangs

![screen shot 2018-10-29 at 2 13 07 pm](https://user-images.githubusercontent.com/17175484/47632401-d6295880-db84-11e8-9114-c5ff10af3f91.png)

Public test code found here (no login required) : https://snippet.uilicious.com/test/public/DozsHppp5ed8y16sUZs8e6

**Comment by nbiton** [comment]
Hi @PicoCreator ,
Our DEV environment was reset to back to basic seed data due to an issue we had last week. Some user's data was retained though. Please use new users with new units and cases for tests, as previous ones might be faulty due to data integrity issues on DEV.

**Comment by PicoCreator** [comment]
Thanks =) and validated with a new account : https://snippet.uilicious.com/test/public/H5DonYEwdx6o8m28eYjFMp

Closing issue
