### ISSUE TITLE
Backup Cloudinary assets to S3

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#62]
We are not using my account: kai.hendry@unee-t.com

I guess we are using yours Franck? Can you put the username / password into SSM?
https://ap-southeast-1.console.aws.amazon.com/ec2/v2/home?region=ap-southeast-1#Parameters:sort=Name

**Comment by kaihendry** [comment]
Oh crap, this backup capability is only for paid plans https://cloudinary.com/console/upgrade_options

**Comment by franck-boullier** [comment]
I'll look at that next week...

**Comment by kaihendry** [comment]
@franck-boullier we should get this backup going on prod...

**Comment by franck-boullier** [comment]
dang... forgot about that...

**Comment by franck-boullier** [comment]
@kaihendry not sure which plan I should select...
Let's move this to Slack anyway as this is an infra conversation that is not directly related to the code....

**Comment by kaihendry** [comment]
Be good to paying on couldinary.prod@unee-t.com so that backups can be established of production data.

**Comment by franck-boullier** [comment]
@kaihendry Prod account upgraded
