### ISSUE TITLE
Demo unit page - does not show any units

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#620]
**Env:** demo only (dev testing blocked by #619)
**Browsers:** Chrome & Firefox

Login to an existing account, and navigates to unit page - was expected to see list of units, got blank instead

![screen shot 2018-10-29 at 2 30 50 pm](https://user-images.githubusercontent.com/17175484/47632970-43d68400-db87-11e8-8936-64247172bd0f.png)

Was expecting the unit list - as seen inside cases

![screen shot 2018-10-29 at 2 30 52 pm](https://user-images.githubusercontent.com/17175484/47632979-4d5fec00-db87-11e8-9384-33f1da5bf6eb.png)

Public test code found here (no login required) : 
https://snippet.uilicious.com/test/public/EvcXG2VTnhmbaCCB9ZDkEa

**Comment by PicoCreator** [comment]
Note : This might be related to https://github.com/unee-t/frontend/issues/394

Where the old "case" page is loading from the bugzilla DB, and the new "unit" page loading from the newer MEFE interface

**Comment by kaihendry** [comment]
Would appear the user_group_map has truncated on demo.

**Comment by franck-boullier** [comment]
?!?! 🤔
Any idea how we can find how this happened?

**Comment by PicoCreator** [comment]
Hmm, if "user_group_map" is a DB issue, i suppose I can close this? - strictly speaking it isnt an app issue - made irrelevant as well due to demo DB reset

**Comment by kaihendry** [comment]
Demo is restored with the [new fixed schema](https://raw.githubusercontent.com/unee-t/bz-database/master/db%20snapshots/unee-t_BZDb_clean_with_demo_users_and_unit_current.sql), so theoretically this shouldn't happen again.
