### ISSUE TITLE
The closed cases in the Unit page are displayed like open cases

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#623]
# The problem:

## Expected result:

Closed cases are displayed with their title stroked through

![image](https://user-images.githubusercontent.com/31331637/47652987-5fab4b80-dbc2-11e8-94e7-03509b5705bd.png)

## Actual Result:

![image](https://user-images.githubusercontent.com/31331637/47652834-fe837800-dbc1-11e8-8bd4-40f5dd077ffd.png)

**Comment by nbiton** [comment]
I don't think it's a new issue though. If it never was like that, I think different tags will be more suitable (UI, enhancement)

**Comment by franck-boullier** [comment]
Closed in PR 625
