### ISSUE TITLE
"Unowned unit" - appearing on multiple accounts

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#630]
**Env:** dev

This might be a security concern, and maybe a race condition bug. When creating an account.

One of the units generated by test automation, ended up being without a "person" attached. As a result several accounts are able to see the unit.

For example : ft76sdaddauoi@inboxkitten.com , is a randomly generated account (did nothing)

It currently has access to : [UI-TEST] unit - 1540951369039-357

![screen shot 2018-11-02 at 10 49 19 am](https://user-images.githubusercontent.com/17175484/47891274-7fc25f80-de8d-11e8-9dd0-54f2c1cfc6d3.png)

Unit without "people" attached

![screen shot 2018-11-02 at 10 50 00 am](https://user-images.githubusercontent.com/17175484/47891277-8224b980-de8d-11e8-867d-c3bcbb010ebc.png)

**Comment by kaihendry** [comment]
Just reproduced this. New signup and I see:
https://s.natalian.org/2018-11-02/1541129604_2558x702.png

**Comment by franck-boullier** [comment]
Wow!
I'd like to better understand what might be the root cause of this. Thanks for spotting that @PicoCreator!

**Comment by franck-boullier** [comment]
this was most likely due to a race condition.

The unit has been deleted in the DEMO environment
