### ISSUE TITLE
Pictures - Impossible to zoom in on part of the picture

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#646]
# The problem:

When a user selects a pictures in Unee-T he/she is not able to zoom in on part of the picture to see specific details on the pic.

# Expected result:

Everywhere in Unee-T (in the conversation page, in the list of images for a case, in the inspection reports), when a user clicks on an image:
1- The image is made to be full screen
2- The user can pinch and zoom on the image to see details on the image if needed.

**Comment by kaihendry** [comment]
Selecting an image should just open the original image. From there you can scale. Though the user needs to be savvy enough to be able to go back.

**Comment by franck-boullier** [comment]
> Selecting an image should just open the original image.

I agree: it should, unfortunately it does not...

**Comment by nbiton** [comment]
> Selecting an image should just open the original image. From there you can scale. Though the user needs to be savvy enough to be able to go back.

Since we're ultimately opting for Unee-T to provide a full PWA experience, that's not a good solution. We'd need to avoid having the user navigating out of the app as much as possible.

**Comment by franck-boullier** [comment]
> We'd need to avoid having the user navigating out of the app as much as possible.

@nbiton I totally agree with that!

**Comment by franck-boullier** [comment]
This works
