### ISSUE TITLE
Make signup button more visible

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#658]
It seems that it doesn't attract enough attention

**Comment by kaihendry** [comment]
Animation ?

**Comment by kaihendry** [comment]
I've noticed sites like LinkedIn are like the opposite. Only option is to **Sign up**. You have to look hard to **Sign in**.

<img src="https://s.natalian.org/2019-01-04/1546569016_2558x1406.png" alt="LinkedIn">

I guess it goes without saying, if you have signed up, you should have automatically signed in. Furthermore if you have signed in, you really should not be seeing that "Please login to continue" page unless something has gone terribly wrong. i.e. there is no reason for the user EVER to be signed out.

**Comment by franck-boullier** [comment]
> there is no reason for the user EVER to be signed out.

I agree with that.
@kaihendry do we have a way to log/track the number of instances when a user is asked to log in?
Once we are able to measure that we'll be able to understand when/where/why it happens and fix this.

**Comment by kaihendry** [comment]
The meteor logs could allow us to see this. Thought the logging needs to be tweaked with some sort of 
"log in" action event field so we can filter on that.

Another approach is to use Google Analytics and attach an event there. Either way, I think @nbiton needs to weigh in.

**Comment by nbiton** [comment]
A user can be logged out automatically after an extended period after the initial login (should be 90 days atm). Also, switching browsers and devices can prompt the user to login again... I don't think we should make either sign up or log in harder to find

**Comment by ongdominic** [comment]
We discussion we had today the solution for this based on this logic:
For users who are looking to register for a new account, they are usually coming from the unee-t landing page vs coming from case.unee-t.com. So when a user clicks on register for an account on the landing page, it will land on a dedicated register for new account page. 

If a user lands on case.unee-t.com, we can assume that they already know what unee-t is about and has an existing account. So they will be focused on signing into their account.

**Comment by franck-boullier** [comment]
closing this for now based on our latest convo (see above comment)
