### ISSUE TITLE
Finalized Inspection Reports - open images opens an new tab

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#667]
# The problem:

After merging PR #666 into the master (not yet deployed in production) we now have a solution to open, enlarge and zoom on images in Unee-T BUT
when the image is from a finalized inspection report the behavior is different than when the image is form a draft inspection report or from a case.

## Expected result:

All images are behaving the same way (below is an example from a case note the URL)

![image](https://user-images.githubusercontent.com/31331637/49772229-6bdd0980-fd27-11e8-8ff8-8403cb270416.png)

## Actual result

For the images in finalized inspection reports the image opens in a different tab (note the URL)

![image](https://user-images.githubusercontent.com/31331637/49772286-ab0b5a80-fd27-11e8-9eb1-6bf7f4e0fd40.png)

@kaihendry , @nbiton any idea for a quick fix for that?

**Comment by nbiton** [comment]
It's probablt due to the temp fix @kaihendry deployed for the generated report html. It should happen for new reports after he reverted that change, but some finalized reports might be stuck that way.
It should be possible to counteract it with the code in MEFE to take control and override that behavior if it exists

**Comment by nbiton** [comment]
I should probably do it

**Comment by franck-boullier** [comment]
Reopening this issue: PR#671 does not fix the problem for existing inspection reports

# Failed Tests:

## Inspection Report finalized before PR 671 is merged to master:
- Log in as leonel in the DEV/Staging
- go to a [finalized inspection report](https://case.dev.unee-t.com/report/557/preview).
- Open an image:

### Expected result:

- Image opens inside the app

### Actual result:

- Image opens in a new tab

## Inspection Report finalized after PR 671 is merged to master:

- Go to a draft report
- Add a picture
- Finalize the report
- In the [finalized PDF version](https://case.dev.unee-t.com/report/228/preview) of the report click on the image

### Expected result:

- Image opens inside the app

### Actual result:

- Nothing Happens

# Other question:

@nbiton what happens if a user download the PDF report on his/her device?|
Expected result: if user clicks on the image in the PDF report then he/she is taken to the image inside the Unee-T app.
Can you confirm that this assumption is correct?

**Comment by nbiton** [comment]
I just debugged the issue and figured out it's being caused by cross-domain security measures. The html content loaded from media.dev.unee-t.com or media.unee-t.com is not detected as the same domain as the one the UI is served from, and therefore child iframe scripting which this feature is based on is not working.

@kaihendry any idea on how we can set it up so the browser's detecting the export htmls as server from the same domain? (see https://stackoverflow.com/questions/648899/a-question-about-cross-domain-subdomain-ajax-request#answer-2392911 for ideas)

**Comment by nbiton** [comment]
We'll also need to figure out how to retroactively apply this to all **existing** html exports as they won't be affected by new changes to the export generator...

**Comment by nbiton** [comment]
> Expected result: if user clicks on the image in the PDF report then he/she is taken to the image inside the Unee-T app.
Can you confirm that this assumption is correct?

@franck-boullier no, that's an incorrect assumption. Nothing would happen currently

**Comment by franck-boullier** [comment]
> although PDFs generated during the time IR exports contained embedded links would open the image directly in a new tab (not the app).

OK we should restore that functionality: it's key that user are able to access the images in the inspection  report.
This is a show stopper: we can't push that in prod until we have a way for user to access images ---> external links are wayyyy better than nothing

**Comment by kaihendry** [comment]
RE https://github.com/unee-t/frontend/issues/667#issuecomment-447629114 CORS

I don't quite understand the circumstances, a minimal example would be good. I *suspect* CloudFront is not propagating the CORS headers and I need to white list them? https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-cors

**Comment by franck-boullier** [comment]
fixed confirmed to be working
