### ISSUE TITLE
Invited email not being sent on dev environment

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#669]
<img src="https://media.dev.unee-t.com/2018-12-11/uit-tenant-1544519919126-2@inboxkitten.com.jpg">

All I see in the logs is:

```
User for uit-tenant-1544519919126-2@inboxkitten.com was created successfully
new user created for uit-tenant-1544519919126-2@inboxkitten.com

```
The sender `db.users.findOne({'emails.address': 'uit-owner-1544519919126@inboxkitten.com'})` is verified.

**Comment by kaihendry** [comment]
I believe this is some regression due to https://github.com/unee-t/bz-database/pull/97#issuecomment-445746482 @franck-boullier 

https://s.natalian.org/2018-12-11/1544523154_2558x1406.png


In the [invite lambda](https://github.com/unee-t/invite) [logs](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=/aws/lambda/invitefromqueue_invite;stream=2018/12/11/[$LATEST]06b5e60d842248998bd6d44a6d681ecd;start=2018-12-10T09:54:55Z) I see **Task timed out after 60.05 seconds**.

It appears to get stuck.

**Comment by franck-boullier** [comment]
> I believe this is some regression due to unee-t/bz-database#97 (comment) 

@kaihendry I need to know more to debug this...

> It appears to get stuck with no SQL error details.

OK what can we do then? 
My initial reaction is that if there is not SQL error details then it's probably not a SQL error at all :thinking:

**Comment by kaihendry** [comment]
Sorry, this has been fixed. The cause was a security group change which caused the lambdas to timeout.

Lambdas timing out whilst connecting to a database? Like to do with some devops configuration error on my part.
