### ISSUE TITLE
Finalized Inspection Reports - Impossible to zoom in on the image for some IR

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#680]
# The Problem:

For some Inspection Reports that were finalized a while ago, it's not possible to zoom in on the pictures.

Example:
![image](https://user-images.githubusercontent.com/31331637/50681275-de4eba00-1045-11e9-89ab-eeaeda60ebe6.png)

**Comment by nbiton** [comment]
Yes, those are broken. The only way to fix those is to find a way to individually manipulate each and every one of those htmls stored on S3

**Comment by franck-boullier** [comment]
> The only way to fix those is to find a way to individually manipulate each and every one of those htmls stored on S3

Who can help us do that? @kaihendry?

**Comment by kaihendry** [comment]
All IRs have been regenerated on s3://prod-media-unee-t/

**Comment by franck-boullier** [comment]
Report have been re-generated.
It is now possible to open existing pictures in old Inspection Reports.
It might be necessary to clear the browser cache on the user's device to make sure that this works as intended.
