### ISSUE TITLE
User cannot scroll invite modal

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#682]
Sounds similar to #135

<img src="https://media.dev.unee-t.com/2019-01-07/scoll-missing.png">

This is customer issue [# 1546](https://secure.helpscout.net/conversation/722351838/1546?folderId=2155397) in Help scout.

**Comment by franck-boullier** [comment]
fixed in https://github.com/unee-t/frontend/releases/tag/beta-2019-05-23
