### ISSUE TITLE
Inviting more than one user - email address of the previously invited user is still there

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#683]
Issue [# 1558](https://secure.helpscout.net/conversation/745363816/1558?folderId=2155397) on Helpscout

```
The previous person I invited (salim, for example) will still appear
after you click "invite more users".

Then, I invited another person using the same window and it hanged.

I have to refresh at least two times before I can invite another person.

What should have happened?

The previous person's email address should not appear when you click
"invite more users" and should not hang when you replace the person's name.
```

**Comment by PicoCreator** [comment]
Looking into this issue - as franck renamed in the title : its the input field not clearing, after inviting an additional user. 

Additional user invite is still working (if filled with a different email)

----

Suggested fix: Clear the input field, when clicking "invite more users"

**Comment by lironz** [comment]
there are 3 components in the form - email, role & tenant
non of them is being cleared.

do we want all 3 fields to be cleared or just the email field ?
