### ISSUE TITLE
Support a large amount of cases for the initial load time

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#684]
This is related to a poor customer UX communicated via Helpscout [#1559](https://secure.helpscout.net/conversation/748000322/1559)

**Comment by nbiton** [comment]
First we'll make the rendering of the cases only show X number of units at once and implement a virtual scroll mechanism to draw the rest

**Comment by franck-boullier** [comment]
Tests with Nath doesn't seem to show any visible improvements unfortunately... Reopening this

**Comment by nbiton** [comment]
As far as I can tell by logging in as Nath, there's a very significant improvement. The "scripting time" (most of the time the preloader animation seems frozen, just before the list appears) has dropped to 1.5s to 2.5s.
Total time to list presentation has dropped to 11s-13s. (Tested on desktop Chrome)

**Comment by nbiton** [comment]
Even though, I would still not close this bug, as there's definitely a lot more to do to reach optimal performance.

**Comment by franck-boullier** [comment]
@nbiton we should definitely implement something like what's described here: https://youtu.be/-AkHdG7MNCY?t=311

Thanks @kaihendry for finding this

**Comment by nbiton** [comment]
That's nice, but pretty irrelevant to this issue. It's fairly easy to track down how much time it takes for the browser to load the data, parse it to components (what I referred to as "scripting time" previously) and render it in the dev tools console. There won't be an added benefit for using this API for debugging this issue

**Comment by nbiton** [comment]
I thought you were talking about the benchmark tagging aspect that was talked about in the video. There's no con to what you're suggesting if we can't make the loading time fast enough. It won't really help with the "frozen" part though, as when the UI is frozen, you also can't show a message...
Luckily, that will be resolved as the "frozen" part will be almost unnoticeable once I finish working on the performance optimization phase I'm currently working on.
