### ISSUE TITLE
not a valid case number nor an alias to a case

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#703]
<img width="1680" alt="screenshot 2019-02-04 at 6 17 26 pm" src="https://user-images.githubusercontent.com/765871/52202373-45f85f00-28a9-11e9-90f0-e2de57c62d7c.png">

Unable to create a case in dev.

https://media.dev.unee-t.com/2019-02-04/failed-to-create-case.mp4
https://client-aysiq7n9tw8hfu5rvr6mzf.uilicious.com/studio/project/NAigEgKD6y8qeNMrAZ65oF/monitoring/testRun/5YEj5PKJwyHTbERM4X5zaf

`{ "file": "rest-resource-factory.js", "line": "98", "message": "client request from user qHZeWyfy8tLpuZJ4M to /rest/bug/undefined with {} resulted\n           in an error: { Error: failed [400] {\"message\":\"'undefined' is not a valid case number nor an alias to a case.\",\"code\":100,\"error\":true,\"documentation\":\"https://bugzilla.readthedocs.org/en/5.0/api/\"}\n    at Object.exports.makeErrorByStatus (packages/http.js:176:10)\n    at Request._callback (packages/http.js:140:24)\n    at Request.self.callback (/home/meteor/www/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.\u003canonymous\u003e (/home/meteor/www/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.\u003canonymous\u003e (/home/meteor/www/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)\n  response: \n   { statusCode: 400,\n     content: '{\"message\":\"\\'undefined\\' is not a valid case number nor an alias to a case.\",\"code\":100,\"error\":true,\"documentation\":\"https://bugzilla.readthedocs.org/en/5.0/api/\"}',\n     headers: \n      { date: 'Mon, 04 Feb 2019 10:14:35 GMT',\n        'content-type': 'application/json; charset=UTF-8',\n        'transfer-encoding': 'chunked',\n        connection: 'close',\n        'set-cookie': [Array],\n        server: 'Apache/2.4.29 (Ubuntu)',\n        'access-control-allow-headers': 'origin, content-type, accept, x-requested-with',\n        'access-control-allow-origin': '*',\n        'x-content-type-options': 'nosniff',\n        'x-frame-options': 'SAMEORIGIN',\n        'x-xss-protection': '1; mode=block',\n        etag: 'JPRYxDZbcarCyvyRMfe1Fw' },\n     data: \n      { message: '\\'undefined\\' is not a valid case number nor an alias to a case.',\n        code: 100,\n        error: true,\n        documentation: 'https://bugzilla.readthedocs.org/en/5.0/api/' } } }", "method": "callAPI.then.catch.err", "timestamp": "2019-02-04T10:14:35+0000", "title": "info" }`

Unfurl above like so `jq '.message|fromjson' foo.json`

**Comment by kaihendry** [comment]
https://unee-t.slack.com/archives/C7GL8EHFG/p1549543773241500?thread_ts=1549527834.240400&cid=C7GL8EHFG

**Comment by franck-boullier** [comment]
I just had a look at the DEV/Staging BZFE Db and it looks like all the procedures have been created empty when the restore was done :scream: 

I've just re-created all the procedures for the DEV/Staging now.
These include the correct Lambda for the DEV/STaging environment.
It should (hopefully) work now

@kaihendry can you test that your issue is now fixed please?

**Comment by franck-boullier** [comment]
We need a specific documentation somewhere to describe the very specific procedure that we need to do to restore that very specific DEV/Staging environment.

This will be useful to highlight what are the things that are environment specific too ---> for instance some procedure are calling lambda functions and these are specific to each environment.

We also need to understand why all the procedure that have been restored were empty...

**Comment by kaihendry** [comment]
[ new-user-flow - user journey - chrome (dev laptop) ](https://client-aysiq7n9tw8hfu5rvr6mzf.uilicious.com/studio/project/NAigEgKD6y8qeNMrAZ65oF/monitoring/job/9iYLSHxEJPPxRDQttVSZzz/testRun/list) appears to be working now. In order to test, we should rely on UIlicious or some other test case, and not someone (but yourself) to manually run the test ideally.

I created https://github.com/unee-t/bz-database/issues/111 to track these restore issues.

How do I **test** a procedure has been correctly setup?
