### ISSUE TITLE
Prebuild a Docker image

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#707]
https://github.com/CyCoreSystems/docker-meteor#build-with-bundled-app

**Comment by kaihendry** [comment]
Doing it in https://github.com/unee-t/frontend/blob/hmlet/buildspec.yml but fibers et al, still need to be built on startup since they seem to be missing multistage builds.

https://github.com/CyCoreSystems/docker-meteor/issues/62#issuecomment-466247587

**Comment by PicoCreator** [comment]
I hope you dun mean : https://www.npmjs.com/package/fibers

Cause had quite a fair bit of issue on that one as well (in uilicious) - you will need to ensure that a clean `npm install` is runned on the same flavour and maybe even version of linux as you intend to run the production in.

If you did `npm install` on a mac / ubuntu for example, and transfer the built files into an alpine container. It probably will break (sometimes).
