### ISSUE TITLE
Regression for Unit creation

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#709]
<img src="https://s.natalian.org/2019-02-13/1550020215_2560x1440.png">

https://media.dev.unee-t.com/2019-02-13/400.mp4

Looks like it's caused by commit 228396463437e1af19ae6871bfc62cf390a39216

**Comment by nbiton** [comment]
Resolved by 31d5d84

**Comment by kaihendry** [comment]
Test passes now https://client-aysiq7n9tw8hfu5rvr6mzf.uilicious.com/studio/project/NAigEgKD6y8qeNMrAZ65oF/monitoring/testRun/EFFF4MqVzbs3nLU9ELjqAk
