### ISSUE TITLE
uneet-static-test@inboxkitten.com - account is locked up

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#713]
After the Database was resetted, we tried to re-create the account `uneet-static-test@inboxkitten.com` but it gave the following error during the sign up process

User and password is the same.

![photo_2019-02-14_14-51-58](https://user-images.githubusercontent.com/17175484/52768293-1e9f5000-3068-11e9-80d5-5d70ad14beee.jpg)

Subsequently this account cannot be recreated (REST API error), and/or logged in (Email or password do not match), nor password resetted (500)

![screen shot 2019-02-14 at 2 53 05 pm](https://user-images.githubusercontent.com/17175484/52768427-7342cb00-3068-11e9-89f4-1376cce9a39a.png)

![screen shot 2019-02-14 at 2 55 00 pm](https://user-images.githubusercontent.com/17175484/52768454-89508b80-3068-11e9-901b-1badfb55faaa.png)

Might need a reset of this account, as its used for some test cases.

**Comment by franck-boullier** [comment]
@kaihendry and/or @nbiton any idea what might be causing this?
(PS: this is much less critical than getting the improved notification mechanism up and running but if there is a quick fix for that, feel free to share ;-)

**Comment by nbiton** [comment]
The user might be present in the SQL db so Meteor is unable to recreate it from scratch. I tried to connect to the SQL db, but I cab't get the connection to work for some reason.

**Comment by PicoCreator** [comment]
Note that the test case it affects is specifically `auth/dev` which is scheduled here (requires login) :

https://client-aysiq7n9tw8hfu5rvr6mzf.uilicious.com/studio/project/NAigEgKD6y8qeNMrAZ65oF/monitoring/job/DH92cSubp7qXrvmtVRJ6pu/testRun/list

**Comment by PicoCreator** [comment]
Got the account recreated after the account reset (@kaihendry) - thanks!
