### ISSUE TITLE
Fix invite link for an already registered uesr

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#718]
Slack comment: https://unee-t.slack.com/archives/C6HRDSVGE/p1551246254083700?thread_ts=1551244114.083100&cid=C6HRDSVGE

Given a code like <https://case.demo.unee-t.com/invitation?code=AZIkALpRgSvdxDa2HRWOn7D3> to an already registered user currently on click we see the error message:

<img src="https://media.dev.unee-t.com/2019-02-27/code-invalid.png" alt="Code invalid">

Expectation is the user will be signed in automatically.

**Comment by franck-boullier** [comment]
This is an edge case: it only happens for users who try to access several different account on the same device.

**Comment by franck-boullier** [comment]
@nbiton I think this one is fixed now, closing this
