### ISSUE TITLE
Invalid parameter passed to Bugzilla::Comment::new_from_list: It must be numeric.

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#721]
Just testing if https://github.com/unee-t/bz-database/issues/110 has been fixed by shoving a message with lots of quotation marks:
https://en.wikipedia.org/wiki/Quotation_marks_in_English

It fails: https://media.dev.unee-t.com/2019-03-06/quotation.mp4

**Comment by kaihendry** [comment]
Manage to reduce this to just `"`

**Comment by franck-boullier** [comment]
@nbiton and @kaihendry see the latest tests described here: https://github.com/unee-t/bz-database/issues/118#issuecomment-470092484 which seem to confirm that MEFE is choking on something here (BZFE seems happy by comparaison)...

**Comment by kaihendry** [comment]
This is a bugzilla issue, triggered by the apostrophe in the comment

```
 {"documentation":"https://bugzilla.readthedocs.org/en/5.0/api/","code":52,"message":"Invalid parameter passed to Bugzilla::Comment::new_from_list: It must be numeric.","error":true}
```


Googling the error message finds https://bugzilla.mozilla.org/show_bug.cgi?id=1426117

**Comment by kaihendry** [comment]
curl -s -X POST -H 'Content-type: application/json' -d "{ \"api_key\": \"${APIKEY}\", \"comment\" : \"’🤣\" }" $HOST/rest/bug/${CASEID}/comment

fails with 

```

{"code":100500,"error":true,"documentation":"https://bugzilla.readthedocs.org/en/5.0/api/","message":"DBD::mysql::db do failed: Lambda API returned error: Invalid Request Content. Could not parse request body into json: Invalid UTF-8 start byte 0x92\n at [Source: (byte[])\"{\"case_id\": 75826, \"unit_id\": 2094, \"case_title\": \"Broken bulb\", \"current_status\": \"CONFIRMED\", \"bz_source_table\": \"ut_notification_message_new\", \"notification_id\": \"ut_notification_message_new-80277\", \"created_datetime\": \"2019-08-13 06:54:48.000000\", \"current_severity\": \"normal\", \"message_truncated\": \"ï¿½?\", \"notification_type\": \"case_new_message\", \"created_by_use [for Statement \"INSERT INTO longdescs (who, bug_when, isprivate, bug_id, thetext, work_time) VALUES (?,?,?,?,?,?)\"] at /opt/bugzilla/Bugzilla/DB.pm line 52.\n\tBugzilla::DB::__ANON__(Bugzilla::DB::Mysql=HASH(0x55ea15114b48), \"INSERT INTO longdescs (who, bug_when, isprivate, bug_id, thet\"..., undef, 128, \"2019-08-13 06:54:48\", 0, 75826, \"\\x{2019}\\x{1f923}\", ...) called at /opt/bugzilla/Bugzilla/Object.pm line 746\n\tBugzilla::Object::insert_create_data(\"Bugzilla::Comment\", HASH(0x55ea15741820)) called at /opt/bugzilla/Bugzilla/Bug.pm line 1072\n\tBugzilla::Bug::update(Bugzilla::Bug=HASH(0x55ea15256980)) called at /opt/bugzilla/Bugzilla/WebService/Bug.pm line 1007\n\tBugzilla::WebService::Bug::add_comment(Bugzilla::WebService::Server::REST::Bugzilla::WebService::Bug=HASH(0x55ea15208ed8), HASH(0x55ea15677060)) called at (eval 3070) line 1\n\teval ' $procedure->{code}->($self, $params) ' called at /usr/local/share/perl/5.26.1/JSON/RPC/Legacy/Server.pm line 208\n\tJSON::RPC::Legacy::Server::_handle(Bugzilla::WebService::Server::REST::Bugzilla::WebService::Bug=HASH(0x55ea15208ed8), HASH(0x55ea14b395c8)) called at /opt/bugzilla/Bugzilla/WebService/Server/JSONRPC.pm line 282\n\tBugzilla::WebService::Server::JSONRPC::_handle(Bugzilla::WebService::Server::REST::Bugzilla::WebService::Bug=HASH(0x55ea15208ed8), HASH(0x55ea14b395c8)) called at /opt/bugzilla/Bugzilla/WebService/Server/REST.pm line 98\n\tBugzilla::WebService::Server::REST::handle(Bugzilla::WebService::Server::REST::Bugzilla::WebService::Bug=HASH(0x55ea15208ed8)) called at /opt/bugzilla/rest.cgi line 30\n\tModPerl::ROOT::Bugzilla::ModPerl::ResponseHandler::opt_bugzilla_rest_2ecgi::handler(Apache2::RequestRec=SCALAR(0x55ea150cc048)) called at /usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm line 207\n\teval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm line 207\n\tModPerl::RegistryCooker::run(Bugzilla::ModPerl::ResponseHandler=HASH(0x55ea15f7a8a8)) called at /usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm line 173\n\tModPerl::RegistryCooker::default_handler(Bugzilla::ModPerl::ResponseHandler=HASH(0x55ea15f7a8a8)) called at
/usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/Registry.pm line 32\n\tModPerl::Registry::handler(\"Bugzilla::ModPerl::ResponseHandler\", Apache2::RequestRec=SCALAR(0x55ea150cc048)) called at /opt/bugzilla/mod_perl.pl line 140\n\tBugzilla::ModPerl::ResponseHandler::handler(\"Bugzilla::ModPerl::ResponseHandler\", Apache2::RequestRec=SCALAR(0x55ea150cc048)) called at (eval 3070) line 0\n\teval {...} called at (eval 3070) line 0\n"}
```

Which is related to https://github.com/unee-t/bz-database/issues/73

I've contacted AWS support **CASE 6092011631**  about Unicode issues in **lambda_async** calls, and they suggest:


> As a workaround, I used TO_BASE64() in Aurora DB based and use byte stream based interface in the Lambda function to decode it back on the Lambda end.  A sample function of sending the same is as shown below:
> 
> CALL mysql.lambda_async('arn:aws:lambda:eu-west-1:457855586117:function:mylamda-function-demo', CONCAT('{"test":"', TO_BASE64('{"data": "Jožko  Mrkvičká "}'), '"}'));
> 
> Could you please modify your stored procedures such that the outgoing data is base 64 encoded and wrapped in a JSON object and see whether you also can get the issue fixed?

**Comment by kaihendry** [comment]
Sorry, whilst trying to solve this problem, procedures in DEV have been updated to send the payload via base64 which currently fails like so:

    Could not parse request body into json: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value

I re-raised the issue at https://console.aws.amazon.com/support/cases?#/6092011631/en [and escalated it](https://twitter.com/kaihendry/status/1161508084998647808) since AWS originally said use **base64** to workaround **mysql.lambda_async** Unicode payload issues. And now their base64 encoding appears to add carriage returns and breaks the JSON payload.

AWS support Wilson has reproduced the issue and says:

> I have currently escalated this issue to our internal service team for further investigation. I will update you as soon as I get any updates. In the meantime should you have any additional information, questions or clarifications please do not hesitate to reach us. We will be glad to assist you.

**Comment by kaihendry** [comment]
Btw you will see **Invalid parameter passed to Bugzilla::Comment::new_from_list: It must be numeric.** in any case where MEFE tried to post to access something like **/rest/bug/comment/undefined**.

Bugzilla typically returns 200 even though the commit to SQL failed, e.g. because of https://github.com/unee-t/bz-database/issues/137#issuecomment-523731990 or something other trigger error!!

**Comment by kaihendry** [comment]
Just a reminder with payloads that might contain Unicode, should have TO_BASE64 upon the values to work around this Unicode issue with **mysql.lambda_async** payloads.

https://github.com/unee-t/lambda2sqs/tree/master/push is able to decode base64 encoded values.

**Comment by kaihendry** [comment]
I think this is fixed now:


    curl -i -X POST -H "Content-type: application/json" -d '{ "api_key": "$MY_API_KEY", "comment" : "\"hi\"" }' https://dashboard.dev.unee-t.com/rest/bug/$MY_BUG/comment

**Comment by nbiton** [comment]
Is there anything to implement in MEFE code for this fix to work?
