### ISSUE TITLE
Implement a notification handler for notification_type of 'case_new'

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#729]
Following the findings in #728:
This type has been overlooked when the initial implementation for the notification handlers in MEFE was done.
This type is used when a new case is created under a unit a user is a member of.
We need to decide how this notification would be reflected to the user in the UI and what the email template wording should be.

**Comment by franck-boullier** [comment]
@nbiton keep in mind that only unee-t owner for a given unit will have access to this type of optional notification (i.e 2 conditions must be met for the user to receive the notification here: user is the owner of the unit AND user has chosen to receive this type of `case_new` notifications).

Any other user can only receive a notification for a new case if and only if:
- option 1: he/she is invited to the case AND he/she choose to receive this type of notification
- option 2: he/she is assigned to the case. AND he/she choose to receive this type of notification

> decide how this notification would be reflected to the user in the UI

My suggestion is to add an icon to at the unit level. @kiatlim, can you have a look at this?

> what the email template wording should be.

Let's keep it simple: "A new case [case title] has been added to the unit [unit information]. I was assigned to [assignee role and assignee name]"

This is not high priority though: we have other mechanism for owner of a unit to know if/when a new case is created.

**Comment by franck-boullier** [comment]
Revisiting the priority for this issue.
This type of notification is needed as this is the way to inform:
- Assignee 
- Invited users
That a new case has been created and that they have been either assigned to this case or invited to this case.

We need to notify the assignee and the Invited users IF they have accepted this type of notifications.

**Comment by kiatlim** [comment]
@franck-boullier how would we describe this in a user story way?
Is this correct? "As a user, I can see notifications in a unit when a case is created or has update"

**Comment by nbiton** [comment]
This supposedly affects users who are "default invited" to a case, so they'll be included when it's created.
We need to fix #812 so we can test this properly with a new implemented template for this type
