### ISSUE TITLE
Feat - Better differenciate people associated to the cases

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#73]
Today the list of user invited to a case is as such:
![image](https://user-images.githubusercontent.com/31331637/35078383-06ad7090-fc3d-11e7-9c07-a644ea9e45ab.png)

It would be good if we could differentiate the users based on their relation to the case and to the unit:
- Relation to the case:
  - Reporter: the user who created the case
  - Assignee: the user who is in charge of doing something about it
  - CC: another user in the loop
- Relation to the unit:
  - Tenant (may also be an occupant)
  - Landlord (may also be an occupant)
  - Agent
  - Contractor
  - Management Company

**Comment by franck-boullier** [comment]
@nbiton, any estimates about when we'll be able to implement the latest design for this?   It's much more useful than the current one we have

https://projects.invisionapp.com/d/main#/console/12250377/266322188/preview#project_console

![image](https://user-images.githubusercontent.com/31331637/35526257-cdc43218-0561-11e8-88e8-55f667d50aff.png)

**Comment by nbiton** [comment]
I agree, but there's no estimate for this yet. Maybe we should start tagging issue with primary and secondary priorities

**Comment by franck-boullier** [comment]
Wow you are up late!
Yes I think we need some prioritization mechanism...
This would come after creating a new case and the invitation mechanism IMO

**Comment by franck-boullier** [comment]
Fixed in PR #112
