### ISSUE TITLE
MEFE internal API - Role assignment API - Missing "isDefaultAssigned" in the payload

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#736]
# The Issue:

In Unee-T, when we add a user to a role in a unit, we need to specify the **Default Assignee** for any new cases for a given role in a given unit.
This is propagated in the BZ side of things as the 'Default Assignee' for new cases assigned to a Component/Role in a given Product/Unit.

This is DIFFERENT from 
- the MEFE owner_id ---> gives us information about who is allowed to do changes to the Unit in Unee-T (NOT propagated to the BZ side of things since Mongo is the Source of Truth for Unit information.
- the isDefaultInvited ---> which is propagated as default_cc in the BZ side of things for all new cases in a given Component/Role for a given Unit/Product. 

# What we currently have in the payload:
```
{
	"actionType": "ASSIGN_ROLE",
	"requestorUserId": "R4vBD6BZRCNx8JwnM",
	"addedUserId": "chFmfTz34ahKcSNM9",
	"unitId": "ths88NatbylBl6dPQ",
	"roleType": "Tenant",
	"isOccupant": false,
	"isVisible": false,
	"isDefaultInvited": true,
	"roleVisibility": {
		"Agent": false,
		"Tenant": true,
		"Owner/Landlord": false,
		"Management Company": false,
		"Contractor": true,
		"Occupant": true
	}
}
```
# What we should have in the payload:
```
{
	"actionType": "ASSIGN_ROLE",
	"requestorUserId": "R4vBD6BZRCNx8JwnM",
	"addedUserId": "chFmfTz34ahKcSNM9",
	"unitId": "ths88NatbylBl6dPQ",
	"roleType": "Tenant",
	"isOccupant": false,
	"isVisible": false,
	"isDefaultAssignee": true,
	"isDefaultInvited": true,
	"roleVisibility": {
		"Agent": false,
		"Tenant": true,
		"Owner/Landlord": false,
		"Management Company": false,
		"Contractor": true,
		"Occupant": true
	}
}
```

**Comment by franck-boullier** [comment]
# Important information:

There can be ONLY ONE `isDefaultAssigned` user for a given role in a given unit.

**Comment by nbiton** [comment]
@franck-boullier do you expect the invite lambda to be called with a `"replace_default"` type in this case?

**Comment by franck-boullier** [comment]
> do you expect the invite lambda to be called with a "replace_default" type in this case?

This seems to be the right way to do it yes.

**Comment by franck-boullier** [comment]
fixed in the latest version of the master
