### ISSUE TITLE
http://case.unee-t.com is not routing to https://case.unee-t.com

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#74]
We need to re-route all http traffic to the https version of the site.

**Comment by kaihendry** [comment]
This is best done on the meteor level.

@nbiton something like https://github.com/unee-t/bugzilla/commit/2d839d2da073dbdfb15f0910464936ef0c1226d3 needs to happen on the meteor side

**Comment by nbiton** [comment]
Yeah, I think I should have a way to take care of it from within the Meteor project

**Comment by kaihendry** [comment]
Couldn't get my head around the Meteor force-ssl package.

Asking for help here: https://forums.meteor.com/t/redirect-to-ssl/42811

**Comment by kaihendry** [comment]
Ok, I have a better solution using CloudFront.

**Comment by kaihendry** [comment]
CloudFront cannot be used to with Meteor for the recording since CloudFront can't seem to properly route Web sockets (despite what is said online) to the instance.

**Comment by kaihendry** [comment]
It needs to be done on the App level, i.e. meteor side.

**Comment by nbiton** [comment]
It's merged and deployed. @franck-boullier I'm closing the bug since it works on dev

**Comment by franck-boullier** [comment]
Verified and confirmed working

@nbiton Will the deployment be ok in prod? It seemed that this created a few unexpected issues in the back end... 
See https://twitter.com/kaihendry/status/999579128721428480

**Comment by kaihendry** [comment]
I've updated dev and now demo,prod to accept 302 (the redirect) as a valid success code.

This is atypical. Usually it's 200, so hopefully this won't catch someone else out in the future. A safer approach would be to implement a basic `/health_check` route
