### ISSUE TITLE
MEFE API - Create user - email address is marked as `verified` = `false`

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#741]
# The problem:

When we create Unee-T user with the Create user MEFE API, the email address for that user is set to `verified` = `false` by default.
This is an issue since the notifications are only sent to the Unee-T users with email address `verified` = `true`.

# Proposed solution:

When we create Unee-T user with the Create user MEFE API, the email address for that user should be set to `verified` = `true` by default.

We should:
1- trust that this email address is valid
2- rely on the Unee-T mechanism to inactivate email addresses if these email address are not accepting emails as they should.

@nbiton is this long to do?

**Comment by nbiton** [comment]
No, it shouldn't be long at all, but I'm not fond of the idea- the "verified" flag is designed just for that. We can decide that the first email to the new users will still be sent even if their email is not 'verified' instead of your proposed solution.

**Comment by franck-boullier** [comment]
> I'm not fond of the idea- the "verified" flag is designed just for that.

I understand but this seems to be the fastest/most efficient solution as far as I can tell.
Also since these email addresses are coming from an external system from a trusted user (the Unee-T Enterprise customer that uses this API) we can safely assume that the email they are sending us is clean and that we are authorized to send messages via Unee-T on their behalf to this email address.

> We can decide that the first email to the new users will still be sent even if their email is not 'verified' instead of your proposed solution.

That might be tricky as we'll have to record somewhere that whatever the first message is that we send to this user is the first message for this user ---> this might prove more difficult to implement.

@kaihendry what's your take on this?

**Comment by nbiton** [comment]
The solution we agreed on:
- A "magic link" will always be sent to users invited into a new case, ONLY IF they have not set their password yet.
- If the user already set his/hers password, a normal notification email with a standard case URL will be sent instead of the "magic link".
- The "magic link" link email will be sent to users regardless of the email address verificatio, but will not be sent if the address is tagged as "invalid".

**Comment by franck-boullier** [comment]
Done in the latest version
