### ISSUE TITLE
Bug - "Submit" button on the Sign up page is not working

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#75]
On the page http://case.unee-t.com/signup

When I try to create a user in the MEFE and link it to a user which already exists in the BZFE the 'Submit" button does not work. Nothing happens.

Tested on:
- DT:
  - Firefox
  - Internet Explorer
- Mobile
  - iPhone browser

**Comment by franck-boullier** [comment]
This is now working

**Comment by kaihendry** [comment]
Why did it fail? Perhaps you should add this as a test case for UI-liciuous?
 
Communicate via https://github.com/unee-t/frontend/issues/184
