### ISSUE TITLE
CRITICAL - Latest PR breaks the MEFE (Firefox on a Desktop)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#762]
# The problem:

Since the merge of https://github.com/unee-t/frontend/pull/761 it is impossible to access case.dev.unee-t.com the login page is loading over and over again 

# How to replicate the issue:

go to case.dev.unee-t.com.
Tested with FF on Desktop

**Comment by franck-boullier** [comment]
# More information:

After several minutes of trying to load the page over and over again this error appears

![image](https://user-images.githubusercontent.com/31331637/56464924-550d9880-6426-11e9-8d35-1baeffa1495c.png)

**Comment by franck-boullier** [comment]
# More information:

This seems to happen to Firefox on Iicognito mode only (standard mode seems to work as expected). Removing the 'Critical' tag.

**Comment by franck-boullier** [comment]
# More information:

On FF in standard mode, endless loading page when trying to access the open cases.
Marking this as critical because of that.

![image](https://user-images.githubusercontent.com/31331637/56465043-58a21f00-6428-11e9-88cf-b556de343cf3.png)

**Comment by nbiton** [comment]
t### Reproduction steps
1. Opened Firefox (Running version 57). PASSED
2. Went to case.dev.unee-t.com. PASSED
3. Logged in as test+leonel. PASSED
4. Access Open Cases list. PASSED
5. Accessed a specific case. PASSED

All worked as expected. I can't think of a breaking change that was introduced lately that could cause an issue like this.

**Comment by nbiton** [comment]
Let's close this if we can't reproduce the issue

**Comment by franck-boullier** [comment]
Closing as we are not able to reproduce
