### ISSUE TITLE
User emails are deleted from Mongo - Unee-T breaks

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#767]
# The problem:

Unee-T MEFE stops working: it's impossible to access cases anymore.
Dashboard is still accessible.

Cause of the issue: email address for Nast has been deleted from Mongo

**Comment by kaihendry** [comment]
In the chat @nbiton showed how to see the problem with `db.users.find({emails:{$size:0}})`, but I am unaware how he fixed it.

**Comment by kaihendry** [comment]
Symptom of this error can easily be found be searching the meteor logs for

    in an error: TypeError: Cannot read property 'address' of undefined

**Comment by franck-boullier** [comment]
can we setup an alert for that so we can do something about it before users start complaining.
This will also help us zoom in on the root cause of that issue too.

**Comment by franck-boullier** [comment]
we had the problem twice now.
2 user email addresses have been deleted in the latest instance of the issue...

**Comment by franck-boullier** [comment]
Hotfix is to manually re-create the email information for these users.
