### ISSUE TITLE
DEMO  Environment - Invited users have no way to navigate away from the case

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#772]
# The problem:

- A user is invited to a case
- Invited user clicks on the link to access the case
- Invited user can interact on the case
- Invited user has no way to navigate away from the case (the "back" arrow does nothing)

![image](https://user-images.githubusercontent.com/31331637/57174726-bea19400-6e75-11e9-9932-3154ea6e8470.png)

See the problem in action here:
https://media.dev.unee-t.com/2019-05-04/invited_user_can_not_navigate_unee-t.mp4

**Comment by franck-boullier** [comment]
@nbiton can you think of a quick fix for that?

**Comment by franck-boullier** [comment]
This does not work in the DEMO environment 
Tested during at least 2 demos with Unee-T prospects...

---> re-opening the issue

**Comment by nbiton** [comment]
The fix was delivered in a commit that was not deployed to "demo"

**Comment by franck-boullier** [comment]
fixed in https://github.com/unee-t/frontend/releases/tag/beta-2019-05-23
