### ISSUE TITLE
Bug - DT version scrolling function not working on FF and IE

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#78]
PR #77
On a case https://unee-t-pr-77.herokuapp.com/case/55273 on the DT version the scrolling is not working on Firefox

Consequence: Not able to see the add comment block

![image](https://user-images.githubusercontent.com/31331637/35143794-8f483f56-fd3d-11e7-89b0-70931158c9e3.png)

**Comment by franck-boullier** [comment]
Problem does NOT appear in Chrome

**Comment by franck-boullier** [comment]
Issue is also present on Chrome downloader too (IE)

**Comment by nbiton** [comment]
Tested fix on FF, but not on IE

**Comment by franck-boullier** [comment]
Fix tested on FF and Internet Explorer
Works as intended
