### ISSUE TITLE
API to list cases for a given user - Some cases are missing

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#782]
# The problem

In the DEV/Staging environment.

Cases are missing for MEFE user `jadQkA7qrNAgHhJvZ`

# The test:

## Do a search in the dashboard:

You can use this [search query](https://dashboard.dev.unee-t.com/buglist.cgi?email1=jonathanchua%40cbm.com.sg&emailassigned_to1=1&emailcc1=1&emailreporter1=1&emailtype1=substring&list_id=599427&query_format=advanced&resolution=---).

This returns 36 open cases.

## Use the API to retrieve open cases for that user

This returns only 3 cases.

**Comment by nbiton** [comment]
Are all these cases belong to units that have the same owner?

**Comment by franck-boullier** [comment]
> Are all these cases belong to units that have the same owner?

most certainly yes, all the units that this user has be invited have the same owner (the generic MEFE user associated to the organization that invited this user to these units)

**Comment by franck-boullier** [comment]
We only return the cases for units where th owner id is the same as the MEFE user who generated the API key for the user.
This is expected behavior.
