### ISSUE TITLE
API to retrieve cases for a given user - Add the MEFE Unit ID to the payload

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#785]
# Current situation:

In the current version the API only returns the name of the unit.
(See PR #780).

# Suggested improvement:

In order to allow maximum flexibility, we should also return the MEFE unit ID for the unit where the case belongs.
That way, using the API to retrieve unit information for a given user, an external app will be able to easily include more information about the unit.

**Comment by nbiton** [comment]
The unit id is already included in the response to the API request... It is noted as "_id". Would you like me to change it to something else so it is clearer?

**Comment by franck-boullier** [comment]
> The unit id is already included in the response to the API request...

Ah/! I did not realise that...

> Would you like me to change it to something else so it is clearer?

Yes please.
Something like `unitId` maybe?

**Comment by nbiton** [comment]
No problem :+1:
