### ISSUE TITLE
check that there is no change to make

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#796]
The payloads that originate through lambda2sns from Enterprise API can have two types of errors:

1. Payload is wrong
2. Payload is valid, but the action took took long (POST time out, database time out)

In case 1. lambda2sns will be designed to not return an error, and therefore **not to retry the payload**. However it will report the error to @franck-boullier's database.

In case 2, if the action took too long, lambda2sns will report an error and *by default* the message will be retried with the same request ID shortly. If the valid payload fails again, it will enter the DLQ, which currently notifies me over email about the failing payload.

**Comment by kaihendry** [comment]
@franck-boullier https://s.natalian.org/2019-05-24/uuid.mp4

I could add the *requestID** UUID in lambda2sns myself, but I am reluctant to because it would be better for Enterprise which initiates the payload to track from the Enterprise side.

**Comment by franck-boullier** [comment]
> https://s.natalian.org/2019-05-24/uuid.mp4

@kaihendry the UUID that you'r lookin for is the `mefeAPIRequestId` <--- this is a unique number generated byt the SQL for each new request

**Comment by franck-boullier** [comment]
Clarification to avoid any confusion:

The UUID that you're looking for is the mefeAPIRequestId <--- this is a unique number generated by the SQL for each new request <--- it is already included in the payload that the SQL is sending downstream

**Comment by kaihendry** [comment]
Ok hopefully @nbiton can work with that!

**Comment by kaihendry** [comment]
defer to https://github.com/unee-t/frontend/issues/799

**Comment by kaihendry** [comment]
`mefeAPIRequestId` is expected from _every API_ call so that MEFE can easily discern duplicates.

Not just invites.

**Comment by kaihendry** [comment]
And I'm going to log my complaint that I made earlier on Slack about this design decision.

* having the same ID twice in the payload is daft
* ID integers **will clash**. Making MEFE inevitably reject some requests and people will be scratching their heads wondering why.

Proposal as before, use UUID(), make `mefeAPIRequestId` a string.

**Comment by franck-boullier** [comment]
`mefeAPIRequestId` is now a MySQL UUID passed on to the MEFE (NOT stored in the Unee-T Enterprise)
This should fix all fringe scenario issue and @kaihendry's concerns.
