### ISSUE TITLE
Internal Server Error occurs during sign up

### ISSUE THREAD

**Issue by jmtiong** [unee-t/frontend#802]
When signing up as a new user, internal server error occurred.

One of the example is 
[https://snippet.uilicious.com/embed/test/private/SUvrbhaxaafXSxXYuDATWe?step=7&autoplay=1](https://snippet.uilicious.com/embed/test/private/SUvrbhaxaafXSxXYuDATWe?step=7&autoplay=1)

from step 7 to step 11

**Comment by franck-boullier** [comment]
I'm unable to replicate the problem @jmtiong could this be a false negative?

**Comment by nbiton** [comment]
This probably happened due to the email sending function being disabled on AWS for the DEV environment. It has been re-enabled.
