### ISSUE TITLE
"Generic" case types are not visible in the drop-downs

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#806]
# Background information:

## Selectable values:
The selectable values for `Case Type` depends on the value that was selected in the field `Case Category`.

Case types can be:
- "Generic"case types <--- displayed for ALL the `Case Categories` regardless of what was selected
  Generic case types are 
  - `Repair`
  - `Maintenance`
  - `Replace`
  - `Other`
- "Specific" case type <--- They are displayed only if a certain `Case Category` is selected

Example: 
If the Case Category selected is `Utilities` then, the following Case Types should be selectable:
  - `Repair` <--- "Generic" Case Type
  - `Maintenance` <--- "Generic" Case Type
  - `Replace` <--- "Generic" Case Type
  - `Water` <--- "Specific" Case Type
  - `Gas` <--- "Specific" Case Type
  - `Internet` <--- "Specific" Case Type
  - `Cable` <--- "Specific" Case Type
  - `Other` <--- "Generic" Case Type

## Order in the drop-down list:
The order in the select list is always based on the `sortkey`. We have a `sortkey` for both `Case Category` and `Case Type`. 

## Active vs inactive values:
Lastly we have active and inactive Case Types (same as for Case Categories - See #805).
In the MEFE we should only display the ACTIVE case types.
Active case types are indentified
- In the BZ database, when the records where the field `isactive` = 1
- In the BZFE Admin interface the value `Enabled for cases` = 'No'

# The Problems:

In the MEFE 
1- the "Generic" Case Types are never displayed
2- the Obsolete Case Types are also displayed (similar to #805)

# How to replicate the issue:

In the MEFE in the DEV/Staging
Create a case
Select one of the Case Category <--- "Generic" case types are not visible.

**Comment by franck-boullier** [comment]
# More information:

Based on the BZ documentation, the [BZ API](https://bugzilla.readthedocs.io/en/5.0/api/core/v1/field.html)  does not seem to include the information of whether a field is enabled for cases or not...
Hopefully this is because the API returns only return the active values :crossed_fingers: :pray: ...

**Comment by franck-boullier** [comment]
# More information:

Reading the documentation more closely, it seems that the information is included in the reply

```
is_active | boolean | This value is defined only for certain product-specific fields such as version, target_milestone or component. When true, the value is active; otherwise the value is not active.
```
:tada:

**Comment by franck-boullier** [comment]
We also have the sortkey:
```
sort_key | int | Values, when displayed in a list, are sorted first by this integer and then secondly by their name.
```

**Comment by nbiton** [comment]
What do I need to look for then?

**Comment by franck-boullier** [comment]
Fixed in the latest version of the master.
See https://github.com/unee-t/frontend/commit/de019e5262120a88c27c0367f3dea17679a64445
