### ISSUE TITLE
We should have an "Assigned to Me" Option

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#821]
# The problem:

When creating a case, if a user wants to assign a case to him/herself, the user has to:
- Pick one of the roles at case creation
- Once the case has been created, go to "More information" for that case
- Change the assignee and assign the case to him/herself.

This is a lot of unnecessary clicks.

![image](https://user-images.githubusercontent.com/31331637/59081777-82ed6480-8922-11e9-8949-4e365784fb85.png)

# Possible solution:

Always have an option "Assign the case to Me" (this should be the default selection) each time a user creates a case.

**Comment by ongdominic** [comment]
The solution to this issue is as such:

![Create Case Screen](https://user-images.githubusercontent.com/46714451/59338352-ca199200-8d34-11e9-9483-3ba01eb20494.png)

Details are in [figma](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=3129%3A0)

**Comment by franck-boullier** [comment]
@nbiton can we do a quick fix for that please

**Comment by nbiton** [comment]
Shouldn't the UI mention which role you're in? 
Also, what is the case for when *you* are the default assignee for one of the roles below? (currently it says "you" in parenthesis next to the role)

**Comment by franck-boullier** [comment]
> Shouldn't the UI mention which role you're in?

We discussed that and this might create more confusion for the user <--- we decided to remove that information (until further notice).

>  what is the case for when you are the default assignee for one of the roles below? (currently it says "you" in parenthesis next to the role)

For simplicity, we'll remove that too as this might be too much unnecessary information.

**Comment by nbiton** [comment]
So if I'm the default assignee for tenant, which of the following should I be seeing?
a. "Myself" as the first option, other options follow, "Tenant" is omitted from the list
b. "Myself" as the first option, other options follow, "Tenant" is included in the list (this means there's some duplication in functionality)
c. "Myself" is not mentioned, other options are listed, including "Tenant".

**Comment by franck-boullier** [comment]
> So if I'm the default assignee for tenant, which of the following should I be seeing?
> a. "Myself" as the first option, other options follow, "Tenant" is omitted from the list

No that is NOT the right option: we want to keep things consistent and make sure user always have the same experience/same options to choose from.

> b. "Myself" as the first option, other options follow, "Tenant" is included in the list (this means there's some duplication in functionality)

Yes this is the right option. 
There will indeed be a duplicate functionality: if the user is the default assignee for the role "tenant" then selecting "assign to Myself" or "Assign to the Tenant" will have the same result.

The rationale here is that the Default Assignee for a given role is not necessarily "Me" even if I have a role in that unit AND, at this point, the user has no way to know if he/she is the default assignee for this role for this unit.

> c. "Myself" is not mentioned, other options are listed, including "Tenant".
No this is NOT the correct option: we want to keep things consistent and make sure user always have the same experience/same options to choose from.
