### ISSUE TITLE
Allow the user to delete the next steps and solutions fields in a single tap

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#822]
Suggestion: When each field is focused on, all the input text is marked as highlighted so the next character would delete it all.

**Comment by franck-boullier** [comment]
See also https://github.com/unee-t/frontend/issues/505#issuecomment-424578922:
This is where the latest design for the "Next Step" and "Solution" Fields is documented

**Comment by franck-boullier** [comment]
For the records:

The improved designs of how we can udpate the "Solution" and "Next Steps" already exists in Figma.
We should keep that in mind when we work on this!

![image](https://user-images.githubusercontent.com/31331637/46056824-21ff7100-c185-11e8-901d-317a8a756f6f.png)

and 

![image](https://user-images.githubusercontent.com/31331637/46056836-3cd1e580-c185-11e8-90b2-262934730032.png)

**Comment by ongdominic** [comment]
Here is the solution for this. Details are in [figma](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=4098%3A1051)
![Screenshot 2019-08-21 at 4 12 14 PM](https://user-images.githubusercontent.com/46714451/63414479-83c86980-c42e-11e9-8318-f3d7dc1b89d4.png)
