### ISSUE TITLE
Make it easier to assign a case back to the default assignee for a role in a unit

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#823]
# The Problem:

A user wants to re-assign a case back to the default assignee for the Role.

As of today it's not easy to differentiate the default assignee for a role in a unit from the other user you are allowed to invite

![image](https://user-images.githubusercontent.com/31331637/59090074-4d567480-893e-11e9-90c2-e1b1904890c8.png)

# The need:

We need to make it simple and easy to assign a case back to the default assignee for a given role.

**Comment by kiatlim** [comment]
@franck-boullier apologies, can u elaborate what is this default assignee for a given role? In what context does this happen? Thanks!

**Comment by franck-boullier** [comment]
>  In what context does this happen?

- I'm a field person (maintenance, housekeeper, etc...) or I'm a contractor.
- I've been assigned to a case.
- I've done what I needed to do on that case.
- I need to assign the case back to the default user so this case disappears from the list of cases that are assigned to me.

> what is this default assignee for a given role

Default assignee for a given role is the user that has been setup as the default assignee for this role in this unit.
The default assignee for a given role for a unit is setup when the role is created for that unit.

In the context of this issue, we should NOT concern yourself with how the default assignee is set up.
We can safely assume that he default assignee for a given role for a unit has already been setup correctly.

**Comment by ongdominic** [comment]
This is the solution to this issue:

![more info - assigned to - user list](https://user-images.githubusercontent.com/46714451/59341655-d7d21600-8d3a-11e9-83e6-a17e1d73696d.png)

More details are in [figma](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=3070%3A6483)

**Comment by franck-boullier** [comment]
@nbiton can we also do a quickfix for that (ideally by the end of this week) 🙏 ?

**Comment by nbiton** [comment]
Who are the default assignees? all the default assignees for the available roles of this unit?

**Comment by franck-boullier** [comment]
> Who are the default assignees? all the default assignees for the available roles of this unit?

Yes, the default assignee that we want to display are all the default assignee for the available roles for this unit.
