### ISSUE TITLE
Why are Unee-T Uilicious tests keep failing?

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#825]
# The problem:

Uilicious reports that the test failed BUT I am unable to replicate the error <--- everything is working for me

@PicoCreator can you help me understand what's going on?

```
❗ Test FAILED (unee-t.com - new-user-flow - user journey - chrome (demo laptop))
# Project    : unee-t.com
# Test       : new-user-flow - user journey - chrome (demo laptop)
# Browser    : chrome
# Resolution : 1280x960
# Run ID     : Dhtu3nSZJSKTwY2NMu8Qqc
# Ran On     : 2019-06-10 02:03:40
# Duration : 4m 38s
Last 3 steps before error:
70.  I see "New Case"
71.  I click "New Case"
72.  I am at "https://inboxkitten.com/inbox/uit-tenant-1560103442947/list" 
```

**Comment by jmtiong** [comment]
Hi @franck-boullier! The bug is on inboxkitten.com that it could not read the email key properly. I have fixed it on inboxkitten.com and if I were to directly access the mailbox, it is able to read it properly https://inboxkitten.com/inbox/uit-tenant-1560103442947/detail/se-AgEFQUf2QywgSnyQSl1CM4uzL8-omb3WZA==.

I tried re-running the test case, but it was hit with an internal server error 500. Are you able to try running it again?

**Comment by franck-boullier** [comment]
>  I have fixed it on inboxkitten.com 

OK thanks

> (...) was hit with an internal server error 500. Are you able to try running it again?

I am not able to replicate that error, when exactly does this 500 error happens?

For me 
When I try to access the magic link that is included [here](https://inboxkitten.com/inbox/uit-tenant-1560103442947/detail/se-AgEFQUf2QywgSnyQSl1CM4uzL8-omb3WZA==) this works as intended.
When I try to create a case this works as intended

**Comment by jmtiong** [comment]
for the 500 error, I am not sure if it is a coincidence, every time I run a test, I got hit with a 500 error.

All of it happened during the sign up of a new account, regardless of the test cases.
https://snippet.uilicious.com/embed/test/private/WZ2HTSZjMgCpXbvo3AKd7Q?step=1&autoplay=1
https://snippet.uilicious.com/embed/test/private/LaN4x8R93j2KntaZd1suub?step=1&autoplay=1

**Comment by franck-boullier** [comment]
> sign up of a new account

If I go to case.demo.unee-t.com and try to create a new account I have no error.
Sometime a 500 error like this might be because the email address already exists... (we need to change the text of the error message when this happens).
Are you using a new email address to create that account?

**Comment by jmtiong** [comment]
Yes, I am using a new email address to create a new account.

**Comment by jmtiong** [comment]
Like these two cases, both are using completely random email address but still, it was faced with 500 error.
https://snippet.uilicious.com/embed/test/private/E88Hx3XtWs6NXovBJCEWwj?step=1&autoplay=1
https://snippet.uilicious.com/embed/test/private/HoBscCb2Ha7AekyNXsfg7V?step=1&autoplay=1

**Comment by franck-boullier** [comment]
OK this is weird cause I'm unable to replicate the issue when I create an account manually in the Demo environment (case.demo.unee-t.com) 🤔

**Comment by jmtiong** [comment]
Oh okay, @franck-boullier that explains it. The url that I used was `case.dev.unee-t.com`. For `case.demo.unee-t.com` it is working fine.

But still, for the development link, it is so weird, I found out that even though the test case says it has a 500 error, the account was actually created!
https://snippet.uilicious.com/test/public/2oinGKhAcJSq6fmJrgnjNr
https://snippet.uilicious.com/test/public/Jw89xKGtCnFjnW2A2jT19F

If I did it manually,
![image](https://user-images.githubusercontent.com/16659123/59237729-d535ca80-8c2d-11e9-869d-ba26b8bcdac6.png)

but the account will be created.

**Comment by jmtiong** [comment]
Dev: it is displaying 500 error but the account was created.
Demo: it is working as intended and there are no issues with it :)

**Comment by franck-boullier** [comment]
> Dev: it is displaying 500 error but the account was created.

This is because we have temporarily disabled email notifications in the DEV/staging environment.

> Demo: it is working as intended and there are no issues with it :)

Great. I'm closing this issue then
