### ISSUE TITLE
403 error when trying to reset the MEFE password

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#827]
# Context:

- account has been created
- use can access the dashboard (no issue there)

# What the user wants to do:

- Nath is trying to reset the password for a new employee.

# The problem:

- MEFE does not allow password reset (403) error
![20190611_113044](https://user-images.githubusercontent.com/31331637/59242180-28fbe000-8c3d-11e9-91f4-fcc9ad903d36.jpg)

**Comment by nbiton** [comment]
It appears to be caused because the user's email address is capitalized: 'Shanmuganathan@hmlet.com', so no user record is found for the address that has been typed.
I'm trying to make it case-insensitive now

**Comment by franck-boullier** [comment]
I just tried to reset the password with the email address without a capital letter but the problem is still the same:

![image](https://user-images.githubusercontent.com/31331637/59250019-bac51680-8c58-11e9-88b7-0c13dfae5b0d.png)

**Comment by nbiton** [comment]
Should be resolved by 2a84064, but needs verification

**Comment by franck-boullier** [comment]
Fixed in the latest release
