### ISSUE TITLE
"Assign to Myself" not available for some units

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#842]
# The problem:

In the PROD environment when creating a case for a given unit the option "Assign the case to Myself" is not available

See 
![image](https://user-images.githubusercontent.com/31331637/60226626-a6bb1f00-98be-11e9-8c5e-378cf59a566d.png)

On other units this option is displayed as it should

![image](https://user-images.githubusercontent.com/31331637/60226696-e5e97000-98be-11e9-837e-9277d7f857b0.png)

**Comment by nbiton** [comment]
@franck-boullier : closing this as it was included in the last release
