### ISSUE TITLE
#PR 79 - Regression - display username instead of email addresses

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#88]
If the username exists, we need to display this instead of the email address in the list of users that we could invite.

This used to work earlier but since the horizontal scrolling issue has been fixed, this doesn't seem to work anymore

![image](https://user-images.githubusercontent.com/31331637/35499319-ccb4e368-050c-11e8-93a9-3fc480e746b4.png)

**Comment by nbiton** [comment]
I'll try testing this too, but it's a bit of a problem as I can't see it working for my own MEFE users without setting the permissions. The horizontal scrolling leak was basically just a styling/css fix and shouldn't be related.

**Comment by nbiton** [comment]
Ok... I have no idea how that did even work briefly before:sweat_smile:  I got it working now. Pushing it in a couple of minutes

**Comment by franck-boullier** [comment]
fixed now
