### ISSUE TITLE
Feat - Unable to access Invitation endpoint on dev.case.unee-t.com

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#92]
When I try to see the invitations sent I am unable to access the endpoint
http://dev.case.unee-t.com/api/pending-invitations

This is true for both dev.case.unee-t.com and the PR #91 on Heroku

**Comment by franck-boullier** [comment]
@nbiton OK thanks for the slack message but I'm still not there yet...

What I've done:
1- Change the API_ACCESS_TOKEN key in the AWS console for the DEV environment
2- Go to http://dev.case.unee-t.com/api/pending-invitations?accessToken=[the token I just created]

Expected result: the invitation that I created in PR #79 is visible there

Actual result: the invitation created in PR#79 (for user franck@unee-t.com - BZ id 89) is NOT visible there I only see a blank screen

![error_pending_invitation](https://user-images.githubusercontent.com/31331637/35538466-f52d55f6-0588-11e8-80b3-a8a17bf5d5aa.png)

**Comment by franck-boullier** [comment]
for the records, I just changed the API key in the back end as this is publicly visible...

**Comment by nbiton** [comment]
Can we close this? :)

**Comment by franck-boullier** [comment]
this works once we use the correct API key

**Comment by franck-boullier** [comment]
URL https://unee-t-pr-112.herokuapp.com/api/pending-invitations?accessToken=[the token]
is not working

![image](https://user-images.githubusercontent.com/31331637/35998334-3c0a0a8e-0d57-11e8-8728-b760dd4c89b4.png)

**Comment by franck-boullier** [comment]
fixed in latest version of the PR #112
