### ISSUE TITLE
Bug - New case - Inconsistent Red Square around mandatory Fields (FF)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#93]
When creating a new case, the mandatory fields are highlighted in a red square
![image](https://user-images.githubusercontent.com/31331637/35640318-cac7b20a-06f7-11e8-9ba8-593559c7bc59.png)
We need to also put the Unit in the same red square to cue the user that this is a mandatory field

**Comment by nbiton** [comment]
The bug is the red squares :flushed: 
It's not a part of the design and they should not appear.
The asterisk next to the field label should signify to the user that the field is required.

I'm guessing this is on FF?

**Comment by franck-boullier** [comment]
"I'm guessing this is on FF?"
yes this is in FF

**Comment by nbiton** [comment]
The red squares were removed

**Comment by franck-boullier** [comment]
fixed in latest release
