### ISSUE TITLE
Feat - New Case - Need confirmation of the unit

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#94]
In PR #91
Once a new case is created, there is no way to know in which unit that case has been created.
![image](https://user-images.githubusercontent.com/31331637/35640501-4c56aaba-06f8-11e8-88f1-739f2bff2640.png)
We need to review the Interface to add the unit information somewhere so that there is no confusion from the user about which unit this case has been created into.

**Comment by nbiton** [comment]
Makes sense.
I'd like to get Kiat's input on this :)

**Comment by kiatlim** [comment]
For now I propose to add a unit icon and the unit name above the people involved. Right after the case description.

**Comment by franck-boullier** [comment]
Unit name is visible in the latest version of the PR #91 
Is it possible to also add the Unit Description too?
This is where we will store useful information such as the unit address: this is important so that user know where to go or which unit is this...

The Unee-T Unit Description = BZ API 'description'  of the product object
See https://bugzilla.readthedocs.io/en/5.0/api/core/v1/product.html#list-products

**Comment by nbiton** [comment]
I just added that too. You can review it again in a few minutes

**Comment by franck-boullier** [comment]
Just tested it

we're getting there but I'm unable to see the full description

![image](https://user-images.githubusercontent.com/31331637/35668819-f90fae1c-076d-11e8-97e1-c2c6926cd6a8.png)

We need to have a way to display the description in full so we can see the full address.
Note that description include html styling too.

**Comment by franck-boullier** [comment]
closing this as we now have information about the unit in the details view of a case.

@nbiton there is a bug in how the description is displayed. See issue #101 
@kiatlim the details view is getting quite crowded... We'll probably need to think about how we could make it a bit leaner (multiple tabs? horizontal scroll??)
