### ISSUE TITLE
chore - Unit information briefly disappears during case creation

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#95]
In PR #91 when we create a new case after hitting the add case button the page stays visible for a very short period of time on the mobile.

During that period, all the field are shown as they were entered excepted for the unit field which is voided.

This might create confusion in the user's mind and makes him/her wonder if he/she has selected the correct unit for the case.

**Comment by nbiton** [comment]
Should be fixed on #91, please verify

**Comment by franck-boullier** [comment]
this works in latest version of PR #91
